<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['积分流水管理' => Url::get('credit_rules/index')]
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>流水详情</th>
            <th>交易方</th>
            <th>用户</th>
            <th>类型</th>
            <th>积分</th>
            <th>时间</th>
            <th>状态</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($models = $data->models)) ://99 
            foreach ($models as $v) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="<?= $v->creditTransactions->id ?>"/>
                    </td>
                    <td><?= $v->creditTransactions->detail ?><?=($v->creditTransactions->type==CreditRules::RULE_TYPE_MALL)?" (订单号：".$v->creditTransactions->orderNum.")":""?></td>
                    <td><?= $listtradertype[$v->creditTransactions->trader] ?></td>
                    <td><?= $v->users->name ?></td>
                    <td><?= $listtype[$v->creditTransactions->type] ?></td>
                    <td><?= $v->creditTransactions->credits ?></td>
                    <td><?= date("Y-n-d H:i:s", $v->creditTransactions->created_at) ?></td>
                    <td><?= ($v->creditTransactions->status)?"成功":"失败" ?></td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $data->pagination->render() ;?>
            <div class="pagination-info"><?=Lang::_('total')."： ".$data->count?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        1:{sorter:false},
        3:{sorter:false},
        4:{sorter:false},
        5:{sorter:false},
        6:{sorter:false},
        7:{sorter:false}
    }
});
</script>
