<div class="footer">
    <div class="ui-comwidth ui-cf">
        <!--<div class="footer-friend-links ui-cf">
            <a href="#" target="_blank" title="搜狗网址导航">搜狗网址导航</a>
            <span>|</span>
            <a href="#" target="_blank" title="hao123">hao123</a>
            <span>|</span>
            <a href="#" target="_blank" title="搜狗搜索">搜狗搜索</a>
            <span>|</span>
            <a href="#" target="_blank" title="来电">来电</a>
            <span>|</span>
            <a href="#" target="_blank" title="搜库">搜库</a>
            <span>|</span>
            <a href="#" target="_blank" title="必应">必应</a>
            <span>|</span>
            <a href="#" target="_blank" title="豆瓣">豆瓣</a>
            <span>|</span>
            <a href="#" target="_blank" title="猫扑">猫扑</a>
            <span>|</span>
            <a href="#" target="_blank" title="百度贴吧">百度贴吧</a>
            <span>|</span>
            <a href="#" target="_blank" title="新浪微博">新浪微博</a>
            <span>|</span>
            <a href="#" target="_blank" title="果壳网">果壳网</a>
            <span>|</span>
            <a href="#" target="_blank" title="易迅网">易迅网</a>
            <span>|</span>
            <a href="#" target="_blank" title="人民数字">人民数字</a>
            <span>|</span>
            <a href="#" target="_blank" title="114啦影视">114啦影视</a>
            <span>|</span>
            <a href="#" target="_blank" title="健康卫视">健康卫视</a>
            <span>|</span>
            <a href="#" target="_blank" title="海报网">海报网</a>
            <span>|</span>
            <a href="#" target="_blank" title="电影网">电影网</a>
            <span>|</span>
            <a href="#" target="_blank" title="178游戏网">178游戏网</a>
            <span>|</span>
            <a href="#" target="_blank" title="机友网">机友网</a>
            <span>|</span>
            <a href="#" target="_blank" title="刷机精灵">刷机精灵</a>
            <span>|</span>
            <a href="#" target="_blank" title="智能电视网">智能电视网</a>			
            <span>|</span>
            <a href="#" target="_blank" title="智能电视">智能电视</a>
            <span>|</span>
            <a href="#" target="_blank" title="电视应用市场">电视应用市场</a>
        </div>-->
        <div class="footer-info ui-cf">
            <div class="footer-links ui-cf">
                <a href="http://tv.cztv.com/aboutme/" rel="nofollow" target="_blank" title="关于我们">关于我们</a>
                <span class="line">|</span>
                <a href="http://tv.cztv.com/adservice/" rel="nofollow" target="_blank" title="广告服务">广告服务</a>
                <span class="line">|</span>
                <a href="http://tv.cztv.com/contactus/" rel="nofollow" target="_blank" title="联系我们">联系我们</a>
                <span class="line">|</span>
                <a href="http://tv.cztv.com/jobinfo/" rel="nofollow" target="_blank" title="招聘信息">招聘信息</a>
                <span class="line">|</span>
                <a href="http://tv.cztv.com/privacyinfo/" rel="nofollow" target="_blank" title="保护隐私">保护隐私</a>
                <span class="line">|</span>
                <a href="http://tv.cztv.com/provision/" rel="nofollow" target="_blank" title="免责条款">免责条款</a>
                <span class="line">|</span>
                <a href="http://tv.cztv.com/suggest/" rel="nofollow" target="_blank" title="意见反馈">意见反馈</a>
                <span class="line">|</span>
                <a href="http://list.cztv.com/sitemap/1/1.html" target="_blank" title="网站地图">网站地图</a>
                <span class="line">|</span>
                <a href="http://tv.cztv.com/linkinfo/" target="_blank" title="网站地图">友情链接</a>
            </div>
            <p>Copyright 2009-2015 cztv.com <a href="http://www.miibeian.gov.cn/publish/query/indexFirst.action"
                                               target="_blank">浙ICP备05052141号-1</a>&nbsp;&nbsp;信息网络传播视听节目许可证号：1107197&nbsp;&nbsp;互联网新闻信息服务许可证号：3312011001
            </p>
            <p>地址：浙江省杭州市莫干山路111号&nbsp;&nbsp;邮政编码：310005&nbsp;&nbsp;客服电话：0571-88071234</p>
        </div>
    </div>
</div>
<!-- footer/E-->
<!-- nav-fixed/S-->
<div class="ui-nav-fixed" id="ui-nav-fixed">
    <ul>
        <li>
            <a href="javascript:;" class="ui-icon-gotop" id="gotop" title="返回顶部"><i></i></a>
        </li>
        <li>
            <a href="http://tv.cztv.com" class="ui-icon-home" title="回到首页"><i></i></a>
        </li>
        <li>
            <a href="javascript:;" class="ui-icon-ewm">
                <i></i>
                <p><img src="http://tv.cztv.com/cztv/user/ui-icon-weixin.jpg"/><em></em></p>
            </a>
        </li>
        <li>
            <a href="http://weibo.com/iblue2015" target="_blank" class="ui-icon-weibo"><i></i></a>
        </li>
    </ul>
</div>                  