ALTER TABLE `data` ADD `thumb1` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '缩略图16:10' AFTER `thumb`;
ALTER TABLE `data` ADD `thumb2` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '缩略图1:1' AFTER `thumb1`;
ALTER TABLE `data` ADD `thumb3` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '缩略图10:16' AFTER `thumb2`;
