CREATE TABLE `recycle` (
  `id` int(11) UNSIGNED NOT NULL,
  `channel_id` int(11) UNSIGNED NOT NULL,
  `data_id` int(11) UNSIGNED NOT NULL COMMENT '媒资id',
  `publish_info` text NOT NULL COMMENT '下架前的发布情况json',
  `user_id` int(11) UNSIGNED NOT NULL COMMENT '操作人',
  `created_at` int(11) UNSIGNED NOT NULL COMMENT '删除时间',
  `partition_by` smallint(4) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='回收站'
PARTITION BY RANGE COLUMNS(partition_by)
(
PARTITION p2014 VALUES LESS THAN (2015)ENGINE=InnoDB,
PARTITION p2015 VALUES LESS THAN (2016)ENGINE=InnoDB,
PARTITION p2016 VALUES LESS THAN (2017)ENGINE=InnoDB,
PARTITION p2017 VALUES LESS THAN (2018)ENGINE=InnoDB,
PARTITION p2018 VALUES LESS THAN (2019)ENGINE=InnoDB,
PARTITION p2019 VALUES LESS THAN (2020)ENGINE=InnoDB,
PARTITION p2020 VALUES LESS THAN (2021)ENGINE=InnoDB,
PARTITION p2022 VALUES LESS THAN (2023)ENGINE=InnoDB,
PARTITION p2023 VALUES LESS THAN (2024)ENGINE=InnoDB,
PARTITION p2024 VALUES LESS THAN (2025)ENGINE=InnoDB,
PARTITION p2025 VALUES LESS THAN (2026)ENGINE=InnoDB,
PARTITION pmax VALUES LESS THAN (MAXVALUE)ENGINE=InnoDB
);


ALTER TABLE `recycle`
  ADD PRIMARY KEY (`id`,`partition_by`);


ALTER TABLE `recycle`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;