ALTER TABLE users CHANGE mobile mobile VARCHAR(11) NOT NULL;
ALTER TABLE favorites ADD COLUMN create_date INT(11) NOT NULL DEFAULT 0;
ALTER TABLE baoliao ADD COLUMN location VARCHAR(100) NOT NULL DEFAULT '';