ALTER TABLE `users` ADD COLUMN `score` INTEGER(11) DEFAULT 0 COMMENT '用户积分';

CREATE TABLE IF NOT EXISTS `favorites` (
  `id` INTEGER(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `user_id` INTEGER(11) NOT NULL ,
  `data_id` INTEGER(11) NOT NULL,
  UNIQUE KEY (`user_id`, `data_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户收藏表';

ALTER TABLE `favorites` ADD COLUMN `create_at` INTEGER(11) UNSIGNED COMMENT '创建时间';