<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form action="#" class="form-horizontal form-bordered form-label-stripped">
            <div class="form-body">

                <!--
                <div class="form-group">
                    <label class="control-label col-md-2">按状态</label>
                    <div class="col-md-10">
                        <div class="order-filter">
                            <a href="#">正常</a>
                            <a href="#">睡眠</a>
                            <a href="#">禁用</a>
                        </div>
                    </div>
                </div>
                -->


            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>