<div class="top-menu">
    <ul class="nav navbar-nav pull-right">
        <li class="dropdown dropdown-user">
            <a target="mainiframe" class="dropdown-toggle">
                <img alt="" class="img-circle"
                     src="<?= ($avatar = Session::get('user')->avatar)? $avatar: '/assets/admin/layout/img/avatar.png' ?>"/>
                <span class="username username-hide-on-mobile"><?= Session::get("user")->name ?></span>
            </a>
        </li>

        <li class="dropdown">
            <a class="dropdown-toggle sidebar-toggler tooltips" data-container="body" data-placement="bottom"
               data-trigger="hover" data-html="true" data-original-title="收起左侧菜单"><i class="icon-screen-tablet"></i></a>
        </li>
        <li class="dropdown">
            <a href="#logoutdialog" data-toggle="modal" class="dropdown-toggle tooltips" data-container="body" data-placement="bottom" data-trigger="hover" data-html="true" data-original-title="退出"><i class="icon-logout"></i></a>
        </li>
    </ul>
</div>

<div class="modal fade" id="logoutdialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">退出登录</h4>
            </div>
            <div class="modal-body">
                您确定要退出登录吗？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn blue" onclick="location='<?=Url::get('admin/logout')?>'">确认</button>
                <button type="button" class="btn red" data-dismiss="modal">取消</button>
            </div>
        </div>
    </div>
</div>