<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-site" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>分配用户组</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i>提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <input type="hidden" name="uid" value="<?= $uid ?>" />
            <div class="form-group">
                <label class="control-label col-md-2">用户分组<span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <?php
                    foreach ($usergrouplist as $item):
                        $checked = in_array($item['id'],$mygids)?'checked':'';
                        ?>

                        <label class="sub-checkbox"><input type="checkbox"  class="icheck"  name="sel_group[]" <?=$checked?> value="<?= $item['id'] ?>"/>
                            <?= $item['name'] ?>&nbsp;&nbsp;</label>
                        <?php
                    endforeach;
                    ?>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    // form stations
    $('#form-site').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },
        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            if(element.is(':radio') || element.is(':checkbox')) {
                error.appendTo(element.parents(".icheck-inline"));
            }
            else {
                error.insertAfter(element.closest('.validate-box'));
            }
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>