<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['节目单列表' => Url::get('stations_program/index',array('id'=>Request::get('id')))],
    'add'=> Url::get('stations_program/create',array('id'=>Request::get('id'))),
    'html' => '',
    'import' =>'stations_program/importexcel',
    'interface' => 'stations_program/interface',
    'filterword' => 'stations_program/filterword'
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>时间</th>
                <th>节目名称</th>
                <th>回看（默认允许）</th>
                <th>预约（默认可预约）</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $models = $data->models;
            if (!empty($models)) {
                foreach ($models as $v) {
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" name="selectchecked" value="<?php echo $v->id; ?>"/>
                        </td>
                        <td>
                            <span class="name-center"><?= date('Y-m-d H:i:s',floor($v->start_time/1000)) ?></span>
                        </td>
                        <td><?= $v->title ?></td>
                        <td><?= $v->replay==1?'<i class="fa fa-check"></i>':'<i class="fa fa-times"></i>' ?></td>
                        <td><?= $v->allow_order==1?'<i class="fa fa-check"></i>':'<i class="fa fa-times"></i>' ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn green edit-content tooltips" data-url="/stations_program/modify?id=<?=$v->id?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <button type="button" class="btn red-pink tooltips" onclick="show_confirm(this)" data-url="/stations_program/delete?id=<?= $v->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>

                                <button type="button" class="btn tooltips <?= $v->status==1?'red':'green-jungle' ?>" data-url="/stations_program/hideprogram?id=<?= $v->id ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="<?= $v->status==1?'隐藏该节目':'显示该节目' ?>" onclick="show_confirm(this)"><i class="fa fa-eye-slash"></i></button>

                                <button type="button" class="btn tooltips <?= $v->replay==1?'red':'green-jungle' ?>" data-url="/stations_program/replay?id=<?= $v->id ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="<?= $v->replay==1?'不允许回看':'允许回看' ?>" onclick="show_confirm(this)"><i class="fa fa-mail-reply"></i></button>

                                <button type="button" class="btn tooltips <?= $v->allow_order==1?'red':'green-jungle' ?>" data-url="/stations_program/order?id=<?= $v->id ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="<?= $v->allow_order==1?'不允许预约':'允许预约' ?>" onclick="show_confirm(this)"><i class="fa fa-video-camera"></i></button>
                                
                                <button type="button" class="btn tooltips <?php switch($v->rate_status) {case 0: echo 'blue';break; case 1: echo 'green-turquoise';break; case 2: echo'purple-plum';break; case 3: echo'bg-yellow-saffron';break;case 4: echo'green';break;case 5: echo'red';break; default: echo'blue-steel';break; }?>" data-url="/stations_program/rateVideo?id=<?=$v->id?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" 
                                		data-original-title="<?php switch ($v->rate_status){case 0: echo"VMS录制"; break; case 1: echo"VMS收录中"; break; case 2: echo"VMS录像执行中"; break; case 3: echo"VMS收录失败";break; case 4: echo"VMS录像成功";break; case 5: echo"VMS录像失败";break;}?> " onclick="<?php if($v->rate_status == 0){?>show_confirm(this)<?php }?>"><i class="fa fa-database"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                }
			}
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default tooltips" data-url="<?= Url::get('stations_program/delete');?>" onclick="passnews(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除">删除</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>


<div class="modal fade" id="importexcelForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabe2">上传节目单</h4>
            </div>
            <form id= "uploadForm">
                <div class="modal-body row">

                    <p> <label class="control-label col-md-3">上传节目单</label>
                        <input id="importexcelfile" type="file" multiple="multiple" name="file" />
                    </p>

                    <p><label class="control-label col-md-3">节目单格式:</label>
                    <div>(只支持csv格式，编码为GBK，模板下载<a href="http://ohudong.cztv.com/document/station_program_template.csv" target="_blank">新蓝网后台节目单模板</a>)</div>
                    </p>

                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn blue" data-dismiss="modal" style="width: auto">关闭</button>
                <button type="button" class="btn red"  style="width: auto" onclick="importexcel()">确定</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="filterwordForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabe2">选择过滤内容</h4>
            </div>
            <form id= "uploadForm2">
                <div class="modal-body row">

                    <p> <label class="control-label col-md-3"><input name="filtertype" type="radio" value="1" />指定时间</label>
                        删去少于等于<input type="number" name="filtertime" value="" style="width:60px" />分钟的节目
                    </p>

                    <p> <label class="control-label col-md-3"><input name="filtertype" type="radio" value="2" />指定字段</label>
                        去除标题中的<input type="text" name="filterkeywords" id="filterkeywords" placeholder="过滤词" class="form-control" value="" />
                    </p>

                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn blue" data-dismiss="modal" style="width: auto">关闭</button>
                <button type="button" class="btn red"  style="width: auto" onclick="importexcel2()">确定</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            1:{sorter:false},
            3:{sorter:false},
            4:{sorter:false}
        }
    });

    $('#filterkeywords').tagsInput({
        width: 'auto',
        defaultText: "过滤词"
    });

    function passnews(datatips){
        var checkVal = [];
        $('input[name="selectchecked"]:checked').each(function(){
            checkVal.push($(this).val());
        });
        if (checkVal.length==0){
            alert('你还没有选择任何内容！');
            return false;
        }
        var datatips = $(datatips);
        var datatitle = datatips.attr('data-original-title');
        var datamessage = '确定删除所选节目';
        bootbox.dialog({
            message: datamessage,
            title: datatitle,
            buttons: {
                success: {
                    label: "确定",
                    className: "green",
                    callback: function() {
                        var url =datatips.attr('data-url');
                        $.post(url,{id:checkVal}, function(result){
                            if(result.msg =="success"){
                                location.reload(); 
                            }
                        });
                    }
                },
                danger: {
                    label: "取消",
                    className: "red",
                    callback: function() {

                    }
                }
            }
        });
    }

    function importexcel() {
        var formData = new FormData($("#uploadForm")[0]);
        $.ajax({
            url: '/stations_program/importexcel?id=<?= Request::get('id')?>' ,
            type: 'POST',
            data: formData,
            dataType: 'json',
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            success: function (data) {
                if (data.code == 200) {
                    window.location.reload();
                } else {
                    alert(data.msg);
                }
            },
            error: function (returndata) {
                alert("请求失败");
            }
        });
    }

    function importexcel2() {
        var formData = new FormData($("#uploadForm2")[0]);
        $.ajax({
            url: '/stations_program/filterword?id=<?= Request::get('id')?>&date=<?= $date?:''?>' ,
            type: 'POST',
            data: formData,
            dataType: 'json',
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            success: function (data) {
                if (data.code == 200) {
                    window.location.reload();
                } else {
                    alert(data.msg);
                }
            },
            error: function (returndata) {
                alert("请求失败");
            }
        });
    }
</script>