<?php
Input::init(Request::getPost(), $model);

$create_success = false;
if(isset($messages) && !empty($messages)):
  foreach($messages as $msg):
  if("媒资创建成功"==$msg) $create_success = true;
  endforeach;
endif;

?>
<script type="text/javascript" src="/assets/global/plugins/dropify-master/dist/js/dropify.min.js"></script>
<script type="text/javascript" src="/assets/global/plugins/zyupload/zyupload/zyupload.basic-1.0.0.js"></script><!--批量上传图片插件-->
<link href="/assets/global/plugins/dropify-master/dist/css/dropify.min.css" rel="stylesheet" type="text/css"/>
<link href="/assets/global/plugins/zyupload/zyupload/skins/zyupload-1.0.0.css" rel="stylesheet"  type="text/css"/>
<div class="form page-quick-sidebar-form">
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-publish" >
        <input type="hidden" name="c_id" value="<?=Request::getQuery('category_id','int','0'); ?>" />
        <input type="hidden" id="quotelist_news" name="quotelist_news" value="" />
        <input type="hidden" id="quotelist_album" name="quotelist_album" value="" />
        <input type="hidden" id="quotelist_video" name="quotelist_video" value="" />
        <input type="hidden" id="quotelist_signal" name="quotelist_signal" value="" />
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>新建媒资</span>
            <div class="btn-group">
                <button type="submit" class="btn blue submitbtn"><i class="fa fa-check"></i>提交</button>
            </div>
        </div>
        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>            
            <div class=" row" style="margin-top: 0px">
                <div class="modal-box1">
                    
                    <?= $this->partial('partials/widget/column'); ?>
                    <?= $this->partial('partials/widget/title'); ?>
                    <?= $this->partial('partials/widget/referer'); ?>
                    <?= $this->partial('partials/widget/keywords'); ?>
                    <?= $this->partial('partials/widget/intro'); ?>
                    <?= $this->partial('partials/widget/depart'); ?>
<!--       地图开关        $this->partial('partials/widget/map');     -->
                    <?= $this->partial('partials/widget/flink'); ?>
                    <?= $this->partial('partials/widget/content'); ?>
                </div>
                <div class="modal-box2">
                    <?= $this->partial('partials/widget/author'); ?>
                    <?= $this->partial('partials/widget/thumb'); ?> 
                    <?= $this->partial('partials/widget/interactive'); ?>
                    <?= $this->partial('partials/widget/interviewcontroller'); ?>
                    <?= $this->partial('partials/widget/wxcontroller'); ?>
                </div>
            </div>
        </div>
    </form>
</div>


<style>
    .form .form-horizontal.form-bordered.form-label-stripped .form-group:nth-child(even) {
        background-color: rgba(252, 252, 252, 0);
    }
    .form .form-horizontal.form-bordered.form-label-stripped .form-group:nth-child(even) > div{
        background-color: rgba(10, 10, 10, 0);
    }
    .dropify-clear{
        display: none !important;
    }

    /*::-webkit-scrollbar{*/
        /*width: 0px;*/
    /*};*/
</style>
<script>
    $(function(){
        $('#form-publish').validate({
            errorElement: 'span', //default input error message container
            errorClass: 'help-block', // default input error message class
            focusInvalid: true, // do not focus the last invalid input
            rules: {
                title: {
                    required: true,
                }
            },
            messages: {
                title: {
                    required: '标题不能为空',
                }
            },
            invalidHandler: function(event, validator) {
                //$('.alert-danger', $('.login-form')).show();
            },
            highlight: function(element) { // hightlight error inputs
                $(element).closest('.form-group').addClass('has-error');
            },
            success: function(label) {
                label.closest('.form-group').removeClass('has-error');
                label.remove();
            },
            errorPlacement: function(error, element) {
                error.insertAfter(element.closest('.validate-box'));
            },
            submitHandler: function(form) {
                thumb_url();
                foreign_img_url();
                album_img_url();
                publish_category();
                if(!validate_time()){
                    alert("发布时间晚于当前时间，请重新选择发布时间");
                    return false;
                }

                if(!limittime()){
                    alert("时效时间，结束时间不能小于开始时间");
                    return false;
                }
                if(!validate_referere())
                {
                    alert("引用地址不能为空或者格式不正确，请输入有效的URL地址");
                    return false;
                }
                if(!validate_redirectUrl()){
                    alert("外链格式不能为空或者格式不正确，请输入有效的URL地址");
                    return false;
                }
                if($("#k_input_key").val()=="" && $("#toggle-kl").attr("checked") == "checked"){
                    alert("口令不能为空");
                    return false;
                }

                var xmlhttp = new XMLHttpRequest();
                xmlhttp.open("post","/publish/secretCheck",false);
                xmlhttp.setRequestHeader('content-type','application/x-www-form-urlencoded');
                var args='type=add'+'&secret='+$("#k_input_key").val();
                xmlhttp.send(args);

                if (xmlhttp.responseText == "0") {
                    alert("口令重复");
                    return false;
                }
                if($("#keywords_tagsinput").text().length > 255){
                    alert("关键词不得多于255个字");
                    return false;
                }

                signal_ret = signals_json();
                if(signal_ret == "url false") {
                	alert("请输入正确的url格式地址");
                	return false;
                }
                if(signal_ret == "rate false") {
                	alert("默认码率与已选码率不符合，请核对");
                	return false;
                }

                if(cat_id.length>0)
                {
                 
                    form.submit();
                }
                else{
                    alert("请先选择栏目分类");
                }

                
            }
        });

        //来源1显示隐藏，获取焦点
        $("#source").click(function () {
            $(".sourceinput").hide();
            $(".imgSource").hide();
            $(".OriginalImg").show();
            $(".sourceclass").css("margin-top", "3px");
            $(".sourceclass2").css("margin-left", "10px");
        });
        $("#urlsource").click(function () {
            $(".sourceinput").show();
            $(".imgSource").show();
            $(".OriginalImg").hide();
            $(".sourceinput").focus();
            $(".sourceclass").css("margin-top", "5px");
            $(".sourceclass2").css("margin-left", "44px");
        });
        //来源2显示隐藏，获取焦点
        $(".original").click(function () {
            $(".urlsource2").hide();
        });
        $(".link").click(function () {
            $(".urlsource2").show();
            $(".sourceinput").focus();
        });
        //引用部分切换特效
        $(".quote-modal").mouseenter(function () {
            $(this).children("div:eq(0)").fadeOut();
            $(this).children("div:eq(1)").fadeIn();
        });
        $(".quote-modal").mouseleave(function () {
            $(this).children("div:eq(1)").fadeOut();
            $(this).children("div:eq(0)").fadeIn();
        });
        Address();

        var addressJson= '<?=$channelAddress ?>';
        if(addressJson != ""){
            addressJson = JSON.parse(addressJson);
            $("#province_id").val(addressJson["province_id"]);
            $("#city_id").val(addressJson["city_id"]);
            $("#county_id").val(addressJson["county_id"]);
            $("#town_id").val(addressJson["town_id"]);
            $("#village_id").val(addressJson["village_id"]);
            $("#a_input").val(addressJson["description"]);
        }

    })
    
     $(".submitbtn").click(function () {
        var thumbdata = $(".indexes").find(".dropify-render").children('img').attr("src");//索引部分
        $("#thumb").val(thumbdata);
        var thumbdata2 = $("#input_file2").parent().find(".dropify-preview").children('.dropify-render').children('img').attr("src");//索引部分
        $("input[name='input_file2']").val(thumbdata2);
        var thumbdata3 = $("#input_file3").parent().find(".dropify-preview").children('.dropify-render').children('img').attr("src");//索引部分
        $("input[name='input_file3']").val(thumbdata3);
        var thumbdata4 = $("#input_file4").parent().find(".dropify-preview").children('.dropify-render').children('img').attr("src");//索引部分
        $("input[name='input_file4']").val(thumbdata4);
        var thumbdata5 = $("#input_file5").parent().find(".dropify-preview").children('.dropify-render').children('img').attr("src");//索引部分
        $("input[name='input_file5']").val(thumbdata5);

    });
		
	<?php
	if(true==$create_success) {
	?>
	setTimeout(function() {
	window.parent.exit_iframe();
	}, 1000);	
	<?php
	}
	?>


    $('html', window.parent.document).css('overflow-y','hidden');


</script>
