<?php
Input::init(Request::getPost(), $model);
?>
<div class="form page-quick-sidebar-form">
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-publish" >
        <input type="hidden" name="category_id" id="category_id" value="<?=$category_id ?>" />
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>发布文章</span>
            <div class="btn-group">
                <button type="submit" class="btn blue submitbtn"><i class="fa fa-check"></i>提交</button>
            </div>
        </div>
        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>            
            <div class=" row" style="margin-top: 10px">
                <div class="modal-box1">
                    <?= $this->partial('partials/widget/title'); ?>
                    <?= $this->partial('partials/widget/column'); ?>
                    <?= $this->partial('partials/widget/keywords'); ?>
                    <?= $this->partial('partials/widget/intro'); ?>
                    <?= $this->partial('partials/widget/referer'); ?>
                    <?= $this->partial('partials/widget/depart'); ?>
<!--                   地图开关 $this->partial('partials/widget/map');-->
                    <?= $this->partial('partials/widget/flink'); ?>
                    <?= $this->partial('partials/widget/content'); ?>
                </div>
                <div class="modal-box2">
                    <?= $this->partial('partials/widget/author'); ?>
                    <?= $this->partial('partials/widget/thumb'); ?> 
                    <?= $this->partial('partials/widget/interactive'); ?>
                    <?= $this->partial('partials/widget/interviewcontroller'); ?>
                    <?= $this->partial('partials/widget/wxcontroller'); ?>
                </div>
            </div>
        </div>
    </form>
</div>


<style>
    .form .form-horizontal.form-bordered.form-label-stripped .form-group:nth-child(even) {
        background-color: rgba(252, 252, 252, 0);
    }
    .form .form-horizontal.form-bordered.form-label-stripped .form-group:nth-child(even) > div{
        background-color: rgba(10, 10, 10, 0);
    }
    .dropify-clear{
        display: none !important;
    }
</style>
<script>
    $(function(){
        $('#form-mediapost').validate({
            errorElement: 'span', //default input error message container
            errorClass: 'help-block', // default input error message class
            focusInvalid: true, // do not focus the last invalid input
            rules: {
                title: {
                    required: true,
                    minlength: 6
                },


            },
            messages: {
                title: {
                    required: '标题不能为空',
                    minlength: '标题不能少于6个字'
                },


            },
            invalidHandler: function(event, validator) {
                //$('.alert-danger', $('.login-form')).show();
            },
            highlight: function(element) { // hightlight error inputs
                $(element).closest('.form-group').addClass('has-error');
            },
            success: function(label) {
                label.closest('.form-group').removeClass('has-error');
                label.remove();
            },
            errorPlacement: function(error, element) {
                error.insertAfter(element.closest('.validate-box'));
            },
            submitHandler: function(form) {
                form.submit();
            }
        });


        //来源1显示隐藏，获取焦点
        $("#source").click(function () {
            $(".sourceinput").hide();
            $(".imgSource").hide();
            $(".OriginalImg").show();
            $(".sourceclass").css("margin-top", "3px");
            $(".sourceclass2").css("margin-left", "10px");
        });
        $("#urlsource").click(function () {
            $(".sourceinput").show();
            $(".imgSource").show();
            $(".OriginalImg").hide();
            $(".sourceinput").focus();
            $(".sourceclass").css("margin-top", "5px");
            $(".sourceclass2").css("margin-left", "44px");
        });
        //来源2显示隐藏，获取焦点
        $(".original").click(function () {
            $(".urlsource2").hide();
        });
        $(".link").click(function () {
            $(".urlsource2").show();
            $(".sourceinput").focus();
        });
        //引用部分切换特效
        $(".quote-modal").mouseenter(function () {
            $(this).children("div:eq(0)").fadeOut();
            $(this).children("div:eq(1)").fadeIn();
        });
        $(".quote-modal").mouseleave(function () {
            $(this).children("div:eq(1)").fadeOut();
            $(this).children("div:eq(0)").fadeIn();
        });


        $(".submitbtn").click(function () {
            var thumbdata = $(".indexes").find(".dropify-render").children('img').attr("src");//索引部分
            $("#thumb").val(thumbdata)
        });





    })
    var foreign_img_url = function(){
        var f_img_url = [];
        $(".urlquotespan img").each(function(){
            f_img_url.push($(this).attr("src"))
        })
        $("#f_img_url").val(f_img_url.join(","));
    }
</script>
