xxxxxxxxxxx
<?php
$this->partial("partials/breadcrumb", [
    'urls'=>[$name=>Url::get('specials/index'),'专题分类列表'=>Url::get('special_category/index?id='.$special_id)],
    'add'=>Url::get("special_category/add?id=".$special_id)
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>分类名称</th>
                <th>所属专题</th>
                <th>专题标示符</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (isset($data->models) && !empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle"><input type="checkbox" class="checkboxes" value="1"/></td>
                        <td>
                            <img class="small-img" src="<?php if($v->specialCategory->logo) { echo cdn_url('image',$v->specialCategory->logo); } else{?> /assets/admin/layout/img/avatar.png<?php } ?>" />
                            <?= $v->specialCategory->name ?>
                        </td>
                        <td><?= $v->title ?></td>
                        <td><?= $v->specialCategory->code ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <?php if($checkAuth('special_category/edit')){ ?>
                                <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('special_category/edit',['id'=>$v->specialCategory->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <?php }?>
                                <?php if($checkAuth('special_category/delete')){ ?>
                                <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="<?=Url::get('special_category/delete',['id'=>$v->specialCategory->id])?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                                <?php }?>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button>
                </div>
            </div>
            <?= $data->pagination->render();?>
                <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        4:{sorter:false}
    }
});
</script>