<?php

use GenialCloud\Core\Facade;

/**
 * Class DB
 *
 * @method static null setEventsManager(\Phalcon\Events\ManagerInterface $eventsManager)
 * @method static \Phalcon\Events\ManagerInterface getEventsManager()
 * @method static \Phalcon\Db\Column describeColumns($table, $schema = null)
 * @method static null connect($descriptor = null)
 * @method static \PDOStatement prepare($sqlStatement)
 * @method static \PDOStatement executePrepared(\PDOStatement $statement, $placeholders, $dataTypes)
 * @method static bool|\Phalcon\Db\ResultInterface query($sqlStatement, $bindParams = null, $bindTypes = null)
 * @method static bool execute($sqlStatement, $bindParams = null, $bindTypes = null)
 * @method static int affectedRows()
 * @method static bool close()
 * @method static string escapeIdentifier($identifier)
 * @method static string escapeString($str)
 * @method static array convertBoundParams($sql, $params = array())
 * @method static bool|int lastInsertId($sequenceName = null)
 * @method static bool begin($nesting = true)
 * @method static bool rollback($nesting = true)
 * @method static bool commit($nesting = true)
 * @method static int getTransactionLevel()
 * @method static bool isUnderTransaction()
 * @method static \Pdo getInternalHandler()
 * @method static array getErrorInfo()
 * @method static string getDialectType()
 * @method static string getType()
 * @method static string getSqlVariables()
 * @method static null setDialect(\Phalcon\Db\DialectInterface $dialect)
 * @method static \Phalcon\Db\DialectInterface getDialect()
 * @method static array fetchOne($sqlQuery, $fetchMode = \Phalcon\Db::FETCH_ASSOC, $bindParams = null, $bindTypes = null)
 * @method static array fetchAll($sqlQuery, $fetchMode = \Phalcon\Db::FETCH_ASSOC, $bindParams = null, $bindTypes = null)
 * @method static string fetchColumn($sqlQuery, $placeholders = null, $column = 0)
 * @method static null insert($table, $values, $fields = null, $dataTypes = null)
 * @method static null insertAsDict($table, $data, $dataTypes = null)
 * @method static null update($table, $fields, $values, $whereCondition = null, $dataTypes = null)
 * @method static null updateAsDict($table, $data, $whereCondition = null, $dataTypes = null)
 * @method static bool delete($table, $whereCondition = null, $placeholders = null, $dataTypes = null)
 * @method static string getColumnList($columnList)
 * @method static string limit($sqlQuery, $number)
 * @method static bool tableExists($tableName, $schemaName = null)
 * @method static bool viewExists($viewName, $schemaName = null)
 * @method static string forUpdate($sqlQuery)
 * @method static string sharedLock($sqlQuery)
 * @method static bool createTable($tableName, $schemaName, $definition)
 * @method static bool dropTable($tableName, $schemaName = null, $ifExists = true)
 * @method static bool createView($viewName, $definition, $schemaName = null)
 * @method static bool dropView($viewName, $schemaName = null, $ifExists = true)
 * @method static bool addColumn($tableName, $schemaName, \Phalcon\Db\ColumnInterface $column)
 * @method static bool modifyColumn($tableName, $schemaName, \Phalcon\Db\ColumnInterface $column, \Phalcon\Db\ColumnInterface $currentColumn = null)
 * @method static bool dropColumn($tableName, $schemaName, $columnName)
 * @method static bool addIndex($tableName, $schemaName, \Phalcon\Db\IndexInterface $index)
 * @method static bool dropIndex($tableName, $schemaName, $indexName)
 * @method static bool addPrimaryKey($tableName, $schemaName, \Phalcon\Db\IndexInterface $index)
 * @method static bool dropPrimaryKey($tableName, $schemaName)
 * @method static bool addForeignKey($tableName, $schemaName, \Phalcon\Db\ReferenceInterface $reference)
 * @method static bool dropForeignKey($tableName, $schemaName, $referenceName)
 * @method static string getColumnDefinition(\Phalcon\Db\ColumnInterface $column)
 * @method static array listTables($schemaName = null)
 * @method static array listViews($schemaName = null)
 * @method static \Phalcon\Db\Index describeIndexes($table, $schema = null)
 * @method static \Phalcon\Db\Reference describeReferences($table, $schema = null)
 * @method static array tableOptions($tableName, $schemaName = null)
 * @method static bool createSavepoint($name)
 * @method static bool releaseSavepoint($name)
 * @method static bool rollbackSavepoint($name)
 * @method static \Phalcon\Db\AdapterInterface setNestedTransactionsWithSavepoints($nestedTransactionsWithSavepoints)
 * @method static bool isNestedTransactionsWithSavepoints()
 * @method static string getNestedTransactionSavepointName()
 * @method static \Phalcon\Db\RawValue getDefaultIdValue()
 * @method static \Phalcon\Db\RawValue getDefaultValue()
 * @method static bool supportSequences()
 * @method static bool useExplicitIdValue()
 * @method static array getDescriptor()
 * @method static string getSQLStatement()
 * @method static string getRealSQLStatement()
 * @method static array getSQLBindTypes()
 */
class DB {

    use Facade;

}