<?php isset($votes)?:$votes = array(); ?>
<?php isset($options)?:$options = array(); ?>
<script src="/assets/admin/layout/scripts/base-1.js"></script>
<script src="/assets/admin/layout/scripts/ui-tree-2.js"></script>
<script>
    jQuery(document).ready(function () {
        Metronic.init();
        Layout.init();
        QuickSidebar.init();
        Demo.init();
        //TableManaged.init();
        FormSamples.init();
        ComponentsFormTools.init();
        ComponentsFormTools2.init();
        FormiCheck.init();
        ComponentsPickers.init();
        ComponentsEditors.init();
        PortletDraggable.init();
        FormFileUpload.init();//多文件上传

        UITree.init();

        BaseJs.init();
    });
</script>
<style>
    *{
        font-size: 12px;
    }
    .file-preview{
        width: 230px;
        min-width: 0px ;
        margin-left: 5px;
        display: inline-block;
        vertical-align: middle;
    }
    .file-preview-frame img{
        width: 100px !important;
        height: 100px !important;
    }
    .file-preview-frame{
        margin:0px;
        height: auto;
    }
    .filebtn{
        height: 23px;
        margin-top: -4px;
    }
    .filebtn>i,.filebtn>span{
        font-size: 14px !important;
    }
</style>
<body>
<div class="page-quick-sidebar-title"  style="right: 40px;">
    <span class="page-quick-sidebar-titleinfo font-blue" style="margin-left: 45px"><i class="fa fa-info"></i>修改投票</span>
    <span class="btn green" onclick="vote()" style="float: right;margin-left: 10px;margin-right: 10px">添加投票<i class="fa fa-hand-o-up" style="margin-left: 5px"></i></span>
    <span class="btn blue" style="float: right;" onclick="submitForm()">全部保存<i class="fa fa-save" style="margin-left: 5px"></i></span>

</div>
<div style="height: 36px"></div>
<div class="form page-quick-sidebar-form" style="margin-bottom: 50px">
    <?php $this->partial('partials/error_messages');?>
    <form method="post" class="form-horizontal form-bordered form-label-stripped" id="form-mediapost" enctype="multipart/form-data">
        <div class="modal-vote">
            <?php foreach($votes as $k => $vote) :?>
                <div>
                    <input style="display: none" name="vote_id[<?=$k?>]" value="<?= $vote->id?>"/>
                    <div class="form-group">
                        <label class="control-label col-md-2" style="padding-top: 12px">
                            <span class="btn btn-xs red" data-original-title=“删除投票” data-url="<?= Url::get('vote/votedelete', ['vote_id' => $vote->id,'id' => Request::get('id')]); ?>" style="margin-bottom:3px" onclick="show_confirm(this)">删除投票</span>
                            标题</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" style="width:100%" name="title[<?=$k?>]" value="<?= $vote->title?>"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" style="padding-top: 12px">选项限制</label>

                        <div class="col-md-2 radio-list">
                            <label style="float: left;margin-right: 10px">
                                <input type="radio" class="radios1" name="toasts[<?=$k?>]" value="1" <?= $vote->option_max==1?'checked':'' ?> />单选</label>
                            <label>
                                <input type="radio" class="radios2" name="toasts[<?=$k?>]" value="2" <?= $vote->option_max!=1?'checked':'' ?> />多选</label>
                        </div>

                        <div class="col-md-4 radio-list divall" style="display: <?= $vote->option_max==1?'none':'block'?>">
                            <label style="float: left;margin-right: 10px;margin-right: 10px">
                                最少选&nbsp<input type="text" class="form-control " name="toastsmin[<?=$k?>]" value="<?= $vote->option_min?>" style="width: 50px;display: inline-block;height:25px;text-align: center"/>&nbsp项
                            </label>
                            <label>
                                最多选&nbsp<input type="text" class="form-control " name="toastsmax[<?=$k?>]" value="<?= $vote->option_max?>" style="width: 50px;display: inline-block;height:25px;text-align: center"/>&nbsp项
                            </label>
                        </div>

                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" style="padding-top: 8px">次数限制</label>
                        <div class="col-md-2 radio-list">
                            <label style="margin-bottom: 5px; ">
                                <input type="radio"  name="votenum[<?=$k?>]" value="1" <?= $vote->rate!=0?'checked':'' ?> />
                                <input type="text" style="text-align:center;display: inline-block;width:60px;height:25px" class="form-control " name="votenumtext1[<?=$k?>]" value="<?= $vote->rate!=0?$vote->times:'' ?>" />&nbsp;次/日</label>
                            <label>
                                <input type="radio" name="votenum[<?=$k?>]" value="2" <?= $vote->rate==0?'checked':'' ?> />
                                <input type="text" style="text-align:center;display: inline-block;width:60px;height:25px" class="form-control " name="votenumtext2[<?=$k?>]" value="<?= $vote->rate==0?$vote->times:'' ?>" />&nbsp;次</label>
                        </div>
                        <div class="col-md-7 radio-list">
                            <label style="margin-right: 50px">
                                <input type="radio" name="votetype[<?=$k?>]" value="ip" <?= $vote->type=='ip'?'checked':'' ?> />IP</label>
                            <label style="margin-top: 10px">
                                <input type="radio" name="votetype[<?=$k?>]" value="login" <?= $vote->type=='login'?'checked':'' ?> />登录</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" style="padding-top: 8px">是否使用验证码</label>
                        <div class="col-md-2 radio-list" style="margin-top: 5px">
                            <label style="margin-right: 10px;float: left ">
                                <input type="radio" class="" name="captcha_verify[<?=$k?>]" value="1" <?= $vote->captcha_verify=='1'?'checked':'' ?> />使用</label>
                            <label>
                                <input type="radio" class="" name="captcha_verify[<?=$k?>]" value="2" <?= $vote->captcha_verify=='2'?'checked':'' ?> />不使用</label>
                            <label>
                                <input type="radio" class="" name="captcha_verify[<?=$k?>]" value="3" <?= $vote->captcha_verify=='3'?'checked':'' ?> />使用英文验证码</label>
                            <label>
                                <input type="radio" class="" name="captcha_verify[<?=$k?>]" value="4" <?= $vote->captcha_verify=='4'?'checked':'' ?> />使用中文验证码</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" style="padding-top: 8px">时间限制</label>
                        <div class="col-md-2 radio-list" style="margin-top: 30px">
                            <label style="margin-right: 10px;float: left ">
                                <input type="radio" class="timeradios1" name="timeradios[<?=$k?>]" value="1" <?= $vote->end_time-$vote->start_time>=3600*24*365?'checked':''?> />不限</label>
                            <label>
                                <input type="radio" class="timeradios2" name="timeradios[<?=$k?>]" value="2" <?= $vote->end_time-$vote->start_time<3600*24*365?'checked':''?> />限制</label>
                        </div>
                        <div class="col-md-8" style="display: <?= $vote->end_time-$vote->start_time<3600*24*365?'block':'none'?>;">
                            <span style="float:left;margin-top:8px">开始日期：</span>
                            <div class="input-group date form_datetime input-large">
                                <input type="text" size="18" name="start_time[<?=$k?>]" value="<?= $vote->end_time-$vote->start_time<3600*24*365?date('Y-m-d H:i',$vote->start_time):''?>"  class="form-control" style="cursor: pointer">
                                <span class="input-group-btn">
						        <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
						    </span>
                            </div>
                            <span style="float:left;margin-top:20px">结束日期：</span>
                            <div class="input-group date form_datetime input-large" style="margin-top: 13px">
                                <input type="text" size="18" name="end_time[<?=$k?>]" value="<?= $vote->end_time-$vote->start_time<3600*24*365?date('Y-m-d H:i',$vote->end_time):''?>"  class="form-control" style="cursor: pointer">
                                <span class="input-group-btn">
						        <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" style="padding-top: 8px">选项</label>
                        <div class="col-md-10 ol">
                            <!--//此处为无序列表-->
                            <ol class="olall" type="A" style="margin-left:-24px ;margin-top: 8px">
                                <input class="option_id" value="<?=$k?>" style="display: none" readonly>
                                <?php foreach ($options[$k] as $key => $option) :?>
                                <li>
                                    <input type="hidden" name="option_id[<?=$k?>][<?=$key?>]" value="<?= $option['id']?>"/>
                                    <input type="text" style="margin:50px 20px 0px 0px;width: 400px;display: inline-block" name="option_content[<?=$k?>][<?=$key?>]" value="<?= $option['content']?>" class="form-control "/>
                                    <span style="margin-right:18px;margin-left: -4px">
                                        <span style="margin-right: 2px;margin-left: -4px;">
                                            <div class="imgcheckbox1" style="border: 1px solid rgb(193,193,193);width: 16px;height: 16px;display: inline-block;position: relative;top: 3px;">
                                                <?php if($option['other']==1){?>
                                                    <div style="width: 10px;height: 10px;background-color: #c3c3c3;margin: 2px auto"></div>
                                                <?php }?>
                                                <input name="option_other[<?=$k?>][<?=$key?>]" value="<?= $option['other']?>" style="display: none"/>
                                            </div>&nbsp;填空
                                        </span>
                                        <span><input class="jishu" type="checkbox" checked />显示人数</span><input type="text" style="margin-left:4px;display:inline-block;width:60px;margin-right:9px;height:25px;text-align: center" class="form-control " name="option_sum[<?=$k?>][<?=$key?>]" value="<?= $option['sum']?>"/>
                                        <input style="display: none" name="option_actual_sum[<?=$k?>][<?=$key?>]" value="<?= $option['actual_sum']?>">
                                    </span>
                                    <!--//图片位置-->
                                    <div class="input-large" style="display: inline-block;width: auto!important;margin-right: 5px;margin-left:-3px">
                                        <input type="file" name="thumbnail[<?=$k?>][<?=$key?>]" class="file-loading thumbnail"/>
                                        <input type="hidden" name="option_picture[<?=$k?>][<?=$key?>]" value="<?= $option['picture'] ?>"/>
                                    </div>
                                    <script>
                                        var thumbnailConfig = {
                                            uploadAsync: false,
                                            showRemove: false,
                                            showCaption: false,
                                            showUpload: false,
                                            overwriteInitial: true,
                                            maxFileCount: 1,
                                            language: "zh",
                                            minImageWidth: 100,
                                            minImageHeight: 100,
                                            //单位kb
                                            maxFileSize: 2048,
                                            allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                                            //允许上传 & 允许预览的类型
                                            allowedFileTypes: ['image'],
                                            previewFileType: "image",
                                            browseLabel: '浏览 ...',
                                            browseClass: "btn btn-xs blue filebtn"<?php if($option['picture']) { ?>,
                                            /**
                                             * 预加载数据
                                             */
                                            //预加载删除
                                            initialPreviewShowDelete: false,
                                            //预加载图片
                                            initialPreview: ['<img src="<?= $option['picture']?cdn_url('image',$option['picture']):'' ?>" class="file-preview-image">'],
                                            //预加载图片对应配置
                                            initialPreviewConfig: [{caption: "图片"}]
                                            <?php } ?>
                                        };
                                        $(".thumbnail").fileinput(thumbnailConfig);
                                    </script>
                                    <!--上传视频弹出框开始-->
                                    <span class="btn blue btn-xs uploadvideo" data-toggle="modal" data-target="#myModal<?=$k?>-<?=$key?>" style="margin-bottom: 4px;font-size: 14px;margin-left:-4px;<?= $option['video_url']!=''?'display: none':'' ?>">上传视频</span>
                                    <span class="btn green btn-xs changeurl" data-toggle="modal" data-target="#myModal<?=$k?>-<?=$key?>" style="margin-left: -5px;margin-bottom: 4px;font-size: 14px;<?= $option['video_url']==''?'display: none':'' ?>">更改视频</span>
                                    <span class="btn red btn-xs deleteurl"  style="margin-bottom: 4px;font-size: 14px;margin-left: 0px;<?= $option['video_url']==''?'display: none':'' ?>">删除视频</span>
                                    <div class="modal fade" id="myModal<?=$k?>-<?=$key?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title" id="myModalLabel">上传视频</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>请输入前端页面播放器要求格式的播放地址</p>
                                                    地址:<input type="text" class="form-control  videourl" name="option_video_url[<?=$k?>][<?=$key?>]" value="<?= $option['video_url'] ?>" style="display: inline-block;width: 95%"/>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn blue saveurl" data-dismiss="modal">保存</button>
                                                    <button type="button" class="btn red" data-dismiss="modal">关闭</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <i style="cursor: pointer;color:red" class="fa fa-times-circle fa-inverse removebox"></i>
                                </li>
                                <?php endforeach; ?>
                            </ol>
                            <span class="btn blue btn-sm addvote" style="margin-top: 5px"><i class="fa fa-plus"></i></span>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </form>
</div>
      <script>
          var i=<?= count($votes)-1?>;
          function vote(){
              i++;
              $(".modal-vote").append(
                  '<div>'+
                  '<input style="display: none" name="vote_id['+i+']" value=""/>'+
                  '<div class="form-group">'+
                  '<label class="control-label col-md-2" style="padding-top: 12px"><span class="btn btn-xs red removeall" style="margin-bottom:3px">删除投票</span>标题</label>'+
                  '<div class="col-md-10">'+
                  '<input type="text" style="width:100%" class="form-control " name="title['+i+']" value=""/>'+
                  '</div>'+
                  '</div>'+

                  '<div class="form-group">'+
                  '<label class="control-label col-md-2" style="padding-top: 12px">选项限制</label>'+

                  '<div class="col-md-2 radio-list">'+
                  '<label style="float: left;margin-right: 10px">'+
                  '<input type="radio" class="radios1" name="toasts['+i+']" value="1" checked/>单选</label>'+
                  '<label>'+
                  '<input type="radio" class="radios2" name="toasts['+i+']" value="2"/>多选</label>'+
                  '</div>'+

                  '<div class="col-md-4 radio-list divall" style="display: none">'+
                  '<label style="float: left;margin-right: 10px;margin-right: 10px">'+
                  '<label style="float: left;margin-right: 10px;margin-right: 10px">'+
                  '最少选&nbsp<input type="text" class="form-control " name="toastsmin['+i+']" style="width: 50px;display: inline-block;height:25px;text-align: center"/>&nbsp项'+
                  '</label>'+
                  '<label>'+
                  '最多选&nbsp<input type="text" class="form-control " name="toastsmax['+i+']" style="width: 50px;display: inline-block;height:25px;text-align: center"/>&nbsp项'+
                  '</label>'+
                  '</label>'+
                  '</div>'+

                  '</div>'+
                  '<div class="form-group">'+
                  '<label class="control-label col-md-2" style="padding-top: 8px">次数限制</label>'+
                  '<div class="col-md-3 radio-list">'+
                  '<label style="margin-bottom: 5px; ">'+
                  '<input type="radio" name="votenum['+i+']" value="1"  checked/>' +
                  '<input type="text" name="votenumtext1['+i+']" class="form-control " style="text-align:center;display: inline-block;width:60px;height:25px"/>&nbsp;次/日</label>'+
                  '<label>'+
                  '<input type="radio" name="votenum['+i+']" value="2"/>' +
                  '<input type="text" name="votenumtext2['+i+']" class="form-control " style="text-align:center;display: inline-block;width:60px;height:25px"/>&nbsp;次</label>'+
                  '</div>'+
                  '<div class="col-md-7 radio-list">'+
                  '<label  style="margin-right: 50px">'+
                  '<input type="radio" name="votetype['+i+']" value="ip"  checked/>IP</label>'+
                  '<label style="margin-top: 10px">'+
                  '<input type="radio" name="votetype['+i+']" value="login"/>登录</label>'+
                  '</div>'+
                  '</div>'+
                  '<div class="form-group"> ' +
                  '<label class="control-label col-md-2" style="padding-top: 8px">是否使用验证码</label> ' +
                  '<div class="col-md-2 radio-list" style="margin-top: 5px"> ' +
                  '<label style="margin-right: 10px;float: left "> ' +
                  '<input type="radio" class="" name="captcha_verify['+i+']" value="1" />使用</label> ' +
                  '<label> ' +
                  '<input type="radio" class="" name="captcha_verify['+i+']" value="2" checked />不使用</label> ' +
                  '<label> ' +
                  '<input type="radio" class="" name="captcha_verify['+i+']" value="3" />使用英文验证码</label> ' +
                  '<label> ' +
                  '<input type="radio" class="" name="captcha_verify['+i+']" value="4" />使用中文验证码</label>' +
                  '</div> ' +
                  '</div>'+
                  '<div class="form-group">'+
                  '<label class="control-label col-md-2" style="padding-top: 8px">时间限制</label>'+
                  '<div class="col-md-2 radio-list"  style="margin-top: 5px">'+
                  '<label style="margin-bottom: 5px; float: left;margin-right:10px">'+
                  '<input type="radio" class="timeradios1" name="timeradios['+i+']" value="1" checked/>不限</label>'+
                  '<label>'+
                  '<input type="radio" class="timeradios2" name="timeradios['+i+']" value="2"/>限制</label>'+
                  '</div>'+
                  '<div class="col-md-8" style="display:none;">'+
                  '<span style="float:left;margin-top:8px">开始日期：</span>'+
                  '<div class="input-group date form_datetime input-large">'+
                  '<input type="text" size="18" name="start_time['+i+']" readonly class="form-control">'+
                  '<span class="input-group-btn">'+
                  '<button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>'+
                  '</span>'+
                  '</div>'+
                  '<span style="float:left;margin-top:20px">结束日期：</span>'+
                  '<div class="input-group date form_datetime input-large" style="margin-top: 13px">'+
                  '<input type="text" size="18" name="end_time['+i+']" readonly class="form-control">'+
                  '<span class="input-group-btn">'+
                  '<button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>'+
                  '</span>'+
                  '</div>'+
                  '</div>'+
                  '</div>'+

                  '<div class="form-group">'+
                  '<label class="control-label col-md-2" style="padding-top: 8px">选项</label>'+
                  '<div class="col-md-10 ol">'+
                  //此处为无序列表
                  '<ol class="olall" type="A" style="margin-left:-24px ;margin-top: 8px">' +
                  '<input class="option_id" value="'+i+'" style="display: none" readonly>'+
                  '<li><input type="text" name="option_content['+i+'][]" style="margin:50px 20px 0px 0px;width: 400px;display: inline-block" class="form-control "/>' +
                  '<span style="margin-right:20px;margin-left: -4px">'+
                  '<span style="margin-right: 3px">'+
                  '<div class="imgcheckbox " style="border: 1px solid rgb(193,193,193);width: 16px;height: 16px;display: inline-block;position: relative;top: 3px;">'+
                  '<input name="option_other['+i+'][]" value="0" style="display: none"/>'+
                  '</div>&nbsp;&nbsp;填空&nbsp;'+
                  '</span>'+
                  '<span><input class="jishu" type="checkbox" />显示人数</span><input type="text" style="margin-left:4px;display:none;width:60px;margin-right:11px;height:25px;text-align:center" class="form-control " name="option_sum['+i+'][]" value=""/>'+
                  '<input style="display: none" name="option_actual_sum['+i+'][]" value="">'+
                  '</span>'+
                  //图片位置
                  '<div class="input-large" style="display: inline-block;width: auto!important;margin-right: 5px;margin-left:-3px"> ' +
                  '<input type="file" name="thumbnail['+i+'][]" class="file-loading thumbnail"/> ' +
                  '<input type="hidden" name="option_picture['+i+'][]" value=""/> ' +
                  '</div> ' +
                  <!--上传视频弹出框开始-->
                  '<span class="btn blue btn-xs uploadvideo" data-toggle="modal" data-target="#myModal'+i+'" style="margin-bottom: 4px;font-size: 14px">上传视频</span>'+
                  '<span class="btn green btn-xs changeurl" data-toggle="modal" data-target="#myModal'+i+'" style="margin-bottom: 4px;font-size: 14px;display: none;margin-left:0px">更改视频</span>'+
                  '<span class="btn red btn-xs deleteurl" onclick="deleteurl()" style="margin-bottom: 4px;font-size: 14px;display: none;margin-left: 5px;">删除视频</span>'+
                  '<div class="modal fade" id="myModal'+i+'" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">'+
                  '<div class="modal-dialog" role="document">'+
                  '<div class="modal-content">'+
                  '<div class="modal-header">'+
                  '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
                  '<h4 class="modal-title" id="myModalLabel">上传视频</h4>'+
                  '</div>'+
                  '<div class="modal-body">'+
                  '<p>请输入前端页面播放器要求格式的播放地址</p>'+
                  'URL:<input type="text" class="form-control  videourl" name="option_video_url['+i+'][]"/>'+
                  '</div>'+
                  '<div class="modal-footer">'+
                  '<button type="button" class="btn blue saveurl" data-dismiss="modal" onclick="saveurl()">保存</button>'+
                  '<button type="button" class="btn red" data-dismiss="modal">关闭</button>'+
                  '</div>'+
                  '</div>'+
                  '</div>'+
                  '</div>'+
                  '&nbsp;<i style="cursor: pointer;color:red" class="fa fa-times-circle fa-inverse removebox"></i>' +
                  '</ol>'+
                  '<span class="btn blue btn-sm addvote" style="margin-top: 5px"><i class="fa fa-plus"></i></span>'+
                  '</div>'+
                  '</div>'+

                  '<div class="form-group">'+
                  '<div class="col-md-12" style="text-align: center">'+
                  '</div>'+
                  '</div>'+
                  '</div>'
              );
              var thumbnailConfig = {
                  uploadAsync: false,
                  showRemove: false,
                  showCaption: false,
                  showUpload: false,
                  overwriteInitial: true,
                  maxFileCount: 1,
                  language: "zh",
                  minImageWidth: 100,
                  minImageHeight: 100,
                  //单位kb
                  maxFileSize: 2048,
                  allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                  //允许上传 & 允许预览的类型
                  allowedFileTypes: ['image'],
                  previewFileType: "image",
                  browseLabel: '浏览 ...',
                  browseClass: "btn btn-xs blue filebtn"
              };
              $(".thumbnail").fileinput(thumbnailConfig);
              Metronic.init();
              Layout.init();
              QuickSidebar.init();
              Demo.init();
              //TableManaged.init();
              FormSamples.init();
              ComponentsFormTools.init();
              ComponentsFormTools2.init();
              FormiCheck.init();
              ComponentsPickers.init();
              ComponentsEditors.init();
              PortletDraggable.init();
              FormFileUpload.init();//多文件上传
              UITree.init();
              BaseJs.init();
          }
          function submitForm(){
              $('#form-mediapost').submit();
          }
          $(".modal-vote").on("click",".radios1",function(){
              //单选
              $(this).parent().parent().parent().parent().next().css("display","none");
              $(this).parent().parent().parent().parent().next().next().css("display","none");
          });
          $(".modal-vote").on("click",".radios2",function(){
              //多选
              $(this).parent().parent().parent().parent().next().css("display","block");
          });
          $(".modal-vote").on("click",".radios3",function(){
              //选项不限
              $(this).parent().parent().parent().parent().next().css("display","none");
          });
          $(".modal-vote").on("click",".radios4",function(){
              //选项限制
              $(this).parent().parent().parent().parent().next().css("display","block");
          });
          $(".modal-vote").on("click",".timeradios1",function(){
              //时间不限
              $(this).parent().parent().parent().parent().css("margin-top","0px");
              $(this).parent().parent().parent().parent().next().css("display","none");
          });
          $(".modal-vote").on("click",".timeradios2",function(){
              //时间限制
              $(this).parent().parent().parent().parent().css("margin-top","30px");
              $(this).parent().parent().parent().parent().next().css("display","block");
          });
          var d=0;
          $(".modal-vote").on("click",".addvote",function(){
              //添加
              d++;
              var c="c"+d;
              var option_id = $(this).parent().children(".olall").children(".option_id").val();
              $(this).parent().children(".olall").append(
                  "<li style='margin-top:5px '>" +
                  "<input type='text' name='option_content["+option_id+"][]' style='margin:5px 20px 0px 0px;width: 400px;display: inline-block' class='form-control '/>" +
                  '<span style="margin-right:20px;margin-left: -4px">'+
                  '<span style="margin-right: 4px;">'+
                  '<div class="imgcheckbox " style="border: 1px solid rgb(193,193,193);width: 16px;height: 16px;display: inline-block;position: relative;top: 3px;">'+
                  '<input name="option_other['+option_id+'][]" value="0" style="display: none"/>'+
                  '</div>'+
                  '&nbsp;&nbsp;填空&nbsp;'+
                  '</span>'+
                  '<span><input type="checkbox" class="jishu" />显示人数</span><input type="text" style="margin-left:4px;display:none;width:60px;height: 25px;margin-right:10px;" class="form-control " name="option_sum['+option_id+'][]" value=""/>'+
                  '<input style="display: none" name="option_actual_sum['+option_id+'][]" value="">'+
                  '</span>'+
                  //图片位置
                  '<div class="input-large" style="display: inline-block;width: auto!important;margin-right: 5px;margin-left:-3px"> ' +
                  '<input type="file" name="thumbnail['+option_id+'][]" class="file-loading thumbnail"/> ' +
                  '<input type="hidden" name="option_picture['+option_id+'][]" value=""/> ' +
                  '</div> ' +
                  <!--上传视频弹出框开始-->
                  '<span class="btn blue btn-xs uploadvideo" data-toggle="modal" data-target="#myModal'+c+'" style="margin-bottom: 4px;font-size: 14px">上传视频</span>'+
                  '<span class="btn green btn-xs changeurl" data-toggle="modal" data-target="#myModal'+c+'" style="margin-left: 0px;margin-bottom: 4px;font-size: 14px;display: none">更改视频</span>'+
                  '<span class="btn red btn-xs deleteurl" style="margin-bottom: 4px;font-size: 14px;display: none;margin-left: 5px;">删除视频</span>'+
                  '<div class="modal fade" id="myModal'+c+'" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">'+
                  '<div class="modal-dialog" role="document">'+
                  '<div class="modal-content">'+
                  '<div class="modal-header">'+
                  '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
                  '<h4 class="modal-title" id="myModalLabel">上传视频</h4>'+
                  '</div>'+
                  '<div class="modal-body">'+
                  '<p>请输入前端页面播放器要求格式的播放地址</p>'+
                  'URL:<input type="text" class="form-control  videourl" name="option_video_url['+option_id+'][]" />'+
                  '</div>'+
                  '<div class="modal-footer">'+
                  '<button type="button" class="btn blue saveurl" data-dismiss="modal" onclick="saveurl()">保存</button>'+
                  '<button type="button" class="btn red" data-dismiss="modal">关闭</button>'+
                  '</div>'+
                  '</div>'+
                  '</div>'+
                  '</div>'+
                  "&nbsp;<i style='cursor: pointer;color: red' class='fa fa-times-circle fa-inverse removebox'></i>" +
                  "</li>");
              var thumbnailConfig = {
                  uploadAsync: false,
                  showRemove: false,
                  showCaption: false,
                  showUpload: false,
                  overwriteInitial: true,
                  maxFileCount: 1,
                  language: "zh",
                  minImageWidth: 100,
                  minImageHeight: 100,
                  //单位kb
                  maxFileSize: 2048,
                  allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                  //允许上传 & 允许预览的类型
                  allowedFileTypes: ['image'],
                  previewFileType: "image",
                  browseLabel: '浏览 ...',
                  browseClass: "btn btn-xs blue filebtn"
              };
              $(".thumbnail").fileinput(thumbnailConfig);
              Metronic.init();
              Layout.init();
              QuickSidebar.init();
              Demo.init();
              //TableManaged.init();
              FormSamples.init();
              ComponentsFormTools.init();
              ComponentsFormTools2.init();
              FormiCheck.init();
              ComponentsPickers.init();
              ComponentsEditors.init();
              PortletDraggable.init();
              FormFileUpload.init();//多文件上传
              UITree.init();
              BaseJs.init();
          });
          $(".modal-vote").on("click",".removebox",function(){
              $(this).parent().remove();
          });

          $(".modal-vote").on("click",".removeall",function(){
              $(this).parent().parent().nextAll().remove();
              $(this).parent().parent().parent().remove();
          });
          $(".radios1").click(function(){//       静态单选
              $(this).parent().parent().parent().parent().next().css("display","none");
              $(this).parent().parent().parent().parent().next().next().css("display","none");
          });
          $(".radios2").click(function(){//静态多选
              $(this).parent().parent().parent().parent().next().css("display","block");
          });
          $(".radios3").click(function(){//静态选项不限
              $(this).parent().parent().parent().parent().next().css("display","none");
          });
          $(".radios4").click(function(){//静态选项限制
              $(this).parent().parent().parent().parent().next().css("display","block");
          });
          $(".timeradios1").click(function(){//静态时间不限
              $(this).parent().parent().parent().parent().next().css("display","none");
          });
          $(".timeradios2").click(function(){//静态限制时间
              $(this).parent().parent().parent().parent().next().css("display","block");
          });

          //静态页面上传视频
          //保存
          $(".saveurl").click(function(){
              var val=$(this).parent().prev().children(".videourl").val();
              if (val!==""){
                  $(this).parent().parent().parent().parent().prev().prev().prev().css("display","none");
                  $(this).parent().parent().parent().parent().prev().prev().css("display","inline-block");
                  $(this).parent().parent().parent().parent().prev().css("display","inline-block");
              }else{

              }
          });
          //删除
          $(".deleteurl").click(function(){
              $(this).next().children().children().children(".modal-body").children(".videourl").val(" ");
              $(this).prev().prev().css("display","inline-block");
              $(this).prev().css("display","none");
              $(this).css("display","none");
          });
          //
          //静态页面上传视频
          //动态页面上传视频
          $(".modal-vote").on("click",".saveurl",function(){
              var val=$(this).parent().prev().children(".videourl").val();
              if (val!==""){
                  alert("保存成功！");
                  $(this).parent().parent().parent().parent().prev().prev().prev().css("display","none");
                  $(this).parent().parent().parent().parent().prev().prev().css("display","inline-block");
                  $(this).parent().parent().parent().parent().prev().css("display","inline-block");
              }else{
                  alert("输入不可为空！");
              }
          });
          $(".modal-vote").on("click",".deleteurl",function(){
              $(this).next().children().children().children(".modal-body").children(".videourl").val(" ");
              alert("删除成功！");
              $(this).prev().prev().css("display","inline-block");
              $(this).prev().css("display","none");
              $(this).css("display","none");
          });

          //静态页面图片checkbox
          $(".imgcheckbox1").click(function(){
              if($(this).children('div').is("div")){
                  $(this).children('div').remove();
                  $(this).children('input').val(0);
              }else{
                  $(this).append('<div style="width: 10px;height: 10px;background-color: #c3c3c3;margin: 2px auto"></div>');
                  $(this).children('input').val(1);
              }
          });
          //动态页面图片checkbox
          $(".modal-vote").on("click",".imgcheckbox",function(){
              if($(this).children('div').is("div")){
                  $(this).children('div').remove();
                  $(this).children('input').val(0);
              }else{
                  $(this).append('<div style="width: 10px;height: 10px;background-color: #c3c3c3;margin: 2px auto"></div>');
                  $(this).children('input').val(1);
              }
          });

          //静态显示人数
          $(".jishu").change(function() {
              var a=$(this).attr("checked")=="checked";
              if(a){
                  $(this).parent().parent().parent().next().css("display","inline-block");
              }else{
                  $(this).parent().parent().parent().next().css("display","none");
              }
          });
          $(".modal-vote").on("click",".jishu",function(){
              var a=$(this).attr("checked")=="checked";
              if(a){
                  $(this).parent().parent().parent().next().css("display","inline-block");
              }else{
                  $(this).parent().parent().parent().next().css("display","none");
              }
          });

      </script>
</body>
</html>