<div class="form-group">
    <label class="col-md-2 control-label">频道 <span class="font-red">*必填</span></label>
    <div class="col-md-10">
        <select class="form-control select_selectsplitter" size="4">
            <option value="1">国内新闻</option>
            <option value="2">杭州新闻</option>
            <option value="3">国际新闻</option>
            <option value="4">浙江之声</option>
            <option value="5">社会热点</option>
            <option value="6">时下热点</option>
        </select>
    </div>
</div>