<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-users" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加会员</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>

            <div class="form-group">
                <label class="control-label col-md-2">头像 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="avatarnail" id="avatarnail" class="file-loading"/>
                        <input type="hidden" name="avatar" value=""/>
                    </div>
                    <span class="help-block">请上传图片大小为120px-120px</span>
                </div>
            </div>
            <script>
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    minFileCount: 1,
                    maxFileCount: 1,
                    language: "zh",
                    minImageWidth: 100,
                    minImageHeight: 100,
                    //单位kb
                    maxFileSize: 2048,
                    allowedFileExtensions : ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'
                };
                $("#avatarnail").fileinput(thumbnailConfig);
            </script>

            <div class="form-group">
                <label class="control-label col-md-2">手机号码 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="mobile" placeholder="手机号码" maxlength="11" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">用户状态 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label><input type="radio" class="icheck" name="status" value="1" checked/>开启</label>
                        <label><input type="radio" class="icheck" name="status" value="0"/>禁用</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">用户名 <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="text" name="name" placeholder="用户名" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">密码 <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="password" name="password" placeholder="密码" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">会员等级 <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="text" name="grade" placeholder="会员等级" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">用户昵称 <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="text" name="nickname" placeholder="用户昵称" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">用户签名 <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="text" name="signature" placeholder="用户签名" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">用户真名 <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="text" name="realname" placeholder="用户真名" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">用户邮箱 <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="text" name="email" placeholder="用户邮箱" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">用户QQ <span class="font-red"></span></label>
                <div class="col-md-10">
                    <input type="text" name="qq" placeholder="用户QQ" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">

    jQuery.validator.addMethod("issecurity", function(value, element) {
        var length = value.length;
        var lv = -1;
        if (value.match(/[a-z]/ig)){ lv++; }
        if (value.match(/[0-9]/ig)){ lv++; }
        if (value.match(/(.[^a-z0-9])/ig)){ lv++; }
        if (length < 6 && lv > 0){ lv--; }
        if (lv < 1) {
            return false;
        }
        else {
            return true;
        }
    }, "密码长度不能少于6位");

    jQuery.validator.addMethod("isChinese", function(value, element) {
        return this.optional(element) || /^[\u4e00-\u9fa5]+$/.test(value);
    });

    jQuery.validator.addMethod("ismobile", function(value, element) {
        var length = value.length;
        var mobile = /^1[3|4|5|7|8|][0-9]{9}$/;
        return this.optional(element) || (length == 11 && mobile.test(value));
    }, "请输入正确的手机号码");

    function issecurity2(value) {
        var length = value.length;
        var lv = -1;
        if (value.match(/[a-z]/ig)){ lv++; }
        if (value.match(/[0-9]/ig)){ lv++; }
        if (value.match(/(.[^a-z0-9])/ig)){ lv++; }
        if (length < 6 && lv > 0){ lv--; }
        if (lv < 1) {
            return false;
        }
        else {
            return true;
        }
    }

    // form stations
    $('#form-users').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            mobile: {
                required: true,
                ismobile: true
            },
            email: {
                email: true
            },
            qq: {
                digits: true
            }
        },

        messages: {
            mobile: {
                required: '手机号码不能为空',
                ismobile: '请输入正确的手机号码'
            },
            email: {
                email: '请输入正确的邮箱地址'
            },
            qq: {
                digits: '请输入正确的QQ号'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>