<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['节目站点设置' => Url::get('stations_set/index')],
    'add'=> Url::get('stations_set/create'),
    'html' => '',
]);
?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
				<th class="">站点ID</th> 
                <th width="10%" class="">站点名称</th>
                <th width="18%" class="">频道Guid</th>
                <th class="">站点路径</th>
                <th class="">视频码率</th>
                <th class="">视频格式</th>
                <th class="">更新时间</th>
                <th class="">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" name="selectchecked" value="<?php echo $v->id; ?>"/>
                    </td>
                        <td><?= $v->vms_siteId ?></td>
                        <td><?= $v->station_name ?></td>
                        <td><?= $v->station_guid ?></td>
                        <td><?= $v->station_file ?></td>
                        <td><?= $v->bitrate ?></td>
                        <td><?= $v->format ?></td>
                        <td><?= date('Y-m-d H:i:s',$v->update_time) ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn green edit-content tooltips" data-url="/stations_set/modify?id=<?=$v->id?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/stations_set/delete?id=<?= $v->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif
            ?>
        </tbody>
    </table>
    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            5:{sorter:false}
        }
    });

    function passnews(datatips) {
        var checkVal = [];
        $('input[name="selectchecked"]:checked').each(function() {
            checkVal.push($(this).val());
        });
        if (checkVal.length==0) {
            alert('你还没有选择任何内容！');
            return false;
        }

        var datatips = $(datatips);
        var datatitle = datatips.attr('data-original-title');
        var datamessage = '确定删除所选站点';
        bootbox.dialog({
            message: datamessage,
            title: datatitle,
            buttons: {
                success: {
                    label: "确定",
                    className: "green",
                    callback: function() {
                        var url =datatips.attr('data-url');
                        $.post(url,{id:checkVal}, function(result) {
                           
                            if(result.msg =="success"){
                                
                                location.reload(); 
                            }
                        });
                    }
                },
                danger: {
                    label: "取消",
                    className: "red",
                    callback: function() {
                    }
                }
            }
        });
    }
</script>