<!DOCTYPE html>
<html style="height:100%;">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
	<meta name="viewport" content="initial-scale=1, maximum-scale=3, minimum-scale=1, user-scalable=no">
	<title>摇一摇实时数据</title>


</head>
<body style="margin:0;padding:0;height:100%; text-align: center">
    <table border="1"  align="center"  style="height: 400px;">
        <tr>
            <td>当前选手名：</td>
            <td><?php echo $title;?></td>
        </tr>
        <?php foreach ($items as $key => $value) { ?>
        <tr>
        <td><?php echo $value['title'];?></td>
        <td><?php echo $value['num'];?></td>
        </tr>
        <?php } ?>
        <tr>
            <td>操作：</td>
            <td><a href="/voice/index">刷新</a></td>
        </tr>
        
    </table>
</body>
</html>