<tbody id="sortbody2">
        <?php
			if($featureData->count()) {
			    foreach($featureData as $model) {
			        $featureModel = $model->featuredData;
			        $signalsModel = $model->signals;
			        $model = $model->data;
			        ?>
	        <tr class="sortr-user" draggable="false" featurerel="<?=$featureModel->sort?>" featureModel_id="<?=$featureModel->id?>" f_id="<?=$signalsModel->id?>" s_id="<?=$featureModel->feature_id?>" listtype="feature"  >
	            <td class="checkbox-middle sortr-handle" style="background-color: rgb(255, 189, 32)">
	                <input type="checkbox" class="checkboxes" value="<?= $featureModel->id?>"/>
	            </td>
	            <td style="height: 51px;">
	                <img class="small-img2"
	                    src="<?= $model->thumb? (stripos($model->thumb,'image.xianghunet.com')?$model->thumb:cdn_url('image',$model->thumb)): '/assets/admin/layout/cztv_img/defaultlogo.png'; ?>"/>
	                <a href="javascript:void(0);" class="name-center ellipsis tooltips quick-sidebar-toggler" data-url="<?=Url::get('media_signals/edit',['id'=>$signalsModel->id])?>" 
	               		data-original-title="<?= $model->title;?>" data-trigger="hover"><?= $model->title;?></a>
            	</td>
            	<td><h5><?php switch($signalsModel->live_type) { 
	                			case Signals::LIVE_TYPE_TV: 			echo Signals::LIVE_TYPE_TV_VALUES;break;
	                			case Signals::LIVE_TYPE_BROADCAST: 	echo Signals::LIVE_TYPE_BROADCAST_VALUES;break;
	                			case Signals::LIVE_TYPE_SUPPOSITIONAL:echo Signals::LIVE_TYPE_SUPPOSITIONAL_VALUES;break;
	                			case Signals::LIVE_TYPE_ACTIVITY: 	echo Signals::LIVE_TYPE_ACTIVITY_VALUES;break;
	                			case Signals::LIVE_TYPE_UGC: 			echo Signals::LIVE_TYPE_UGC_VALUES;break;
	                			default:echo"未用"; }?>
	                			</h5>
	           </td>
	           <td style="width: 80px">
	                <span class="states font-red" data-toggle="modal" data-target="#myModal_state<?= $featureModel->id?>">
	                		<?php
		                	switch ($model->status) {
		                		case Signals::LIVE_DATA_STATUS_NO_REVIEWED: echo Signals::LIVE_DATA_STATUS_NO_REVIEWED_VALUES; break;
		                		case Signals::LIVE_DATA_STATUS_FORBIDDEN: echo Signals::LIVE_DATA_STATUS_FORBIDDEN_VALUES; break;
		                		case Signals::LIVE_DATA_STATUS_REVIEWED:
		                		switch($signalsModel->live_status) { 
		                			case Signals::LIVE_STATUS_NOTSTART: 	echo Signals::LIVE_STATUS_NOTSTART_VALUES;break;
		                			case Signals::LIVE_STATUS_FORBIDDEN: 	echo Signals::LIVE_STATUS_FORBIDDEN_VALUES;break;
		                			case Signals::LIVE_STATUS_FINISH: 	echo Signals::LIVE_STATUS_FINISH_VALUES;break;
		                			case Signals::LIVE_STATUS_PLAYING: 	echo Signals::LIVE_STATUS_PLAYING_VALUES;break;
		                			default:echo"未用"; 
		                		}break;
							} ?></span>
	                <div class="modal fade" id="myModal_state<?= $featureModel->id?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel_state" aria-hidden="true">
	                    <div class="modal-dialog">
	                        <div class="modal-content">
	                            <div class="modal-header">
	                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	                                <h4 class="modal-title" id="myModalLabel_state<?= $featureModel->id?>">审核状态</h4>
	                            </div>
	                            <div class="modal-body">
	                                <div class="radio-list radio_model" style="height: 20px">
	                                    <label class="col-md-3" style="text-align: center">
	                                        <input type="radio" name="state<?= $featureModel->id?>" value="<?=Signals::LIVE_DATA_STATUS_NO_REVIEWED?>" 
	                                        <?php if($model->status == Signals::LIVE_DATA_STATUS_NO_REVIEWED) echo'checked';?>/><?=Signals::LIVE_DATA_STATUS_NO_REVIEWED_VALUES?></label>
	                                    <label class="col-md-3" style="text-align: center">
	                                        <input type="radio" name="state<?= $featureModel->id?>" value="<?=Signals::LIVE_DATA_STATUS_REVIEWED?>"
	                                        <?php if($model->status == Signals::LIVE_DATA_STATUS_REVIEWED) echo'checked';?>/><?=Signals::LIVE_DATA_STATUS_REVIEWED_VALUES?></label>
	                                    <label class="col-md-3" style="text-align: center">
	                                        <input type="radio" name="state<?= $featureModel->id?>" value="<?=Signals::LIVE_DATA_STATUS_FORBIDDEN?>"
	                                        <?php if($model->status == Signals::LIVE_DATA_STATUS_FORBIDDEN) echo'checked';?>/><?=Signals::LIVE_DATA_STATUS_FORBIDDEN_VALUES?></label>
	                                </div>
	                            </div>
	                            <div class="modal-footer">
	                                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
	                                <button type="button" class="btn btn-primary determine" data-dismiss="modal">确定</button>
	                                <input type="hidden" name="id_value" value=<?=$model->id?>>
	                            </div>
	                        </div>
	                    </div>
	                </div>
            	</td>
                <td style="width: 155px"><?php echo date('Y-m-d H:i:s',$model->created_at)?></td>
                <td class="operation">
                <div class="btn-group btn-group-xs btn-group-solid">
                	<button type="button" class="btn yellow  tooltips" 
                    		data-url="<?=Url::get('mediasignals/bindingdel',['id'=>$featureModel->id,'sid'=>$signalsModel->id])?>" 
                    		onclick="show_confirm(this)" data-container="body" data-placement="top" 
                    		data-trigger="hover" data-html="true" data-original-title="取消推荐位">
                    		<i class="fa fa-thumbs-down"></i></button>
                	
                </div>
            	</td>
            	
	        </tr>
        <?php }}?>
        </tbody>
