<div class="form-group box-border-right">
    <label class="control-label col-md-2" style="font-size: 15px;font-weight: 800;padding-top: 6px;border-right: 1px solid #efefef">
        付费码率
    </label>
    <div class="col-md-10">
        <div class="col-md-10">
        <?php
        	$signalRates = new SignalRates();
        	$signalRate = $signalRates->getAll();					// 码率
        	if (!empty($signalRate)) {
        	foreach ($signalRate as $k => $v) {
        		$bflag = false;
        		if(isset($news->paylist)) {
	        		$arr = explode(",", $news->paylist);
	        		if(count($arr) > 0) {
		        		foreach ($arr as $val) {
		        			if($v['id'] == $val) {
		        				?><label style="margin-bottom: 0px;margin-right: 10px"><input type="checkbox" name="paylist[]" value="<?= isset($v['id']) ? $v['id'] : 1 ?>" class="form-control" checked/><?= $v['rate_kpbs'].$v['rate_unit'] ?></label><?php 
		        				$bflag = true;
		        				continue;
		        			}
		        		}
	        		}
	        		if($bflag) continue;
	        			?><label style="margin-bottom: 0px;margin-right: 10px"><input type="checkbox" name="paylist[]" value="<?= isset($v['id']) ? $v['id'] : 1 ?>" class="form-control" /><?= $v['rate_kpbs'].$v['rate_unit'] ?></label><?php 
        		} else {
				if($k == 0) { ?>
	        <label style="margin-bottom: 0px;margin-right: 10px"><input type="checkbox" name="paylist[]" value="<?= isset($v['id']) ? $v['id'] : 1 ?>" class="form-control" checked/><?= $v['rate_kpbs'].$v['rate_unit'] ?></label>
	           <?php }else{ ?>
            <label style="margin-bottom: 0px;margin-right: 10px"><input type="checkbox" name="paylist[]" value="<?= isset($v['id']) ? $v['id'] : 1 ?>" class="form-control" /><?= $v['rate_kpbs'].$v['rate_unit'] ?></label>
	    <?php  }  } } } ?>
        </div>
    </div>
</div>