<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['电台列表' => Url::get('stations/index')],
    'add'=> Url::get('stations/create'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th class="">电台名</th>
                <th class="">CODE</th>
                <th class="">电台类型</th>
                <th class="">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value="<?= $v->id ?>"/>
                        </td>
                        <td>
                            <img class="small-img" src="<?php if($v->logo) {echo cdn_url('image',$v->logo);} else{?> /assets/admin/layout/img/sidebar_inline_toggler_icon_blue.jpg <?php } ?>" >
                            <span class="name-center">
                                <?= $v->name ?>
                            </span>
                        </td>
                        <td><?= $v->code ?></td>
                        <td><?= ($v->type==1)?"电视台":"广播台" ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn blue-steel href-location tooltips" data-url="<?= Url::get('stations_epg/index', ['id' => $v->id]) ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="直播流管理"><i class="fa fa-bar-chart-o"></i></button>
                                <button type="button" class="btn yellow href-location tooltips" data-url="<?= Url::get('stations_program/index', ['id' => $v->id]) ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="节目单管理"><i class="fa fa-eye"></i></button>
                                <button type="button" class="btn green edit-content tooltips" data-url="/stations/modify?id=<?=$v->id?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <button type="button" class="btn blue tooltips" onclick="show_confirm(this)"  data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="审查"><i class="fa fa-check-square-o"></i></button>
                                <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/stations/delete?id=<?= $v->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif;
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
<!--                     <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button> -->
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        4:{sorter:false}
    }
});
</script>
