<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a target="mainiframe" href="/admin/index">首页</a>
        </li>

        <li class="page-toolbar">
            <div class="btn-group pull-right">
                <button type="button" class="btn green tooltips screening-btn" data-container="body"
                        data-placement="bottom" data-trigger="hover" data-html="true" data-original-title="筛选"><i
                        class="fa fa-eye"></i></button>
                <button type="button" class="btn purple tooltips trigger-fullscreen" data-container="body"
                        data-placement="bottom" data-trigger="hover" data-html="true" data-original-title="全屏"><i
                        class="fa fa-expand"></i></button>
            </div>
        </li>
    </ul>
</div>
<div class="screening-content">
    <div class="form">
        <form action="<?Url::get('ugc_live_room/detail',array('id'=>$room->id)) ?>" method="get" class="form-horizontal form-bordered form-label-stripped">
            <div class="form-body">
                <div class="form-group">
                    <label class="control-label col-md-2">直播厅名称</label>
                    <div class="col-md-4">
                        <input type="text" value="<?=$room->roomname?>" class="form-control  col-xs-4" placeholder="" readonly>
                    </div>
                    <label class="control-label col-md-2">直播厅编号</label>
                    <div class="col-md-4">
                        <input type="text" value="<?=$room_ext['item_no'] ?>" class="form-control col-xs-4" placeholder="" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">主播</label>
                    <div class="col-md-4">
                        <input type="text" value="<?= $room_ext['anchor_name'] ?>" class="form-control col-xs-4" placeholder="" readonly>
                    </div>
                    <label class="control-label col-md-2">观看人数</label>
                    <div class="col-md-4">
                        <input type="text" value="<?= $room_ext['audience']?>" class="form-control col-xs-4" placeholder="" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">索引图</label>
                    <div class="col-md-4">
                        <img width="100" height="100" src="<?= cdn_url('image','/'.$room->thumb) ?>" />
                    </div>
                    <label class="control-label col-md-2">简介</label>
                    <div class="col-md-4">
                        <textarea class="form-control col-xs-4"><?=trim($room->intro) ?></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">线路</label>
                    <div class="col-md-4">
                        <input type="text" value="<?=$room_ext['line'] ?>" class="form-control col-xs-4" placeholder="" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-4">运行状态</label>
                    <div class="col-md-10">
                        <div class="order-filter">
                            <a href="<?=Url::get('ugc_live_room/detail',array('id'=>$room->id,'runstatus'=>UgcLiveRoom::RUN_STATUS_STOP))?>" <?php if(UgcLiveRoom::RUN_STATUS_STOP == $room->runstatus) {?>class="active"<?php } ?>>关闭</a>
                            <a href="<?=Url::get('ugc_live_room/detail',array('id'=>$room->id,'runstatus'=>UgcLiveRoom::RUN_STATUS_PAUSE))?>" <?php if(UgcLiveRoom::RUN_STATUS_PAUSE == $room->runstatus) {?>class="active"<?php } ?>>暂停</a>
                            <a href="<?=Url::get('ugc_live_room/detail',array('id'=>$room->id,'runstatus'=>UgcLiveRoom::RUN_STATUS_PLAY))?>" <?php if(UgcLiveRoom::RUN_STATUS_PLAY == $room->runstatus) {?>class="active"<?php } ?>>正常</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Begin Qucik Siderbar -->
<div class="page-quick-sidebar-wrapper">
    <div class="page-quick-sidebar-main">
        <button type="button" class="btn red page-quick-sidebar-toggler">关闭</button>
        <iframe id="iframe" src="" width="100%" height="100%" frameborder="0"></iframe>
    </div>
</div>
<!-- End Qucik Siderbar  -->