<div class="form-group box-border-right intro_model" style="background-color:#f9f9f9;">
    <label class="control-label col-md-2" style="font-size: 15px;font-weight: 800;padding-top: 46px">简介</label>
    <div class="col-md-10">
    <textarea placeholder="请填写媒资简介" rows="3" maxlength="200" class="form-control maxlength-handler validate-box" name="intro" id="intro" ><?= Input::fetch('intro');?></textarea>
    </div>
</div>