<table class="table table-striped table-hover table-bordered margin-top-10" id="live_list">
   <div id="guide_live_model" class="col-md-12">
   <?php if(isset($signal->live_type) && $signal->live_type ==6) {
   		if(isset($signalJson)&&!empty($signalJson)) {
		$temp = 0;
		$jsonArr = json_decode($signalJson);
		if(count($jsonArr) > 0) {
			foreach ($jsonArr as $kV => $sV) {
			$temp++;
	?>

    <div class="s_model">
            <div class="col-md-3" style="margin-top: 6px; display:none;">源地址:<span class="add_s">+</span><span class="delete_s">-</span></div>
            <div class="col-md-7" style="margin-top: 5px; display:none;">
            <input class="form-control s_Class" placeholder="rtmp://" value="<?=$sV->sUrl?>" style="padding-right:40px"/>
            <a class="btn red btn-xs openUrl" attr_source_src ="<?=$sV->sUrl?>" onclick="guideHideenUrl(this)">试看</a></div>
            <div class="col-md-2" style="margin-top: 4px;display:none;">
                <select class="form-control sourse_rate" disabled> 
                   <option  value="1">800K</option>
                </select>
            </div>
            <div class="CND_model" style="display: block;margin-top: 5px">
			 <?php 
            	if(count($sV->data) > 0) {
					foreach ($sV->data as $cdnV) {
					
			?>
                <div class="CDN_url">
                        <div class="col-md-3" style="margin-top: 6px;padding-left: 25px">播放地址:</div>
                       
						<div class="col-md-7" style="margin-top: 5px"> <input type="hidden" name="rid" id="rid" value="<?php $data = F::getConfig("ugcLive"); if(isset($data) && array_key_exists("playurl", $data)){ echo($data["playurl"]); }else{ echo"请配置";}?>"/>
						<input class="form-control CDN_Class" Cdn_type="s" placeholder="rtmp://" value="<?php if(isset($data) && array_key_exists("playurl", $data)){ echo($data["playurl"]); }else{ echo"请配置";}?>" style="padding-right:40px" readonly/>
						<a class="btn red btn-xs openUrlLeft" attr_cdn_src="<?php if(isset($signal) && !empty($signal->id)) { echo $signal->id; }?>" onclick="guideSourceUrl(this)">试看</a> 
                        </div>
                        <div class="col-md-2" style="margin-top: 5px">
                            <select class="form-control cdn_rate" disabled>
                                 <option  value="1">800K</option>
                            </select>
                        </div>
						<div class="play_model" style="display: block">
						 <?php 
                         	if(count($cdnV->epgData) > 0) {
								foreach($cdnV->epgData as $epgK => $epgV) {
									$temp++;
								?>
								
                            <div class="play_url">
                                <div class="col-md-3" style="margin-top: 5px;padding-left: 35px">推流地址<span class="add_p" style="display: none">+</span><span class="delete_p" style="display: none">-</span></div>
                              
	                            <div class="col-md-9 model_ir">
	                             <?php
	                             if(!empty($epgV->playurl_data)) {
	                             foreach ($epgV->playurl_data as $playK => $playurl) { 	
                               	?>
	                            	<div class="col-md-12 play_ir" style="padding-left:0px">
	                            	
	                                   <div class="col-md-9" style="margin-top: 5px;padding-left:0px">
	                                   <a class="btn red btn-xs openUrlLeft" attr_src="<?= $playurl->play_url?>" onclick="guidePlayUrlShow(this)">试看</a>
	                                   <input class="form-control play_Class" placeholder="rtmp://" value="<?= $playurl->play_url?>" style="padding-right:40px"/>
	                                   <a class="btn red btn-xs openUrl" attr_src="<?= $playurl->play_url?>" onclick="guidePlayUrl(this)">推送</a>
	                                   <?php if(count($epgV->playurl_data)-1 == $playK) {?>
	                                   <span class="add_ir" style="display: block">
	                                    +
	                                   </span>
	                                   <span class="delete_ir" style="display: block">
	                                    -
	                                   </span>
	                                   <?php } else {?>
	                                   <span class="add_ir" style="display: none">
	                                    +
	                                   </span>
	                                   <span class="delete_ir" style="display: block">
	                                    -
	                                   </span>
	                                  <?php }?>
	                                </div>
	                                <div class="col-md-3" style="margin-top: 5px;padding-left:43px;padding-right:0px">
	                                  <select class="form-control play_rate" disabled>
	                                    <option  value="1">800K</option>
	                                   </select>
	                                </div>
	                              </div>
                                <?php 
                               		}
                                }
                                ?>
 								</div>
                                <div class="col-md-12" style="padding-right: 0px; display:none">
                                    <div class="col-md-12 radio-list" style="margin-top: 5px">
                                        <label class="col-md-2 encrypt_n" style="margin-bottom: 10px">
                                            <input type="radio" name="type_000<?= $temp?>" value="1" <?= !empty($epgV->playurl_data) ? $epgV->isdrm == '1' ? "checked='checked'" : '':'';?>/>不加密</label>
                                        <label class="col-md-2 encrypt_y">
                                            <input type="radio" name="type_000<?= $temp?>" value="2" <?= !empty($epgV->playurl_data) ? $epgV->isdrm == '2' ? "checked='checked'" : '':"checked='checked'";?>/>加密</label>
                                        <div class="col-md-8 drmvalue" style="padding-right: 0px; display: <?= $epgV->isdrm == 1 ? 'none' : 'block';?>" >
                                            <select class="form-control encrypt_select">
                                               <?php
											        $signalDrm = SignalDrm::findAll();						// 密钥
												    if (!empty($signalDrm)) {
												        foreach ($signalDrm as $v) {
											    ?>
                                                 <option value="<?= $v['id'] ?>" <?= !empty($epgV->playurl_data) ?  $epgV->isdrm == '2' && $v['id']== $epgV->drm_id ?'selected="selected"' : "":"";?>><?= $v['drm_name']?></option>
                                                  <?php
												        }
												    }
											    ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12" style="margin-top: 5px; display:none">
                                    <label class="col-md-2" style="padding-top: 5px;text-align: center">类型:</label>
                                    <div class="col-md-4" style="padding-left:0px">
                                        <select class="form-control type_select">
                                            <option></option>
                                            <option <?= $epgV->type == "m3u8" ? 'selected="selected"' : "";?>>m3u8</option>
                                            <option <?= $epgV->type == "rtmp" ? 'selected="selected"' : "";?>>rtmp</option>
                                            <option <?= $epgV->type == "flv" ? 'selected="selected"' : "";?>>flv</option>
                                        </select>
                                    </div>
                                    <label class="col-md-2" style="padding-top: 5px;text-align: center">厂家:</label>
                                    <div class="col-md-4" style="padding-right: 0px">
                                        <select class="form-control vendor_select">
                                          <option  value="1">"云帆"</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12" style="margin-top: 5px;display:none">
								 <label class="col-md-2" style="padding-top: 5px;text-align: center">默认码率</label>
								    <div class="col-md-4" style="padding-left:0px">
								        <select class="form-control default_rate">
								          <option  value="1">800K</option>
								        </select>
								    </div>
								</div>
                                <div class="col-md-12" style="margin-top: 10px; display:none"><textarea class="t_area form-control" style="height: 100px" placeholder="备注..." ><?=isset($epgV->remarks) ? $epgV->remarks :""; ?></textarea></div>
                            </div>
							<?php
									}
								}
							?>
                        </div>
                    </div>
					<?php 
							}
						}
					?>
            </div>
    </div>

	<?php	
				} 
			}
		}
   }
   else {
   ?>
   <div class="s_model">
			<div class="col-md-3" style="margin-top: 6px; display:none;">源地址:<span class="add_s">+</span><span class="delete_s">-</span></div>
			<div class="col-md-7" style="margin-top: 5px; display:none;">
			<input class="form-control s_Class" placeholder="rtmp://" value="rtmp://test/ugc_guide.com" style="padding-right:40px"/>
			<a class="btn red btn-xs openUrl" attr_source_src="rtmp://test/ugc_guide.com" onclick="guideHideenUrl(this)">试看</a>
			</div>
			<div class="col-md-2" style="margin-top: 4px; display:none;">
				<select class="form-control sourse_rate">
					<option  value="1">800K</option>
				</select>
			</div>
			<div class="CND_model" style="display: block;margin-top: 5px">
				<div class="CDN_url">
						<div class="col-md-3" style="margin-top: 6px;padding-left: 25px">播放地址:<span class="add_C" style="display: none">+</span><span class="delete_C" style="display: none">-</span></div>
						
						<div class="col-md-7" style="margin-top: 5px">
						<input class="form-control CDN_Class" Cdn_type="s" placeholder="rtmp://" style="padding-right:40px" value="<?php $data = F::getConfig("ugcLive"); if(isset($data) && array_key_exists("playurl", $data)){ echo($data["playurl"]); }else{ echo"请配置";}?>" readonly/>
						
						</div>
						<div class="col-md-2" style="margin-top: 5px">
						    <select class="form-control cdn_rate" disabled>
						   		<option  value="1">800K</option>
						    </select>
						</div>
						<div class="play_model" style="display: block">
							<div class="play_url">
								<div class="col-md-3" style="margin-top: 5px;padding-left: 35px">推流地址<span class="add_p" style="display: none">+</span><span class="delete_p" style="display: none">-</span></div>
								<div class="col-md-9 model_ir">
									<div class="col-md-12 play_ir" style="padding-left:0px">
										<div class="col-md-9" style="margin-top: 5px;padding-left:0px">
											 <a class="btn red btn-xs openUrl" attr_src onclick="guidePlayUrl(this)">试看</a> 
										</div>
										
										<div class="col-md-9" style="margin-top: 5px;padding-left:0px">
		                                  
		                                   <input class="form-control play_Class" placeholder="rtmp://" style="padding-right:40px"/>
		                                   <a class="btn red btn-xs openUrl" attr_src onclick="guidePlayUrl(this)">推送</a>
		                                   <a class="btn red btn-xs openUrlLeft" attr_src onclick="guidePlayUrlShow(this)">试看</a>
		                                   <span class="add_ir" >
		                                    +
		                                   </span>
		                                   <span class="delete_ir">
		                                    -
		                                   </span>
		                                </div>
										<div class="col-md-3" style="margin-top: 5px;padding-left:43px;padding-right:0px">
										    <select class="form-control play_rate" disabled>
												<option  value="1">800K</option>
											</select>
										</div>
									</div>
								</div>
								
								<div class="col-md-12" style="padding-right: 0px; display: none;">
									<div class="col-md-12 radio-list" style="margin-top: 5px">
										<label class="col-md-2 encrypt_n" style="margin-bottom: 10px">
											<input type="radio" name="type_000" value="1" checked />不加密</label>
										<label class="col-md-2 encrypt_y">
											<input type="radio" name="type_000" value="2" />加密</label>
											<div class="col-md-8" style="padding-right: 0px">
												<select class="form-control encrypt_select">
													<?= $this->partial('partials/widget/live_tv_drm'); ?>
												</select>
											</div>
									</div>
								</div>
								<div class="col-md-12" style="margin-top: 5px; display: none;">
									<label class="col-md-2" style="padding-top: 5px;text-align: center">类型:</label>
									<div class="col-md-4" style="padding-left:0px">
										<select class="form-control type_select">
											<option selected="selected">m3u8</option>
											<option>rtmp</option>
											<option>flv</option>
										</select>
									</div>
									<label class="col-md-2" style="padding-top: 5px;text-align: center">厂家:</label>
									<div class="col-md-4" style="padding-right: 0px">
										<select class="form-control vendor_select">
											<option  value="1">"云帆"</option>
										</select>
									</div>	
								</div>
								<div class="col-md-12" style="margin-top: 5px; display: none;">
								 <label class="col-md-2" style="padding-top: 5px;text-align: center">默认码率</label>
								    <div class="col-md-4" style="padding-left:0px">
								        <select class="form-control default_rate">
								           <option  value="1">800K</option>
								        </select>
								    </div>
								</div>
								<div class="col-md-12" style="margin-top: 10px; display: none;"><textarea class="t_area form-control" style="height: 100px" placeholder="备注..."></textarea></div>
							</div>
						</div>
					</div>
			</div>
		</div>
   <?php }?>
   </div>
</table>

<script type="text/javascript">

(function(){
	$(".play_Class").change(function(){
	       var val=$(this).val();
	       $(this).next().attr("attr_src",val);
	       $(this).next().next().attr("attr_src",val);
	    });
	$(".CDN_Class").change(function(){
	       var val=$(this).val();
	       $(this).next().attr("attr_cdn_src",val);
	    });
})();


$("#guide_live_model").on("click", ".add_ir", function () {
    var ir_index=$(this).parents(".play_ir").index();
    $(this).hide();
    if (ir_index >= 9) {
        alert("最多添加10条！");
    } else {
        $(this).parents(".model_ir").append(
            '<div class="col-md-12 play_ir" style="padding-left:0px">'+
                '<div class="col-md-9" style="margin-top: 5px;padding-left:0px">'+
                '<input class="form-control play_Class" placeholder="rtmp://" style="padding-right:40px"/>'+
                '<a class="btn red btn-xs openUrl" attr_src onclick="guidePlayUrl(this)">推送</a>'+
                '<a class="btn red btn-xs openUrlLeft" attr_src onclick="guidePlayUrlShow(this)">试看</a>'+
                '<span class="add_ir">+</span>'+
                '<span class="delete_ir">-</span>'+
                '</div>'+
                '<div class="col-md-3" style="margin-top: 5px;padding-left:43px;padding-right:0px">'+
                '<select class="form-control play_rate" disabled>'+
                '<option  value="1">800K</option>'+
                '</select>'+
                '</div>'+
            '</div>'
        );
    }
    Metronic.init();
    $(".play_Class").change(function(){
	       var val=$(this).val();
	       $(this).next().attr("attr_src",val);
	       $(this).next().next().attr("attr_src",val);
	    });
});//增加

$("#guide_live_model").on("click", ".delete_ir", function () {
    var ir = new Array();
    $(this).parents(".model_ir").children(".play_ir").each(function () {
        var ir3 = $(this).index();
        ir.push(ir3);
    });
    var ind_ir = ir.length;
    if (ind_ir == 1){
        alert("无法删除最后一项！");
    } else {
        $(this).parent().parent().remove();
        delete_irmodel();
    }
});//ir删除


function replaceUrl(url) {
	var sr = "rtmp://yf.push.cztv.com";
	if(url.indexOf("yf.push.cztv.com") > 0) {
		var reg = url.substr(sr.length,url.length);
		url = "rtmp://yf.ugcrtmp.l.cztv.com" + reg;
	}
	return url;
}

function guideHideenUrl(obj){
    var url=$(obj).attr("attr_source_src");
	winModalLimitScreen('/signals/player?url='+url);
}

function guideSourceUrl(obj) {
	var url=$(obj).attr("attr_cdn_src");
	url = replaceUrl(url);
	winModalLimitScreen('/signals/guideplayer?id='+url);
    //winModalLimitScreen('/signals/liveguide?id='+url);
}

function guidePlayUrlShow(obj) {
	var url=$(obj).attr("attr_src");
	// url = replaceUrl(url);
	winModalLimitScreen('/signals/player?url='+url);
}

function guidePlayUrl(obj) {
	var url=$(obj).attr("attr_src");
	var res = sendUrl(url);
}

function sendUrl(url) {
	$.post("/media_signals/sendYL",{url:url, id:<?=$signal->id; ?>},function(result) {
		if(result.msg =="error"){
             alert('发送失败');
             return false;
         }else{
        	 alert("发送成功");
        	 return true;
         }
	});
	
}

</script>