<script src="/assets/global/plugins/jquery.blockui.min.js"></script>
<script>

//todo filesize  文件大小
    //阿里云oss上传
    oss_accessid = ''
    oss_accessoss_key = ''
    oss_host = ''
    oss_policyBase64 = ''
    oss_signature = ''
    oss_callbackbody = ''
    oss_filename = ''
    oss_key = ''
    oss_expire = 0
    g_object_name = ''
    g_object_name_type = 'local_name'
    OSS_FILE_NAME_TYPE_LOCAL = "local_name"
    OSS_FILE_NAME_TYPE_RANDOM = "random_name"

    oss_now = oss_timestamp = Date.parse(new Date()) / 1000;
    policyUrl = "<?php $config=F::getConfig('domain_config'); echo $config["interaction"]."osspolicy/".$ossAction ?>";

    function send_request() {
        var xmlhttp = null;
        if (window.XMLHttpRequest) {
            xmlhttp = new XMLHttpRequest();
        }
        else if (window.ActiveXObject) {
            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        }

        if (xmlhttp != null) {

            xmlhttp.open("GET", policyUrl, false);
            xmlhttp.send(null);
            return xmlhttp.responseText
        }
        else {
            alert("Your browser does not support XMLHTTP.");
        }
    }
    ;



    function get_oss_signature() {
        //可以判断当前oss_expire是否超过了当前时间,如果超过了当前时间,就重新取一下.3s 做为缓冲
        oss_now = oss_timestamp = Date.parse(new Date()) / 1000;
        if (oss_expire < oss_now + 3) {
            body = send_request()
            var obj = eval("(" + body + ")");
            oss_host = obj['host']
            oss_policyBase64 = obj['policy']
            oss_accessid = obj['accessid']
            oss_signature = obj['signature']
            oss_expire = parseInt(obj['expire'])
            oss_callbackbody = obj['callback']
            oss_key = obj['dir']

        }

    }


    function random_string(len) {
        len = len || 32;
        var chars = 'ABCDEFGHJKMNPQRSTWXYZabcdefhijkmnprstwxyz2345678';
        var maxPos = chars.length;
        var filename = '';
        for (i = 0; i < len; i++) {
            filename += chars.charAt(Math.floor(Math.random() * maxPos));
        }
        return filename;
    }

    function get_suffix(filename) {
        pos = filename.lastIndexOf('.')
        suffix = ''
        if (pos != -1) {
            suffix = filename.substring(pos)
        }
        return suffix;
    }

    function calculate_object_name(filename) {
        if (g_object_name_type == 'local_name') {
            g_object_name = oss_key + "${filename}"
        }
        else if (g_object_name_type == 'random_name') {
            suffix = get_suffix(filename)
            g_object_name = oss_key + random_string(10) + suffix
        }
        return ''
    }


    function set_upload_param(filename) {

        get_oss_signature()
        if (filename != '') {

            calculate_object_name(filename);
            var res = {
                'key': g_object_name,
                'policy': oss_policyBase64,
                'OSSAccessKeyId': oss_accessid,
                'success_action_status': '200', //让服务端返回200,不然，默认会返回204
//                'callback': oss_callbackbody,
                'signature': oss_signature,
            };

            return res;
        }

        return false;

    }

    function appendObjectToFrom(form_data,item) {
        for ( var key in item ) {
            form_data.append(key, item[key]);
        }
    }

function OssUpload( file,fileNameType,callBack) {
        g_object_name_type = fileNameType;
        var param = set_upload_param(file.name);
        var form_data = new FormData();

        appendObjectToFrom(form_data,param);
        form_data.append("file",file);
        var fileFullName = oss_host+param["key"];
        $.blockUI({ message: '<h2><img src="/assets/admin/layout/img/loading_mask.gif" /> 提交中...</h2>' });
        $.ajax({
            url: oss_host,
            data: form_data,
            processData: false,
            cache: false,
            async: false,
            type:'POST',
            contentType: false,//这个就是了
            success: function (data, textStatus, request) {
                $.unblockUI();
                //textStatus === "success" 表示成功
                if(typeof callBack === "function") {
                    callBack(fileFullName,param["policy"],textStatus);
                }

            },
            error : function(responseStr) {
                $.unblockUI();
                if(typeof callBack === "function") {
                    callBack(fileFullName,param["policy"],responseStr.responseText);
                }
            }
        });
    }

</script>