<div class="form-group box-border-top box-border-right" style="background-color:#f9f9f9;">
    <label class="control-label col-md-2" style="font-size: 15px;font-weight: 800;padding-top: 14px">
        <span class="btn btn-xs blue content_toggle">
            <i class="fa fa-upload tooltips" style="padding-top:2px;" data-trigger="hover" data-original-title="展开"></i>
            <i class="fa fa-download tooltips" style="display:none;padding-top:3px;" data-trigger="hover" data-original-title="收起"></i>
        </span>
        标题
        <span class="font-red mustadd" style="font-size: 13px;">*必填</span>
    </label>
    <div class="col-md-10">
        <div class="form-group form-md-line-input has-info"
             style="border-bottom: 1px solid rgba(204,204,204,0.53);padding-top: 0px">
            <input type="text" class="form-control maxlength-handler valid heading"
                   id="title" name="title" maxlength="80" placeholder="请填写媒资标题" value="<?= Input::fetch('title');?>">
            <label for="form_control_1" style="left: 0px;color:rgba(4, 56, 138, 0.68);width: 100%;font-size: 15px;top:-10px;font-weight: 600"></label>
        </div>
    </div>
</div>
<div class="form-group box-border-right subtitle" <?php if(!Input::fetch('sub_title')): ?><?php endif; ?>>
    <label class="control-label col-md-2"
           style="font-size: 15px;font-weight: 800;padding-top: 14px">副标题</label>
    <div class="col-md-10">
        <div class="form-group form-md-line-input has-info"
             style="border-bottom: 1px solid rgba(204,204,204,0.53);padding-top: 0px;">
            <input type="text" id="sub_title"  name="sub_title" value="<?= Input::fetch('sub_title');?>" class="form-control maxlength-handler valid"   placeholder="请填写副标题" maxlength="80" style="font-size: 14px;border: none;">
            <label for="form_control_1" style="left: 0px;color:rgba(4, 56, 138, 0.68);width: 100%;font-size: 15px;top:-10px;font-weight: 600"></label>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(".content_toggle").toggle(
       function(){
          $(this).children('i').eq(0).hide();
          $(this).children('i').eq(1).show();
          $(".depart_model,.flink_model,.sourse_model,.intro_model,.subtitle,.keywords_model").show();
       },
       function(){
          $(this).children('i').eq(1).hide();
          $(this).children('i').eq(0).show();
          $(".depart_model,.flink_model,.sourse_model,.intro_model,.subtitle,.keywords_model").hide();
       }
    );
</script>
