<div class="form-group box-border-right box-border-top" style="margin-top: 10px">
    <label class="control-label col-md-12" style="text-align: left;font-size: 15px;font-weight: 800;background-color: rgba(230, 230, 230, 0.57);padding: 5px;">水印样式</label>
    <div class="col-md-12">
        <div>
            <select class="form-control select_selectsplitter" size="4">
                <optgroup label="无水印"></optgroup>
                <optgroup label="蓝色水印">
                    <option value="blue_mm">中间</option>
                    <option value="blue_lt">左上</option>
                    <option value="blue_lm">左中</option>
                    <option value="blue_lb">左下</option>
                    <option value="blue_rt">右上</option>
                    <option value="blue_rm">右中</option>
                    <option value="blue_rb">右下</option>
                    <option value="blue_mt">中上</option>
                    <option value="blue_mb">中下</option>
                </optgroup>
                <optgroup label="透明水印">
                    <option value="mm">中间</option>
                    <option value="lt">左上</option>
                    <option value="lm">左中</option>
                    <option value="lb">左下</option>
                    <option value="rt">右上</option>
                    <option value="rm">右中</option>
                    <option value="rb">右下</option>
                    <option value="mt">中上</option>
                    <option value="mb">中下</option>
                </optgroup>
            </select>
        </div>
    </div>
</div>