<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form class="form-horizontal form-bordered form-label-stripped" id="form-blockvalues" enctype="multipart/form-data" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加区块值  </span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>
            
            <div class="form-group">
                <label class="control-label col-md-2">名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" placeholder="名称" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group" id="advert-style">
                <label class="control-label col-md-2">区块值</label>

                <div class="col-md-10">
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div class="fileinput-new thumbnail" style="width:120px; height:120px;">
                                <img alt="" src=""/>
                            </div>
                            <div class="fileinput-preview fileinput-exists thumbnail" style="max-width:120px; max-height:120px;"></div>
                            <div>
                                <span class="btn blue btn-file">
                                    <span class="fileinput-new">选择图片</span>
                                    <span class="fileinput-exists">更换图片</span>
                                    <input type="file" name="imageurl-0" id="imageurl-0">
                                </span>
                                <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput">删除图片</a>
                            </div>
                        </div>
                        <div class="clearfix margin-top-10">
                            <span class="label label-danger">提示</span> 支持gif、jpg、png格式，图片大小<2M
                        </div>
                </div>
                    <div class="col-md-10 col-md-offset-2 col-md-adjust">
                        <input name="block_title-0" type="text" maxlength="50" placeholder="标题" value="" class="form-control input-large maxlength-handler validate-box"/>
                    </div>
                    <div class="col-md-10 col-md-offset-2 col-md-adjust">
                        <input name="block_link-0" type="text" maxlength="50" placeholder="链接地址" value="" class="form-control input-large maxlength-handler validate-box default-http"/>
                    </div>
                    <div class="col-md-10 col-md-offset-2 col-md-adjust">
                        <input name="block_desc-0" type="text" maxlength="20" placeholder="描述" value="" class="form-control input-large maxlength-handler validate-box"/>
                    </div>
            </div>
            <div class="text-center" id="add_style">
                <button type="button" class="btn blue add-style"><i class="fa fa-plus"></i> 添加区块值</button>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">
    // form stations
    $('#form-blockvalues').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required : true
            }
        },

        messages: {
            name: {
                required : '名称不能为空'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });

$(function() {
    var num = 1;
    $('.add-style').click(function() {
        if(num >= 20){
            alert('新增样式数量超过上限');
            return false;
        }
        else{
        $("#advert-style").find("label").siblings("div:last").after("<div class=\"col-md-10 col-md-offset-2 border-division\">" +
            "<span class=\"pull-right\"><button type=\"button\" class=\"btn red remove-style-"+num+"\"><i class=\"fa fa-trash-o\"></i> 删除</button></span>" +
            
                "<div class=\"fileinput fileinput-new\" data-provides=\"fileinput\">" +
                    "<div class=\"fileinput-new thumbnail\" style=\"width:120px; height:120px;\">" +
                        "<img alt=\"\" src=\"\"/>" +
                    "</div>" +
                    "<div class=\"fileinput-preview fileinput-exists thumbnail\" style=\"max-width:120px; max-height:120px;\">" + "</div>" +
                    "<div>" +
                        "<span class=\"btn blue btn-file\">" +
                            "<span class=\"fileinput-new\">选择图片</span>" +
                            "<span class=\"fileinput-exists\">更换图片</span>" +
                            "<input type=\"file\" name=\"imageurl-"+num+"\" id=\"imageurl-"+num+"\" multiple=\"multiple\" accept=\"image/*\" >" +
                        "</span>" +
                        "<a href=\"javascript:;\" class=\"btn red fileinput-exists\" data-dismiss=\"fileinput\">删除图片</a>" +
                    "</div>" +
                "</div>" +
                "<div class=\"clearfix margin-top-10\">" +
                    "<span class=\"label label-danger\">提示</span> 支持gif、jpg、png格式，图片大小<2M" +
                "</div>" +
           
            "</div>" +
                "<div class=\"col-md-10 col-md-offset-2 col-md-adjust\">" +
                    "<input name=\"block_title-"+num+"\" type=\"text\" maxlength=\"20\" placeholder=\"标题\" value=\"\" class=\"form-control input-large maxlength-handler validate-box\"/>" +
                "</div>" +
            
                "<div class=\"col-md-10 col-md-offset-2 col-md-adjust\">" +
                    "<input name=\"block_link-"+num+"\" type=\"text\" maxlength=\"50\" placeholder=\"链接地址\" value=\"\" class=\"form-control input-large maxlength-handler validate-box default-http\"/>" +
                "</div>" +
                "<div class=\"col-md-10 col-md-offset-2 col-md-adjust\">" +
                    "<input name=\"block_desc-"+num+"\" type=\"text\" maxlength=\"20\" placeholder=\"描述\" value=\"\" class=\"form-control input-large maxlength-handler validate-box\"/>" +
                "</div>" +
            
            "<script type=\"text/javascript\">" +
                "$('.maxlength-handler').maxlength({" +
                "limitReachedClass:\"label label-danger\"," +
                "alwaysShow:true," +
                "threshold:5" +
                "});" +
            "<\/script>"
        );
        $(function() {
            $("#advert-style").find(".default-http").focus(function() {
                if($(this).val() == "") {
                    $(this).val("http://");
                }
            });
        });
        $(".remove-style-"+num).click(function() {
            $(this).parent().parent().next().remove();
            $(this).parent().parent().next().remove();
            $(this).parent().parent().remove();
            num--;
        });
        num++;
        }

    });

});
</script>