<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['工资薪金邮件通知' => Url::get('salary_bill/index',array('id'=>Request::get('id')))],    
    'html' => '',
    'salaryexcel' =>'salary_bill/salaryimport'
]);
?>
<?php $this->partial('partials/error_messages'); ?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>员工编号</th>
                <th>名称</th>
                <th>Email</th>
                <th>发送状态</th>
                <?php
                foreach($salary_bill_list as $v) {
                    foreach( $v as $key=>$column) {
                        if($column===true) continue;
                        if (in_array($column, ['基本工资', '岗位津贴', '通讯补贴', '补发', '工资小计', '奖金', '当月奖罚', '应发合计', '公积金', '养老', '医疗', '门诊', '失业', '工会', '个税', '实发'])) {
                        ?>
                        <th><?php echo $column ?></th>
                        <?php
                        }
                    }
                    break;
                }
                ?>
            </tr>
        </thead>
        <tbody>
          <?php
              foreach($salary_bill_list as $v) {
          ?>
            <tr>
                <td class="checkbox-middle">
                    <input name="selectchecked" type="checkbox" class="checkboxes" value="<?=$v[0]?>"/>
                </td>
                <td><?php echo $v[0] ?></td>
                <td><?php echo $v[2] ?></td>
                <td><?php echo $v[1] ?></td>
                <td><?php echo ($v['status'])?"<font color='green'>发送成功</font>":"" ?></td>
                <?php
                    foreach($v as $key=>$column) {
                        if($column===true) continue;
                        if(in_array($column, ['基本工资', '岗位津贴', '通讯补贴', '补发', '工资小计', '奖金', '当月奖罚', '应发合计', '公积金', '养老', '医疗', '门诊', '失业', '工会', '个税', '实发'])) {
                            ?>
                            <td><?php echo $v[$key+1] ?></td>
                        <?php
                        }
                    }
                ?>
            </tr>
          <?php
              }
          ?>
        </tbody>
    </table>
    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default tooltips" data-url="<?= Url::get('salary_bill/sendSalary'); ?>" onclick="passnews(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="批量发送">批量发送</button>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="modal fade" id="importexcelForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabe2">上传工资单</h4>
            </div>
            <form id= "uploadForm">
                <div class="modal-body row">

                    <p> <label class="control-label col-md-3">上传工资单</label>
                        <input id="importexcelfile" type="file" multiple="multiple" name="file" />
                    </p>

                    <p><label class="control-label col-md-3">工资单格式:</label>
                    <div>(只支持csv格式，编码为GBK，模板下载<a href="http://ohudong.cztv.com/document/cztv_salary_bill.csv" target="_blank">新蓝网工资单模板</a>)</div>
                    </p>

                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn blue" data-dismiss="modal" style="width: auto">关闭</button>
                <button type="button" class="btn red"  style="width: auto" onclick="importsalary()">确定</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            1:{sorter:false},
            3:{sorter:false},
            4:{sorter:false}
        }
    });

    function passnews(datatips){
        var checkVal = [];
        $('input[name="selectchecked"]:checked').each(function(){
            checkVal.push($(this).val());
        });
        if (checkVal.length==0){
            alert('你还没有选择任何员工！');
            return false;
        }
        var datatips = $(datatips);
        var datatitle = datatips.attr('data-original-title');
        var datamessage = '确定发邮件给所选员工';
        bootbox.dialog({
            message: datamessage,
            title: datatitle,
            buttons: {
                success: {
                    label: "确定",
                    className: "green",
                    callback: function() {
                        var url =datatips.attr('data-url');
                        $.post(url,{id:checkVal}, function(result){
                            location.reload();
                        });
                    }
                },
                danger: {
                    label: "取消",
                    className: "red",
                    callback: function() {

                    }
                }
            }
        });
    }

    function importsalary() {
        var formData = new FormData($("#uploadForm")[0]);
        $.ajax({
            url: '/salary_bill/salaryimport' ,
            type: 'POST',
            data: formData,
            dataType: 'json',
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            success: function (data) {
                if (data.code == 200) {
                    window.location.reload();
                } else {
                    alert(data.msg);
                }
            },
            error: function (returndata) {
                alert("请求失败");
            }
        });
    }
</script>