ALTER TABLE `users` CHANGE `qq` `qq` VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'QQ信息';
ALTER TABLE `users` CHANGE `gender` `gender` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '性别 0：未知，1：男 2：女';
ALTER TABLE `users` CHANGE `avatar` `avatar` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用户头像';
UPDATE users SET `grade`=0
ALTER TABLE `users` CHANGE `grade` `grade` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT '会员等级';