<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['视频列表' => Url::get('media_videos/index')],
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>标题</th>
                <th>简介</th>
                <th>分类</th>
                <th>播出时间</th>
                <th>作者</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($parcel->models as $model):
            $cat = $model->privateCategory;
            $catestr = "";
            $fatherlen = count($cat->getParents());
            
            if($fatherlen>3) {
                $arr = $cat->getParents();
                for($i=$fatherlen-3; $i<$fatherlen; $i++) {
                    $catestr .= (""!=$catestr)?"/".$arr[$i]->name:$arr[$i]->name;
                }
            }
            else {
                foreach($cat->getParents() as $cc) {
                    $catestr .= (""!=$catestr)?"/".$cc->name:$cc->name;
                }
            }
            $model = $model->data; ?>
            <tr>
                <td class="checkbox-middle">
                    <input type="checkbox" class="checkboxes" value="<?= $model->id?>"/>
                </td>
                <td>
                    <img class="small-img" src="<?php if($model->thumb) {echo (stripos($model->thumb,'image.xianghunet.com')?$model->thumb:cdn_url('image',$model->thumb));} else{?> /assets/admin/layout/img/sidebar_inline_toggler_icon_blue.jpg <?php } ?>"/>
                    <span class="name-center">
                        <?= $model->title;?>
                    </span>
                </td>
                <td class="maxtabletd"><?= $model->intro;?></td>
                <td><?=$catestr?></td>
                <td><?= $model->updated_at?date('Y-m-d H:i:s', $model->updated_at):'';?></td>
                <td><?= $model->author_name;?></td>
                <td>
                    <div class="btn-group btn-group-xs btn-group-solid">
                    	<button type="button" class="btn green edit-content tooltips" data-url="<?= Url::get('media_videos/edit', ['id' => $model->source_id],['',]); ;?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                        <?php if($checkAuth('media_posts/publish')){ ?>
                            <button type="button" class="btn green-jungle edit-content tooltips"
                                    data-url="<?= Url::get('media_posts/publish', ['id' => $model->id]); ?>"
                                    data-container="body" data-placement="top" data-trigger="hover" data-html="true"
                                    data-original-title="<?= $model->status == 1 ? '修改发布栏目': ($model->status == 9 ? '修改发布栏目' : '发布') ?>"><i class="fa <?= $model->status == 1 ? 'fa-pencil': ($model->status == 9 ? 'fa-pencil' : 'fa-send') ?>"></i></button>
                        <?php }?>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        <?php if(count($parcel->models) == 0) { ?>
            <tr class="sortable-tr"><td colspan="11">未能找到相关数据</td></tr>
        <?php } ?>
        <?php ?>
        </tbody>
    </table>
    <div class="paginationnav">
        <div class="paginationnav-main">
            <?= $parcel->pagination->render(); ?>
            <div class="pagination-info">总计 <?= $parcel->count ?> 条</div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        1:{sorter:false},
        2:{sorter:false},
        5:{sorter:false}
    }
});
</script>