<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped"  enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加热词</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>
        <div class="form-body">

            <div class="form-group">
                <label class="control-label col-md-2">关键词 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="name" placeholder="关键词" maxlength="50" class="form-control input-large maxlength-handler"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">权重 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="weight" placeholder="权重" maxlength="50" class="form-control input-large maxlength-handler"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">状态 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label>
                            <input type="radio" class="icheck" name="status" value="0"/>
                            不显示</label>
                        <label>
                            <input type="radio" class="icheck" name="status" value="1" />
                            显示</label>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>