<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['热词列表' => Url::get('hotwords/index')],
    'add'=> Url::get('hotwords/add'),
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>关键词</th>
            <th>用户ID</th>
            <th>用户名</th>
            <th>创建时间</th>
            <th>权重</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($models = $data->models)) :
            foreach ($models as $v) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td><?= $v->name ?></td>
                    <td><?= $v->user_id ?></td>
                    <td><?= $v->user_name ?></td>
                    <td><?php echo date("Y-m-d H:i:s", $v->createtime) ?></td>
                    <td><?= $v->weight ?></td>
                    <td><?php if($v->status == '1') {
                            echo '显示';
                        }
                        else {
                            echo '不显示';
                        }
                        ?></td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn green edit-content" value="/hotwords/upd/<?= $v->id ?>">编</button>
                            <a type="button" href="/hotwords/del/<?= $v->id ?>" data-toggle="modal" class="btn red">删</a>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $data->pagination->render() ;?>
            <div class="pagination-info"><?=Lang::_('total')."： ".$data->count?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        7:{sorter:false}
    }
});
</script>