<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
<meta content="yes" name="apple-mobile-web-app-capable" />
<meta content="black" name="apple-mobile-web-app-status-bar-style" />
<meta content="telephone=no" name="format-detection" />
<title>UGC</title>

</head>
<body>
	<div>
		<video src='http://yfhls.l.cztv.com/live/129_1535/online.m3u8' controls  webkit-playsinline="true" x-webkit-airplay="true"></video>
	</div>
</body>
</html>