<div class="page-content-wrapper">
    <div class="page-content">

        <div class="col-md-12 page-404">
            <div class="number">
                404
            </div>
            <div class="details">
                <h3>噢! 您访问的页面出了点小问题.</h3>
                <p>
                    服务器暂时没有找到你刚刚需要的页面.<br>
                    <a href="javascript:window.history.go(-1)">返回上一页</a>
                    或者你可以试试其他的页面.
                </p>

            </div>
        </div>

    </div>
</div>