<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['专题列表' => Url::get('/specials/index'),'专题模板列表' => Url::get('special_templates')],
    'add'=> Url::get('special_templates/create'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th class="">模板名</th>
                <th class="">字段集</th>
                <th class="">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value="1"/>
                        </td>
                        <td>
                            <span class="name-center">
                                <?= $v->name ?>
                            </span>
                        </td>
                        <td><?= $v->fields ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <?php if($checkAuth('special_templates/modify')){ ?>
                                <button type="button" class="btn green edit-content tooltips" data-url="/special_templates/modify?id=<?=$v->id?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <?php }?>
                            <!--  <?php if($checkAuth('special_templates/delete')){ ?>
                                <button type="button" class="btn blue check-content tooltips" onclick="show_confirm(this)" data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="审查"><i class="fa fa-check"></i></button>
                                <?php }?>  -->
                                <?php if($checkAuth('special_templates/delete')){ ?>
                                <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/special_templates/delete?id=<?= $v->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                                <?php }?>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif;
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            3:{sorter:false}
        }
    });
</script>
