<div class="screening-content">
    <div class="form">
        <form action="/baoliao/index" method="get" class="form-horizontal form-bordered form-label-stripped">
            <div class="form-body">
                <div class="form-group">
                    <label class="control-label col-md-2">搜索</label>
                    <div class="col-md-4">
                        <input type="text" name="content" class="form-control input-medium" placeholder="">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>