<?php
View::setVar('action', '新增模板');
Input::init(Request::getPost(), $model);
?>

<script src="/assets/global/plugins/jstree/dist/jstree.min-3.js"></script>
<div class="form page-quick-sidebar-form">
    <form class="form-horizontal form-bordered form-label-stripped form-tpl" id="form-tpl" method="post" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>配置模板&nbsp;<?= Input::fetch('name') ?></span>
            <div class="btn-group">
                <button type="submit" class="btn blue" onclick="javascript:import_quote(this);"><i class="fa fa-check"></i> 提交</button>
            
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>

            <div class="form-group">
                <label class="control-label col-md-2">所属域名</label>
                <div class="col-md-10">
                    <select name="domain_id" id="domain_id" class="form-control input-large validate-box select2_category" data-placeholder="请选择" >
                        <?php
                            foreach($domains as $domain) {
                        ?>
                        <option value="<?php echo $domain['id']?>" <?php if($domain_id==$domain['id']) {?>selected="selected" <?php } ?>><?php echo $domain['name']?></option>
                        <?php
                            }
                        ?>
                    </select>
                    <span id="Warning" name="Warning" class="font-red"></span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">类型</label>
                <div class="col-md-10">
                    <select name="topicfile" id="topicfile" class="form-control input-large validate-box select2_category" data-placeholder="请选择" >
                        <option value="tpl" >tpl</option>
                        <option value="css" >css</option>
                        <option value="js" >js</option>
                        <option value="images" >images</option>
                        <option value="vr" >vr</option>
                    </select>
                    <span id="Warning" name="Warning" class="font-red"></span>
                </div>
            </div>

            <!-- </form>

             <form id="fileupload" action="/tpl/attachupload" method="POST" enctype="multipart/form-data" class="form-horizontal form-bordered form-label-stripped fileupload-form">
              The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->



            <div class="form-group">
                <label class="control-label col-md-2">文件</label>
                <div class="col-md-10">
                    <div class="row fileupload-buttonbar">
                        <div class="col-md-7">
                            <!-- The fileinput-button span is used to style the file input field as button -->
                            <span class="btn green multipleupload">
                                <input type="file" name="files[]" id="upload_image" multiple="multiple" accept="tpl" onchange="handleFile(this)">
                                <i class="fa fa-plus"></i>
                                <span>添加文件...</span>
                            </span>
                            <!--
                            <span class="btn green fileinput-button">
                                <i class="fa fa-plus"></i>
                                <span>
                                    添加文件...
                                </span>
                                <input type="file" name="files[]" multiple="" onchange="handleFile(this)">
                            </span>
                            <button type="submit" class="btn blue start">
                                <i class="fa fa-upload"></i>
                                <span>
                                    开始上传
                                </span>
                            </button>
                            <button type="button" class="btn red delete">
                                <i class="fa fa-trash"></i>
                                <span>
                                    删除
                                </span>
                            </button>-->
                        </div>
                        <span id="fileWarn" class="font-red"></span>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-2 control-label">静态文件</label>
                <div class="col-md-10">
                    <div class="scroller" style="height:300px;" data-always-visible="1">
                        <input type="hidden" name="static_file" id="static_file" value="<?= !empty($adminExt) ? $adminExt->department : 0 ?>" class="form-control input-large maxlength-handler validate-box" >
                        <div id="department_tree" class="tree-demo">

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
</div>

<script type="text/javascript">   
	$(function(){ 
		var s = createFilesTree();
	});                       
                        
    var tpltype = $('#type').val();
    fileType(tpltype);
    function fileType(type) {
        var flag = true;
        var html = '';
        if(type < 0) {
            alert('请选择文件类型');
            flag = false;
        }
        if(flag) {
            if($.inArray(type, ['1','12']) >= 0) {
                $("#url_div").css('display','none');
                $('#url_rules').val(' ');
            }
            else {
                $("#url_div").css('display','block');
            }
        }
    }

    function handleFile(fileName) {
        var flag = true;
        var num = 0;
        var typearr = ['index', 'category', 'detail', 'album','error'];
        var type =  $("#type").find("option:selected").val();

        var files = fileName.files;
        var countNumber = files.length;
        if($.inArray(type,typearr) >= 0 ) {
            var name = type+'.tpl';
            num = 1;
            if(countNumber == num) {
                if(name == files[0].name) {
                    flag = true;
                }
                else {
                    alert('请上传正确的文件名');
                    flag = false;
                }
            }
            if(countNumber > num && num > 0) {
                alert('只能上传一个文件');
                flag = false;
            }
        }
        if(flag) {
            var count = "选择了" + countNumber + "个文件"
            $(".multipleupload span").html(count);
        }
    }


    function createFilesTree() {
        $('#department_tree').jstree({
            //'plugins': ["checkbox", "types"],
            'core': {
                "themes": {
                    "responsive": false
                },
                'data' : {
                    'url' : function (node) {
                        return '/tpl/json?id=<?php echo $category_id;?>&type=categorydetail';
                    },
                    'data' : function (node) {
                        return { 'id' : node.text, 'href': "/tpl/deletefiles?id="+node.id };
                    }
                }
            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                }
            }
        });
    }
 

    jQuery.validator.addMethod("typesame", function (value, element) {
        var existflag = 1;
        $.ajax({
            type:"POST",
            url:'/tpl/typeSame',
            async:false,
            data:{'type':value,'domain_id':<?= $domain_id ?> },
            success: function(msg){
                if(msg == 'exist'){
                    existflag = 0;
                }
            }
        });
        if(existflag == 1){
            return true;
        }
        else{
            return false;
        }
    } ,  "对不起，该域名下该模板类型已存在" );

    function import_quote(e) {
		var domain_id = $('#domain_id').val();
		var topicfile = $('#topicfile').val();
		var static_file = $('#static_file').val();
	    var parentWin=window.opener;
	    var data = {domain_id: domain_id, topicfile: topicfile, static_file: static_file};
	    
	   // console.log(s);
	    parentWin.postMessage(data, "*");
	    if (e.preventDefault){
	        e.preventDefault();
	    }
	    e.returnValue = false;
	  //  window.parent.close();
	}

</script>

