<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit">
    <meta content="user-scalable=no,width=640, minimum-scale=0.5" name="viewport">
    <meta name="format-detection" content="telephone=no">
    <title>摇奖频道</title>
    <link rel="stylesheet" type="text/css" href="<?=static_url('css/all.css')?>"/>
</head>