<?php

/**
 * Created by PhpStorm.
 * User: fang
 * Date: 2016/8/2
 * Time: 16:02
 */
class AnchorController extends BaseController
{
    const CUIQI = 1;   //崔麒
    const YONGKUN = 2;  //永坤
    const HULINLIN = 3;  //胡玲玲
    const LANTE = 4;   //LT郎特
    const HUAHUA = 5;  //花花
    const XUNUO = 6;  //许诺
    const XIAOYU = 7;  //小雨
    const GAOWEN = 8;  //高雯
    const ANCHOR_COUNT = "anchorCount";
    const ANCHOR = "anchorId:";

    /**
     * 初始化方法
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //允许跨域请求
        $this->crossDomain();
    }

    /**
     * 增加游戏次数
     */
    public function addAction()
    {
        $id = Request::getQuery('id', 'int', 0);
        if ($id > 0 && $id < 9) {
            $res = RedisIO::incrBy(self::ANCHOR . $id, 199); //递增199
            RedisIO::incrBy(self::ANCHOR_COUNT, 199);        //递增199
            $this->_json($res);
        } else {
            $this->_json([], 4006, "error");
        }
    }

    /**
     *
     * 获取主播游戏数
     *
     */
    public function getAction()
    {
        $id = Request::getQuery('id', 'int', 0);
        if ($id > 0 && $id < 9) {
            $res = RedisIO::get(self::ANCHOR . $id);
            $this->_json($res);
        } else {
            $this->_json([], 4007, "error");
        }
    }

    /**
     *
     * 获取所有主播游戏数
     */
    public function getCountAction()
    {
        $res = RedisIO::get(self::ANCHOR_COUNT);

        if ($res < 12382) {
            RedisIO::set(self::ANCHOR_COUNT, 12382);  //初始值12382
            $this->_json($res);
        } else {
            $this->_json($res);
        }
    }


    /**
     * 允许跨域请求
     */
    private function crossDomain()
    {
        $host = isset($_SERVER['HTTP_ORIGIN']) ? $_SERVER['HTTP_ORIGIN'] : '';
        if (false !== strpos($host, 'cztv')) {
            header('content-type:application:json;charset=utf8');
            header('Access-Control-Allow-Origin:' . $host);
            header('Access-Control-Allow-Methods:POST,GET,PUT');
            header('Access-Control-Allow-Headers:x-requested-with,content-type');
        }

    }

    /**
     * @param $data
     * @param int $code
     * @param string $msg
     */
    protected function _json($data, $code = 200, $msg = "success")
    {
        echo json_encode([
            'code' => $code,
            'msg' => $msg,
            'data' => $data,
        ]);
        exit;
    }

    /**
     * 设置默认站点
     * @see BaseController::defaultDomainCheck()
     */
    protected function defaultDomainCheck($host)
    {
        $this->domain_id = 6;
        $this->channel_id = 1;
        return true;
    }


}