<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit">
    <title>中国蓝TV - 浙江广播电视集团新媒体 - 浙江第一视频门户</title>
    <meta name="Keywords" content="明星,娱乐,视频,新闻,网络电视,时尚门户,电视直播,浙江卫视,影视,浙江广电,电视台,中国蓝"/>
    <meta name="Description"
          content="浙江广播电视集团新媒体，整合浙江卫视在内的18个广播电视频道的优势资源， 打造“浙江第一视频门户”，为网民提供互联网、通信网、电视网三网融合、无缝衔接的新媒体优质服务。"/>
    <link rel="shortcut icon" href="http://tv.cztv.com/cztv/user/favicon.ico"/>
    <link type="text/css" rel="stylesheet" href="http://tv.cztv.com/cztv/user/core.css"/>
    <link type="text/css" rel="stylesheet" href="http://tv.cztv.com/cztv/user/style.css"/>
    <!--[if lte IE 6]>
    <div class="ie6_div">
        <div class="ie6_content">亲，您正在使用过时的浏览器，提升体验您可以：<img src="http://tv.cztv.com/cztv/user/ie6_ie.png"><a
            href="http://windows.microsoft.com/zh-cn/internet-explorer/download-ie">【升级IE浏览器】</a>或点击下载<img
            src="http://tv.cztv.com/cztv/user/ie6_360.png" style="padding-left: 8px;"><a href="http://se.360.cn/">【360安全浏览器】</a><img
            src="http://tv.cztv.com/cztv/user/ie6_chrome.png" style="padding-left: 8px;"><a
            href="http://www.google.cn/intl/zh-CN/chrome/">【chrome浏览器】</a></div>
    </div>
    <script src="http://tv.cztv.com/bluetv/user/iepng.js" type="text/javascript"></script>
    <script type="text/javascript">
        DD_belatedPNG.fix('div, ul, img, li, input , a, i, em');
    </script>
    <![endif]-->
</head>
<body id="autoBody">
<!--top-nav/S-->
<?php $this->partial('cms/cztv_public_head'); ?>
<?php $this->partial('cms/cztv_public_css'); ?>
<!--top-nav/E-->
<!-- usercenter/S-->
<div class="ui-warp ui-comwidth ui-cf">
    <div class="ui-usercenter ui-cf" id="usercenter">
        <div class="ui-user-nav">
            <div class="ui-user-pic ui-cf">
                <img src="http://i0.letvimg.com/img/201207/30/tx70.png" alt="用户头像" title="用户头像"/>
                <p title="Barry">Barry</p>
            </div>
            <ul class="ui-cf">
                <li>
                    <a href="/setting/index" title="账号信息"><i class="icon-user-info"></i><span>账号信息</span></a>
                </li>
                <li class="active">
                    <a href="/playrecord/index" title="观看记录"><i class="icon-user-history"></i><span>观看记录</span></a>
                </li>
                <li title="我的收藏">
                    <a href="/favorite/index"><i class="icon-user-collection"></i><span>我的收藏</span></a>
                </li>
            </ul>
        </div>
        <div class="ui-user-con ui-cf">
            <div id="user-box" class="ui-user-box ui-cf">
                <h2 class="ui-user-title" title="观看记录">观看记录</h2>
            </div>
        </div>
    </div>
</div>
</div>
<!-- usercenter/E-->
<!-- footer/S-->
<?php $this->partial('cms/cztv_public_footer'); ?>
<!-- footer/E-->
<!-- nav-fixed/S-->
<!-- nav-fixed/E-->
<!-- modal-confirm/S-->
<div class="ui-modal ui-modal-sm" id="ui-modal-del">
    <div class="ui-modal-warp">
        <!-- <a href="javascript:;" class="ui-modal-close ui-modal-closed">X</a> -->
        <div class="ui-modal-content">
            <!-- 配置隐藏域用于删除 ui-form-id是dialog配置传入的 -->
            <input type="hidden" value="" id="ui-form-id"/>
            <div class="ui-modal-del ui-text-center ui-cf">
                <p class="confirm"><i class="ui-icon-warning"></i><span>您确定要删除么？</span></p>
                <p class="btns">
                    <a href="javascript:;" class="ui-btn ui-btn-primary ui-btn-xs ui-modal-ok">确定</a>
                    <a href="javascript:;" class="ui-btn ui-btn-danger ui-btn-xs ui-modal-close">取消</a>
                </p>
            </div>
        </div>
    </div>
</div>
<!-- modal-confirm/E-->
<script type="text/javascript" src="http://tv.cztv.com/bluetv/user/core.js"></script>
<script src="http://tv.cztv.com/bluetv/base/jqueryCookie.js"></script>
<script type="text/javascript" src="http://tv.cztv.com/bluetv/user/main.js"></script>
<script src="http://tv.cztv.com/bluetv/header/user.js"></script>
<script src="http://tv.cztv.com/bluetv/header/autoComplete.js"></script>
<script src="http://tv.cztv.com/bluetv/storage/swfobject.js"></script>
<script src="http://tv.cztv.com/bluetv/storage/xlPlayer.js"></script>
<script src="https://ohudong.cztv.com/1/250886/js/history20171208.js"></script>
<script>
    var _gsChannel = "/用户中心/观看记录/";
    $(function () {
        (function () {
            var s = document.createElement('script');
            s.type = 'text/javascript';
            s.async = true;
            s.src = (location.protocol == 'https:' ? 'https://ssl.' : 'http://static.') + 'gridsumdissector.com/js/Clients/GWD-002664-693004/gs.js';
            var firstScript = document.getElementsByTagName('script')[0];
            firstScript.parentNode.insertBefore(s, firstScript);
        })();
    });
</script>
</body>
</html>