<?php
Input::init(Request::get(),[]);
if(!isset($search)){
    $search=array();
}
?>
<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form role="form" method="get" class="form-horizontal form-bordered form-label-stripped" action="/audit_ban_comments/search">
            <div class="form-body">
                <div class="form-group ">
                    <label class="control-label col-md-2">搜索</label>
                    <div class="col-md-10">
                        <div class="screening-order">
                            <input type="text" class="form-control input-small  margin-right-10" placeholder="输入用户ID" name="ssoid" />
                            <input type="submit" class="btn blue breadcrumbbtn" value="搜索" />
                        </div>
                    </div>
                </div>
            </div>
            
        </form>
    </div>
    <?php if($search){?>
        <div class="search-result">
            <dt><a href="/audit_ban_comments/index">所有结果</a></dt> >
            <dd>
                <?php if(isset($search['ssoid'])):?>
                   <span><?=$search['ssoid']?></span>
                <?php endif;?>

                <a href='/audit_ban_comments/index'><i class="fa fa-times"></i></a>
            </dd>
        </div>
        <?php } ?>
        <!-- END FORM-->
    </div>
</div>

