<?php
Input::init(Request::getPost(), $model);
?>
<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped form-stations" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i><?= $action ?></span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <input type="hidden" name="media_type" id="media_type" value="<?= isset($media_type) ? $media_type:"1";?>">
            <div class="form-group">
                <label class="control-label col-md-2">模板名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" placeholder="模板名称" value="<?= Input::fetch('name') ?>" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">扩展参数:<span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <section class="col">
                            <?php
                                foreach($custom_params as $param) {


                            ?>
                            <input type="checkbox" class='checkbox_term' name="params[]" id="params[]" value="<?=$param['id']?>" <?php if(in_array($param['id'], $data_template_params)) echo "checked"; ?> /><?=$param['param_label']?>
                            <?php
                                }
                            ?>
                        </section>
                    </div>
                </div>
            </div>

        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">
    // form stations
    $('.form-stations').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required: true
            }
        },
        messages: {
            name: {
                required: '名称不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
            //parent.location.reload(); //Refresh Iframe parent
        }

    });
</script>