<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-site" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加站点</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>

            <div class="form-group">
                <label class="control-label col-md-2">Logo <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="logonail" id="logonail" class="file-loading"/>
                        <input type="hidden" name="logo" value=""/>
                    </div>
                    <span class="help-block">请上传图片大小为300px-300px</span>
                </div>
            </div>
            <script>
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    minFileCount: 1,
                    maxFileCount: 1,
                    language: "zh",
                    minImageWidth: 100,
                    minImageHeight: 100,
                    //单位kb
                    maxFileSize: 2048,
                    allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'
                };
                $("#logonail").fileinput(thumbnailConfig);
            </script>

            <div class="form-group">
                <label class="control-label col-md-2">站点名 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="name" placeholder="站点名" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">域名 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="domain" placeholder="域名" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">授权电台ID</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <?php $data=Stations::getStationsByChannel(Auth::user()->channel_id);
                        foreach($data as $s) {?>
                            <label><input type="checkbox" name="stations[]" value="<?=$s['id']?>"><?=$s['name']?>[<?=$s['code']?>]</label>
                       <?php } ?>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">状态</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label><input type="radio" class="icheck" name="status" value="0"/>禁用</label>
                        <label><input type="radio" class="icheck" name="status" value="1" checked/>开启</label>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    // form stations
    $('#form-site').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required: true,
                minlength: 2
            },
            domain: {
                required: true
            }
        },

        messages: {
            name: {
                required : '站点名不能为空',
                minlength: '站点名至少为2个字符'
            },
            domain: {
                required: '域名不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            if(element.is(':radio') || element.is(':checkbox')) {
                error.appendTo(element.parents(".icheck-inline"));
            }
            else {
                error.insertAfter(element.closest('.validate-box'));
            }
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>