<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['站点列表' => Url::get('site/index')],
    'add'=> Url::get('site/add'),
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>站点名</th>
            <th>终端ID</th>
            <th>密钥</th>
            <th>域名</th>
            <th>授权电台</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($models = $data->models)) :
            foreach ($models as $v) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td>
                        <img class="small-img" src="<?php if($v->logo) { echo cdn_url('image',$v->logo); } else{?> /assets/admin/layout/img/sidebar_inline_toggler_icon_blue.jpg<?php } ?>" />
                        <span class="name-center">
                            <?= $v->name ?>
                        </span>
                    </td>
                    <td><?= $v->app_id ?></td>
                    <td><?= $v->app_secret ?></td>
                    <td><?= $v->domain ?></td>
                    <td><?php
                       $stations = explode(',', $v->stations);
                       foreach ($stations as $s) {
                           echo $stations_data2[$s]['code']." ";
                       }
                    ?>
                    </td>
                    <td><?php echo ($v->status==1)?'开启':'禁用' ?></td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn green edit-content tooltips" data-url="<?= Url::get('site/upd', ['id' => $v->id]) ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/site/del?id=<?= $v->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default">删除</button>
                </div>
            </div>
            <?= $data->pagination->render() ;?>
            <div class="pagination-info"><?=Lang::_('total')."： ".$data->count?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        7:{sorter:false}
    }
});
</script>