<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="/private_category/update" class="form-horizontal form-bordered form-label-stripped" id="form-category" enctype="multipart/form-data" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>修改分类</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>
        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>
            <input type="hidden" name="channel_id" value="<?=$category->channel_id?>">
            <input type="hidden" name="id" value="<?=$category->id?>">
            <input type="hidden" name="father_id" id="father_id" value="<?=$category->father_id?>">
            
            <div class="form-group">
                <label class="col-md-2 control-label">上级分类 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="scroller" style="height:300px;" data-always-visible="1">
                        <div id="category_tree" class="tree-demo">
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $('.linkage-select').cxSelect({
                    url: '/category/json',
                    selects: ['linkage-one', 'linkage-two', 'linkage-three', 'linkage-four'],
                    nodata: 'none'
                });
            </script>            
            
            <div class="form-group">
                <label class="control-label col-md-2">分类名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" placeholder="分类名" maxlength="50" value="<?=$category->name?>" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">
    // form stations
    $('#form-category').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required : true
            }
        },

        messages: {
            name: {
                required : '分类名不能为空'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });

    function createCategoryTree() {
        $('#category_tree').jstree({
            //'plugins': ["checkbox", "types"],
            'core': {
                "themes": {
                    "responsive": false
                },
                'data' : {
                    'url' : function (node) {
                        return '/private_category/json?media_type=<?=$category->media_type?>&id=<?=$category->id?>';
                    },
                    'data' : function (node) {
                        return { 'id' : node.text };
                    }
                }
            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                }
            }
        })
    }

    $(function() {
        createCategoryTree();
        $('#category_tree')
            // listen for event
            .on('changed.jstree', function (e, data) {
                var i, j, r = [];
                for(i = 0, j = data.selected.length; i < j; i++) {
                    $("#father_id").val(data.instance.get_node(data.selected[i]).id);
                }
                if(data.selected.length==0) {
                    $("#father_id").val(0);
                }

            })
            // create the instance
            .jstree();
    });

</script>