<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped form-stations" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加评论列表</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>

            <div class="form-group">
                <label class="control-label col-md-2">主题 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="code" placeholder="CODE" value="" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">评论方式 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="code" placeholder="CODE" value="" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">发布方式 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="name" placeholder="电台名" value="" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">防刷机制 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="channel_name" placeholder="直播流字段1" value="" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">状态 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="customer_name" placeholder="直播流字段2" value="" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    // form stations
    $('.form-stations').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            channel_id: {
                required : true
            },
            code: {
                required : true,
                number: true
            },
            name: {
                required : true
            },
            channel_name: {
                required : true
            },
            customer_name: {
                required : true
            }
        },

        messages: {
            channel_id: {
                required : '所属频道不能为空'
            },
            code: {
                required : '请输入正确的电视台ID',
                number : '电视台ID必须为数字'
            },
            name: {
                required : '电台名不能为空'
            },
            channel_name: {
                required : '直播流字段不能为空'
            },
            customer_name: {
                required : '直播流字段不能为空'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>