<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['评论列表' => Url::get('comment/commentindex')],
    'add'=> Url::get('comment/add'),
]);
?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>专题名称</th>
                <th>发布方式</th>
                <th>匿名评论</th>
                <th>防刷机制</th>
                <th>防刷时间间隔</th>
                <th>创建时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <?php
        if(isset($data->models)) $speccomment = $data->models;
            if (!empty($speccomment)) :
                foreach ($speccomment as $item) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td><?=$item->themname ?></td>
                    <td><?=$item->publishway == '1'?'先发后审':($item->publishway == '2'?'先审后发':'') ?></td>
                    <td><?=$item->anonymous ==1?'匿名评论':'实名评论' ?></td>
                    <td><?=$item->prevent_action==1?'有':'无' ?></td>
                    <td><?=$item->prevent_action==1?$item->interval:0 ?></td>
                    <td><?= date('Y-m-d H:i:s', $item->create_at)?></td>
                    <td><?= $item->adminid?'已审核':'未审核' ?></td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn blue-steel href-location tooltips" data-url="/comment/detail/?data_id=<?= $item->id ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="审查"><i class="fa fa-check-square-o"></i></button>
                            <button type="button" class="btn green edit-content tooltips" data-url="/comment/edit/?data_id=<?=$item->id ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>

        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">

            <div class="pagination-info"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        2:{sorter:false},
        5:{sorter:false}
    }
});
</script>