<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="/vote_option/edit?id=<?=$data->id?>" method="post" class="form-horizontal form-bordered form-label-stripped form-vote" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>编辑投票选项</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>
        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <input type="hidden" name="id" value="<?= $data->id?>"/>
            <div class="form-group">
                <label class="control-label col-md-2">选项内容 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="content" value="<?=$data->content?>" placeholder="选项内容" class="validate-box form-control input-large" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">选项图片 </label>
                <div class="col-md-10">
                    <div class="input-large image-delete-shutdown">
                        <input type="file" name="picture" id="thumbnail" class="file-loading"/>
                        <input type="hidden" name="picture" value="<?=$data->picture?>"/>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">视频播放地址 </label>
                <div class="col-md-10">
                    <input type="text" name="video_url" value="<?=$data->video_url?>" placeholder="视频播放地址" class="validate-box form-control input-large " />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">是否需要填空</label>
                <div class="col-md-10">
                    <div class="icheck-list">
                        <label>
                            <input type="radio" class="icheck" <?= $data->other==1?'checked':''?> name="other" value="1"/>
                            需要</label>
                        <label>
                            <input type="radio" class="icheck" <?= $data->other==0?'checked':''?> name="other" value="0" />
                            不需要</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">显示数量 </label>
                <div class="col-md-10">
                    <input type="text" name="sum" value="<?=$data->sum?>" placeholder="显示数量" class="validate-box form-control input-large " />
                </div>
            </div>

        </div>
    </form>
    <!-- END FORM-->
</div>


<script type="text/javascript">
    // form stations
    $('.form-vote').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            content: {
                required : true
            }
        },

        messages: {
            content: {
                required : '投票内容不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });

    var thumbnailConfig = {
        uploadAsync: false,
        showRemove: false,
        showCaption: false,
        showUpload: false,
        overwriteInitial: true,
        maxFileCount: 1,
        language: "zh",
        minImageWidth: 100,
        minImageHeight: 100,
        //单位kb
        maxFileSize: 2048,
        allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
        //允许上传 & 允许预览的类型
        allowedFileTypes: ['image'],
        previewFileType: "image",
        browseLabel: '浏览 ...'<?php if($data->picture) { ?>,
        /**
         * 预加载数据
         */
        //预加载删除
        initialPreviewShowDelete: false,
        //预加载图片
        initialPreview: ['<img src="<?= cdn_url('image',$data->picture)?>" class="file-preview-image">'],
        //预加载图片对应配置
        initialPreviewConfig: [{caption: "图片"}]
        <?php } ?>
    };
    $("#thumbnail").fileinput(thumbnailConfig);
</script>