<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['过滤词列表' => Url::get('audit_comment_keywords/index')],
    'add' => Url::get('audit_comment_keywords/add'),
    'html' => ''
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>关键词</th>
            <th>添加时间</th>
            <th>操作员</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
            <?php
            if($data&&isset($data->models)) $models = $data->models;
            if (!empty($models)) :
            foreach ($models as $v) :
            ?>

                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td><?= $v->keyword ?></td>
                    <td><?= date('Y-m-d H:i:s',$v->addtime) ?></td>
                    <td><?= $v->audit_name ?></td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn red tooltips" data-url="<?=Url::get('audit_comment_keywords/delete', ['id'=>$v->id])?>"  onclick="show_confirm(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                        </div>
                    </td>
                </tr>
            <?php
                endforeach;
            endif
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        4:{sorter:false}
    }
});
</script>