<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form class="form-horizontal form-bordered form-label-stripped" id="form-greeting" method="post" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>修改节目</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>

            <div class="form-group">
                <label class="control-label col-md-2">节目名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" placeholder="节目名称" value="<?=$show->name?>" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">节目编号 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="sort" type="text" placeholder="节目编号" value="<?=$show->sort?>" maxlength="3" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">节目类型 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="type" type="text" placeholder="节目类型" value="<?=$show->type?>" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">投票开关</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label>
                            <input type="radio" class="icheck" name="status" <?=$show->status==0?'checked':''?> value="0"/>
                            关闭</label>
                        <label>
                            <input type="radio" class="icheck" name="status" <?=$show->status==1?'checked':''?> value="1" />
                            开启</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">选送频道 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="channel_name" type="text" placeholder="选送频道" value="<?=$show->channel_name?>" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">选送频道Logo </label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="channel_logonail" id="channel_logonail" class="file-loading"/>
                        <input type="hidden" name="channel_logo" value="<?=$show->channel_logo?>"/>
                    </div>
                    <span class="help-block">请上传图片大小为300px-300px</span>
                </div>
            </div>
            <script type="text/javascript">
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    maxFileCount: 1,
                    language: "zh",
                    minImageWidth: 100,
                    minImageHeight: 100,
                    //单位kb
                    maxFileSize: 5120,
                    allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'<?php if($show->channel_logo) { ?>,
                    /**
                     * 预加载数据
                     */
                    //预加载删除
                    initialPreviewShowDelete: false,
                    //预加载图片
                    initialPreview: ['<img src="<?= cdn_url('image',$show->channel_logo) ?>" class="file-preview-image">'],
                    //预加载图片对应配置
                    initialPreviewConfig: [{caption: "选送频道Logo"}]
                    <?php } ?>
                };
                $("#channel_logonail").fileinput(thumbnailConfig);
            </script>
        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    // form stations
    $('#form-greeting').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            sort:{
                digits: true,
                required: true
            },
            name: {
                required: true
            },
            channel_name: {
                required: true
            },
            type:{
                required:true
            }
        },

        messages: {
            sort:{
                digits: '节目编号必须为整数',
                required:'节目编号不能为空'
            },
            name: {
                required: '节目名称不能为空'
            },
            channel_name: {
                required: '选送频道不能为空'
            },
            type:{
                required: '类型不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>