<?php

$addaction = ($app_type=="android")?"androidadd":"iosadd";
$editaction = ($app_type=="android")?"androidedit":"iosedit";
$title = ($app_type=="android")?"安卓":"苹果";
$this->partial("partials/breadcrumb", [
    'urls' => ['APP列表' => Url::get('applist/index'), $app->name.'('.$title.')'=>"" ],
    'add'=> Url::get('applist/'.$addaction, ['app_id'=>$app->id]),
]);

?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>应用名</th>
            <th>版本</th>
            <th>状态</th>
            <th>新特性</th>
            <th>下载地址</th>
            <th>下载次数</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($models = $data->models)) :
            foreach ($models as $v) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td>
                        <img class="small-img" src="<?php if($v->logo) { echo cdn_url('image',$v->logo); } else{?> /assets/admin/layout/img/defaultlogo.png<?php } ?>" />
                        <span class="name-center">
                            <?= $v->name ?>
                        </span>
                    </td>
                    <td><?= $v->version ?></td>
                    <td><?=  ($v->publish==1)?"已发布 ":($v->status==1?"未发布":"未审核") ?><?php if($v->status==1&&$v->publish==1) echo date("Y-n-d H:i", $v->publishtime); ?></td>
                    <td><?= $v->newfeature ?></td>
                    <td><a href="<?= (stripos($v->url, "http")===false)?cdn_url('image',$v->url):$v->url ?>"><?= (stripos($v->url, "http")===false)?cdn_url('image',$v->url):$v->url ?></a></td>
                    <td><?= $v->downloads ?></td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('applist/'.$editaction, ['id'=>$v->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            <?php
                              if($v->status==1&&$v->publish==0) {
                            ?><button type="button" class="btn blue tooltips" data-url="<?=Url::get('applist/unlock',['id'=>$v->id])?>" onclick="show_confirm(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="取消审核"><i class="fa fa-check-square"></i></button>
                            <?php
                              }
                            ?>

                            <button type="button" class="btn <?= ($v->publish==1)?"red":($v->status==1?"green-jungle":"blue") ?> tooltips" data-url="<?= ($v->publish==1)?Url::get('applist/unpublish',['id'=>$v->id]):($v->status==1?Url::get('applist/publish',['id'=>$v->id]):Url::get('applist/lock',['id'=>$v->id])) ?>" onclick="show_confirm(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="<?= ($v->publish==1)?"下架":($v->status==1?"发布":"审核") ?>"><i class="fa <?= ($v->publish==1)?"fa fa-ban":($v->status==1?"fa-send":"fa-check-square-o") ?>"></i></button>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    




    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $data->pagination->render() ;?>
            <div class="pagination-info"><?=Lang::_('total')."： ".$data->count?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        1:{sorter:false},
        3:{sorter:false},
        4:{sorter:false},
        5:{sorter:false},
        6:{sorter:false},
        7:{sorter:false}
    }
});
</script>
