function PCMSAD(PID) {
  this.ID        = PID;
  this.PosID  = 0; 
  this.ADID     = 0;
  this.ADType   = "";
  this.ADName   = "";
  this.ADContent = "";
  this.PaddingLeft = 0;
  this.PaddingTop  = 0;
  this.Wspaceidth = 0;
  this.Height = 0;
  this.IsHitCount = "N";
  this.UploadFilePath = "";
  this.URL = "";
  this.SiteID = 0;
  this.ShowAD  = showADContent;
  this.Stat = statAD;
}

function statAD() {
  var new_element = document.createElement("script"); 
  new_element.type = "text/javascript";

  document.body.appendChild(new_element);
}

function showADContent() {
  var content = this.ADContent;
  var str = "";
  var AD = eval('('+content+')');
  if (this.ADType == "images") {
    if (AD.Images[0].imgADLinkUrl) str += "<a href='"+AD.Images[0].imgADLinkUrl+"' target='_blank'>";
    str += "<img title='"+AD.Images[0].imgADAlt+"' src='"+this.UploadFilePath+AD.Images[0].ImgPath+"' width='"+this.Width+"' height='"+this.Height+"' style='border:0px;'>";
    if (AD.Images[0].imgADLinkUrl) str += "</a>";
  }else if(this.ADType == "flash"){
    str += "<object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000' width='"+this.Width+"' height='"+this.Height+"' id='FlashAD_"+this.ADID+"' codebase='http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0'>";
    str += "<param name='movie' value='"+this.UploadFilePath+AD.Images[0].ImgPath+"' />"; 
      str += "<param name='quality' value='autohigh' />";
      str += "<param name='wmode' value='opaque'/>";
    str += "<embed src='"+this.UploadFilePath+AD.Images[0].ImgPath+"' quality='autohigh' wmode='opaque' name='flashad' swliveconnect='TRUE' pluginspage='http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash' type='application/x-shockwave-flash' width='"+this.Width+"' height='"+this.Height+"'></embed>";
      str += "</object>";   
  }
  str += "";
  document.write(str);
}

 
var cmsAD_<?= $advert['advert']->id ?> = new PCMSAD('cmsAD_<?= $advert['advert']->id ?>'); 
cmsAD_<?= $advert['advert']->id ?>.PosID = <?= $advert['advert']->id ?>; 
cmsAD_<?= $advert['advert']->id ?>.ADID = <?= $advert['advert']->spaceid ?>; 
cmsAD_<?= $advert['advert']->id ?>.ADType = "<?= Advert::getTypeName($advert['advert']->type) ?>";
cmsAD_<?= $advert['advert']->id ?>.ADName = "<?= $advert['advert']->name ?>"; 
cmsAD_<?= $advert['advert']->id ?>.ADContent = "{'Images':[{'imgADLinkUrl':'<?php if($img[0]['linkurl'] == 'http://') echo '';
 else echo $img[0]['linkurl']?>','imgADAlt':'<?= $img[0]['alt'] ?>','ImgPath':'<?= $img[0]['imageurl'] ?>'}],'imgADLinkTarget':'New','Count':'1','showAlt':'Y'}"; 
 
cmsAD_<?= $advert['advert']->id ?>.SiteID = 1; 
cmsAD_<?= $advert['advert']->id ?>.Width = <?= $advert['advertSpace']->width ?>; 
cmsAD_<?= $advert['advert']->id ?>.Height = <?= $advert['advertSpace']->height ?>; 
cmsAD_<?= $advert['advert']->id ?>.UploadFilePath = ''; 
cmsAD_<?= $advert['advert']->id ?>.ShowAD();

var isIE=!!window.ActiveXObject; 
if (isIE){

  if (document.readyState=="complete"){
    cmsAD_<?= $advert['advert']->id ?>.Stat();
  } else {
    document.onreadystatechange=function(){
      if(document.readyState=="complete") cmsAD_<?= $advert['advert']->id ?>.Stat();
    }
  }
} else {
  cmsAD_<?= $advert['advert']->id ?>.Stat();
}