function PCMSAD(PID) {
  this.ID        = PID;
  this.PosID  = 0; 
  this.ADID		  = 0;
  this.ADType	  = "";
  this.ADName	  = "";
  this.ADContent = "";
  this.PaddingLeft = 0;
  this.PaddingTop  = 0;
  this.Width = 0;
  this.Height = 0;
  this.IsHitCount = "N";
  this.UploadFilePath = "";
  this.URL = "";
  this.SiteID = 0;
  this.ShowAD  = showADContent;
  this.Stat = statAD;
}

function statAD(id) {
	var sp = document.createElement("SCRIPT");
	sp.type = "text/javascript";
	document.body.appendChild(sp);
}

function showADContent() {
  var content = this.ADContent;
  var isIE=!!window.ActiveXObject;
  var str = "<div id='PCMSAD_"+this.PosID+"'>";
  var AD = eval('('+content+')');
  var count = 0;
  if(AD.ADText.length){
	  count = AD.ADText.length;
  }
  for(var i=0;i<count;i++){
	if (isIE){

		if (document.readyState=="complete"){
			this.Stat(AD.ADText[i].textID);
		} else {
			document.onreadystatechange=function(){
				if(document.readyState=="complete") this.Stat(AD.ADText[i].textID);
			}
		}
	} else {
		this.Stat(AD.ADText[i].textID);
	}
	  str += "<li><a href="+AD.ADText[i].textLinkUrl+" target='_blank' title='"+AD.ADText[i].textContent+"'>"+AD.ADText[i].textContent+"</a></li>";
	}
  str += "</div>";
  document.write(str);
}
 
var cmsAD_<?= $advert['advert']->id ?> = new PCMSAD('cmsAD_<?= $advert['advert']->id ?>'); 
cmsAD_<?= $advert['advert']->id ?>.PosID = <?= $advert['advert']->spaceid ?>; 
cmsAD_<?= $advert['advert']->id ?>.ADID = <?= $advert['advert']->id ?>; 
cmsAD_<?= $advert['advert']->id ?>.ADType = "<?= $advert['advert']->type ?>"; 
cmsAD_<?= $advert['advert']->id ?>.ADName = "<?= $advert['advert']->name ?>"; 
cmsAD_<?= $advert['advert']->id ?>.ADContent = 
  "{'ADText':[{'textID':'<?= $advert['advert']->id ?>','textContent':'<?= $img[0]['alt'] ?>','textLinkUrl':'<?= $img[0]['linkurl'] ?>'} ]}"; 
cmsAD_<?= $advert['advert']->id ?>.SiteID = 1; 
cmsAD_<?= $advert['advert']->id ?>.Width = <?= $advert['advertSpace']->width ?>;
cmsAD_<?= $advert['advert']->id ?>.Height = <?= $advert['advertSpace']->height ?>;
cmsAD_<?= $advert['advert']->id ?>.UploadFilePath = ""; 
cmsAD_<?= $advert['advert']->id ?>.ShowAD();
