<?php
$this->partial("partials/breadcrumb", [
    'urls'=>['部门列表'=>Url::get('department/index')],
    'add'=>Url::get("department/add")
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>部门</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <?php
        if (isset($departments)) :
            foreach ($departments as $v) :
                ?>
                <tr name="<?=$v['father_id']==0 ? $v['id'] : $v['father_id']?>_<?=$v['level']?>" level="<?=$v['level']?>" class="categorylevel_<?=$v['level']?>" style="display: <?= ($v['level'])>0?'none':'' ?>" >
                    <td name="categorytitle">
                        <div class="<?=$v['has_child'] ? 'cateplus' : ''?> categoryname" <?=$v['has_child'] ? 'onclick="categorytree(this,' . $v['id'] . ',' . ($v['level'] + 1) . ')"' : 0?>>
                            <i></i>
                            <img class="small-img" src="<?=empty($v['logo']) ? '/assets/admin/layout/cztv_img/defaultlogo.png' : cdn_url('image',$v['logo'])?>"/>
                            <span class="name-center" ><?= $v['name'] . '(' . $v['id'] . ')' ?></span>
                        </div>
                    </td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <?php if($checkAuth('department/edit')){?>
                                <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('department/edit',['id'=>$v['id']])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            <?php }?>
                            <?php if($checkAuth('department/delete')){?>
                                <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/department/delete?id=<?=$v['id']?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            <?php }?>
                        </div>
                    </td>
                </tr>

                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <?= $data->pagination->render();?>
                <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        2:{sorter:false}
    }
});


function categorytree(elem,father,level){
    var str = 'tr[name='+father+'_'+level+']';
    if($(elem).attr('class')=='cateplus categoryname'){
        $(elem).attr('class','cateminus categoryname');
        $(str).css('display','');
    }
    else{
        $(elem).attr('class','cateplus categoryname');
        var level = $(elem).parent().parent().attr('level');
        var next = $(elem).parent().parent().next();
        for(var i=0;;i++){
            if(next.attr('level')>level){
                next.css('display','none');
                if(next.children('td[name=categorytitle]').children().attr('class')=='cateminus categoryname'){
                    next.children('td[name=categorytitle]').children().attr('class','cateplus categoryname');
                }
                next=next.next();
            }else{
                break;
            }
        }
    }
}
</script>
