<?php 
Input::init(Request::getPost(), $data);
?>
<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form class="form-horizontal form-bordered form-label-stripped" id="form-admin" enctype="multipart/form-data" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i><?= $action ?></span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>

            <div class="form-group">
                <label class="control-label col-md-2">频道 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <?= $this->partial('partials/channel', ['channel' => $channel,'channel_id'=>Input::fetch('channel_id')]) ?>
                    <span class="help-block"></span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">手机号 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="mobile" type="text" placeholder="手机号" maxlength="11" class="form-control input-large maxlength-handler validate-box" value="<?= Input::fetch('mobile');?>"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">姓名 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" placeholder="姓名" maxlength="20" class="form-control input-large maxlength-handler validate-box" value="<?= Input::fetch('name');?>"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">密码 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="password" type="password" placeholder="密码" maxlength="20" class="form-control input-large maxlength-handler validate-box" <?= Input::fetch('password');?>/>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">

    jQuery.validator.addMethod("issecurity", function (value, element) {
        var length = value.length;
        var lv = 0;
        if (value.match(/[a-z]/ig)) {
            lv++;
        }
        if (value.match(/[0-9]/ig)) {
            lv++;
        }
        if (value.match(/(.[^a-z0-9])/ig)) {
            lv++;
        }
        if (length < 8 && lv > 0) {
            lv--;
        }
        if (lv < 2) {
            return false;
        }
        else {
            return true;
        }
    }, "密码过于简单！");

    jQuery.validator.addMethod("ismobile", function (value, element) {
        var length = value.length;
        var mobile = /^1[3|4|5|7|8|][0-9]{9}$/;
        return   this.optional(element) || (length == 11 && mobile.test(value));
    }, "请正确填写您的手机号码");

    function issecurity2(value) {
        var length = value.length;
        var lv = -1;
        if (value.match(/[a-z]/ig)) {
            lv++;
        }
        if (value.match(/[0-9]/ig)) {
            lv++;
        }
        if (value.match(/(.[^a-z0-9])/ig)) {
            lv++;
        }
        if (length < 6 && lv > 0) {
            lv--;
        }
        if (lv < 1) {
            return false;
        }
        else {
            return true;
        }
    }

    // form stations
    $('#form-admin').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            mobile: {
                required: true,
                number: true,
                ismobile: true,
                minlength: 11,
                maxlength: 11
            },
            name: {
                required: true
            },
            <?php if(!Request::get('id')){?>
            password: {
                issecurity: true,
                required: true,
                minlength: 8,
                maxlength: 20
            },
            <?php }?>
        },
        messages: {
            mobile: {
                required: '请输入正确的手机号码',
                number: '手机号码不能有字母字符',
                minlength: '手机号不能少于11位',
                maxlength: '手机号不能多于11位'
            },
            name: {
                required: '姓名不能为空'
            },
            password: {
                issecurity: '密码过于简单',
                required: '新密码不能为空',
                minlength: '密码长度不能少于8位',
                maxlength: '密码长度不能超过20位'
            }
        },
        invalidHandler: function (event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },
        highlight: function (element) { // hightlight error inputs
            $(element)
                    .closest('.form-group').addClass('has-error'); // set error class to the control group
        },
        success: function (label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },
        submitHandler: function (form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>