<?php

class DeptController extends InteractionBaseController {


   public function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
   }

    /**
    * 获取所有部门并建树
    */
    public function getDeptAction(){
        $channel_id = intval(Request::getQuery('channel_id','int',1));
        $dept = GovernmentDepartment::getDeptByChannelId($channel_id);
        $dept_tree = $this->_tree($dept);
        $this->_json($dept_tree);

    }


    /**
     * 构建树
     * @param $res
     * @return array
     */
    protected function _tree($res)
    {
        $items = array();
        foreach ($res as $val) {
            if(isset($val['id'])){
                $items[$val['id']] = $val;
            }
        }

        $tree = array();
        foreach ($items as $key => $item) {
            if (isset($items[$item['father_id']])) {
                $items[$item['father_id']]['sons'][] = &$items[$item['id']];
            } else {
                $tree[] = &$items[$item['id']];
            }
        }
        return $tree;

    }

    /**
     * @param $data
     * @param int $code
     * @param string $msg
     */
    protected function _json($data, $code = 200, $msg = "success")
    {
        header('Content-type: application/json');
        echo json_encode([
            'code' => $code,
            'msg' => $msg,
            'data' => $data,
        ]);
        exit;
    }



}