<!-- 后台登录页面 -->
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <title>新蓝云平台-浙江广播电视集团新媒体</title>
        <meta name="Author" content="mengqingqiang"/>
        <meta name="Description" content="新蓝云平台是浙江广播电视集团旗下的新媒体联合互动运营平台，是整合浙江广电集团内外优势资源，面向广电行业的新媒体一站式服务平台，由浙江新蓝网络传媒体有限公司负责技术支撑和运营支撑。"/>
        <meta name="Keywords" content="浙江广电,浙江广播电视集团,广电新媒体,浙江卫视,新蓝网,广播,电视 ,新媒体,云平台,市县广电新媒体,网络直播,网络点播  "/>
        <meta name="Generator" content="浙江新蓝网络传有限公司,浙江广播电视集团新蓝网,新蓝网,www.cztv.com "/>
        <meta name="Revised" content="V.1.1"/>
        <meta name="Others" content="一站式广播电视新媒体服务平台"/>

        <meta charset="utf-8"/>      
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">        
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        <link rel="shortcut icon" href="/assets/global/img/favicon.ico"/>
        <!-- 引入共用CSS -->
        <!-- <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/> -->
        <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="/assets/admin/pages/css/login.css" rel="stylesheet" type="text/css"/>
    </head>

    <body class="login">
        <script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <!-- logo -->
        <div class="logo">
            <a href="index" class="logo-content">
                <img src="<?= $channel ? cdn_url('image',$channel->channel_logo)."?x-oss-process=image/resize,w_160,h_160,m_fixed/auto-orient,0/quality,q_90/sharpen,1/format,src" : D::defaultImage('logo')."?x-oss-process=image/resize,w_160,h_160,m_fixed/auto-orient,0/quality,q_90/sharpen,1/format,src"; ?>" class="logo-img" alt="需开发填写对应名称"/>
                <img src="<?= D::defaultImage('hdcztvqrcode') ?>" alt="名称" class="qr-code">
            </a>
            <span><?= $channel ? $channel->name : "新蓝云平台" ?></span>
        </div>
        <!-- login form -->
        <div class="content">
            <?= $this->getContent(); ?>
        </div>

        <!-- 版权 -->
        <div class="copyright">
            2015 &copy; 浙江广播电视集团*新蓝网
        </div>

    <!-- 引入共用JS -->
        <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
    </body>
</html>
