<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['切换频道' => Url::get('switching_channel/index')],
    'add' => Url::get(''),
    'html' => '',
]);
?>
<?php $this->partial('partials/error_messages'); ?>
<div class="form form-topcontrol">
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped form-switching-channel">
        <div class="form-body">

            <div class="form-group">
                <label class="control-label col-md-2">选择频道</label>

                <div class="col-md-10">
                    <div class="icheck-inline">
                        <?php
                        if(!empty($data)) {
                            foreach($data as $v) { ?>
                                <label>
                                    <input type="radio"
                                           class="icheck" <?php if($v->channel_id == Session::get('user')->channel_id) {
                                        echo 'checked';
                                    } ?> name="channel_id"
                                           value="<?= $v->channel_id ?>"/><?= $listChannel[$v->channel_id]['name'].D::adminLabel($v); ?>
                                </label>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">当前手机号 </label>

                <div class="col-md-10">
                    <input type="text" value="<?= Session::get('user')->mobile ?>" readonly
                           class="form-control input-large"/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">密码 <span class="font-red">*必填</span></label>

                <div class="col-md-10">
                    <input type="password" name="password" placeholder="密码"
                           class="form-control input-large validate-box"/>
                </div>
            </div>
        </div>

        <div class="form-actions">
            <div class="row">
                <div class="col-md-10 col-md-offset-2 ">
                    <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
                </div>
            </div>
        </div>

    </form>
</div>

<script type="text/javascript">
    $('.form-switching-channel').validate({
        errorElement: 'span',
        errorClass: 'help-block',
        focusInvalid: true,
        rules: {
            password: {
                required: true
            }
        },

        messages: {
            password: {
                required: '密码不能为空'
            }
        },

        invalidHandler: function (event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function (element) {
            $(element)
                .closest('.form-group').addClass('has-error');
        },

        success: function (label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function (error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function (form) {
            form.submit();
        }

    });
</script>