<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form class="form-horizontal form-bordered form-label-stripped" id="form-admin" enctype="multipart/form-data" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加员工</span>
                <div class="btn-group" >
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>
            <div class="form-group">
                <label class="control-label col-md-2">头像 </label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="avatarnail" id="avatarnail" class="file-loading"/>
                        <input type="hidden" name="avatar" value=""/>
                    </div>
                    <span class="help-block">请上传图片大小为120px-120px</span>
                </div>
            </div>
            <script>
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    language: "zh",
                    minImageWidth: 100,
                    minImageHeight: 100,
                    //单位kb
                    maxFileSize: 2048,
                    allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'
                };
                $("#avatarnail").fileinput(thumbnailConfig);
            </script>

            <div class="form-group">
                <label class="control-label col-md-2">姓名 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" placeholder="姓名" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>
            <div class="form-group">
                    <label class="control-label col-md-2">岗位</label>
                <div class="col-md-10">
                    <input name="job_name" type="text" placeholder="请输入岗位名称" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">手机号 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="mobile" type="text" placeholder="手机号" maxlength="11" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

			<div class="form-group" style="display: none">
                <label class="control-label col-md-2">QQ号</label>
                <div class="col-md-10">
                    <input name="qqnum" type="text" placeholder="QQ号" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>
        	<div class="form-group" style="display: none">
            	<label class="control-label col-md-2">微信企业号</label>
                <div class="col-md-10">
                	<input name="vxinhao" type="text"  placeholder="微信企业号" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>
            <div class="form-group" style="display: none">
                <label class="control-label col-md-2">备用手机号</label>
                <div class="col-md-10">
                    <input name="contacts" type="text" placeholder="备用手机号" maxlength="11" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group" style="display: none">
                <label class="control-label col-md-2">密码 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="password" type="text" value="z1234567" onfocus="this.type = 'password'" placeholder="密码" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group" style="display: none">
                <label class="control-label col-md-2">邮箱</label>
                <div class="col-md-10">
                    <input name="email" type="text" placeholder="邮箱" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">部门 <span class="font-red">*必填</span></label>
                    <div class="form-control height-auto">
                    <div class="scroller" style="height:300px;" data-always-visible="1">
                        <input type="hidden" name="dept_id" id="dept_id" >
                        <div id="department_tree" class="tree-demo"></div>
                    </div>
                </div>
            </div>
            
            <div class="form-group" style="display: none">
                    <label class="control-label col-md-2">操作日志</label>
                    <div class="col-md-10">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>姓名</th>
                                    <th>修改内容</th>
                                    <th>修改时间</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            <script type="text/javascript">
                $('.linkage-select').cxSelect({
                    url: '/department/json',
                    selects: ['linkage-one', 'linkage-two', 'linkage-three', 'linkage-four', 'linkage-five', 'linkage-six', 'linkage-seven', 'linkage-eight'],
                    nodata: 'none'
                });
            </script>
        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    jQuery.validator.addMethod("issecurity", function (value, element) {
        var length = value.length;
        var lv = 0;
        if (value.match(/[a-z]/ig)) {
            lv++;
        }
        if (value.match(/[0-9]/ig)) {
            lv++;
        }
        if (value.match(/(.[^a-z0-9])/ig)) {
            lv++;
        }
        if (length < 8 && lv > 0) {
            lv--;
        }
        if (lv < 2) {
            return false;
        }
        else {
            return true;
        }
    }, "密码长度不能少于8位");

    jQuery.validator.addMethod("isChinese", function (value, element) {
        return this.optional(element) || /^[\u4e00-\u9fa5]+$/.test(value);
    });

    jQuery.validator.addMethod("ismobile", function (value, element) {
        var length = value.length;
        var mobile = /^1[3|4|5|7|8|][0-9]{9}$/;
        return this.optional(element) || (length == 11 && mobile.test(value));
    }, "请输入正确的手机号码");

    function issecurity2(value) {
        var length = value.length;
        var lv = -1;
        if (value.match(/[a-z]/ig)) {
            lv++;
        }
        if (value.match(/[0-9]/ig)) {
            lv++;
        }
        if (value.match(/(.[^a-z0-9])/ig)) {
            lv++;
        }
        if (length < 6 && lv > 0) {
            lv--;
        }
        if (lv < 1) {
            return false;
        }
        else {
            return true;
        }
    }
    
    // form stations
    $('#form-admin').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required: true,
                isChinese: true
            },
            mobile: {
                required: true,
                ismobile: true
            },
            contacts: {
                ismobile: true
            },
            email: {
                email: true
            },
            dept_id: {
                required: true
            },
            password: {
                required: true,
                minlength: 8,
                issecurity: true,
                maxlength: 20
            }
        },
        messages: {
            name: {
                required: '姓名不能为空',
                isChinese: '姓名必须为汉字'
            },
            mobile: {
                required: '手机号码不能为空',
                ismobile: '请输入正确的手机号码'
            },
            contacts: {
                ismobile: '请输入正确的手机号码'
            },
            email: {
                email: '请输入正确格式的邮箱'
            },
            duty_id: {
                required: '岗位不能为空'
            },
            dept_id: {
                required: '请选择部门'
            },
            password: {
                required: '请输入密码',
                minlength: '密码长度不能少于8位',
                issecurity: '密码太简单，请由数字,字母或者符号组成',
                maxlength: '密码长度不能超过20位'
            }
        },
        invalidHandler: function (event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },
        highlight: function (element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },
        success: function (label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },
        submitHandler: function (form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });

    $("#duty_id").change(function () {
        $(this).valid();
    });
    function createDepartmentTree() {
        $('#department_tree').jstree({
            //'plugins': ["checkbox", "types"],
            'core': {
                "themes": {
                    "responsive": false
                },
                'data': {
                    'url': function (node) {
                        return '/department/json?id=0';
                    },
                    'data': function (node) {
                        return {'id': node.text};
                    }
                }
            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                }
            }
        })
    }
    function createCategoryTree() {
        $('#category_tree').jstree({
            //'plugins': ["checkbox", "types"],
            'core': {
                "themes": {
                    "responsive": false
                },
                'data': {
                    'url': function (node) {
                        return '/category/json?id=0&terminal=web';
                    },
                    'data': function (node) {
                        return {'id': node.text};
                    }
                }
            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                }
            }
        })
    }

    $(function () {
        createDepartmentTree();
        $('#department_tree')
                // listen for event
                .on('changed.jstree', function (e, data) {
                    var i, j, r = [];
                    var deptIds = "";
                    for (i = 0, j = data.selected.length; i < j; i++) {
                      //  $("#dept_id").val(data.instance.get_node(data.selected[i]).id);
                    	if(i >= 9){
    						alert("最多只能选择10个部门");
    						break;
    					}
                    	if(deptIds!="") deptIds += ",";
                    	deptIds += data.instance.get_node(data.selected[i]).id;
                    }
                    $("#dept_id").val(deptIds);
                })
                // create the instance
                .jstree();
    });
</script>