<style>
    .form-control-static{margin-top: 7px}
    </style>
<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <div class="form-horizontal form-bordered form-label-stripped" id="form-admin" >
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>查看员工 id:<?=$admin->id?></span>
        </div>
        <div class="form-body">
            <input type="hidden" name="id" value="<?=$admin->id?>">
            <input type="hidden" name="channel_id" value="<?=$admin->channel_id?>">

            <div class="form-group">
                <label class="control-label col-md-2">头像</label>
                <div class="col-md-10">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-new thumbnail" style="width: 120px; height: 120px;">
                            <img alt="" src="<?= cdn_url('image',$admin->avatar)?>"/>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">姓名</label>
                <div class="col-md-10">
                    <div class="form-control-static"><?=$admin->name?></div>
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-md-2">手机号</label>
                <div class="col-md-10">
                    <div class="form-control-static"><?=$admin->mobile?></div>
                </div>
            </div>            
            
            <div class="form-group">
                <label class="control-label col-md-2">部门</label>
                <div class="col-md-10">
                    <div class="form-control-static">
                        <?php if(!empty($parents)){
                        	 foreach ($parents as $value) {
								 echo " ".$value;
							} 
                        } ?>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">岗位</label>
                <div class="col-md-10">
                    <div class="form-control-static"><?= $admin->job_name?></div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">角色</label>
                <div class="col-md-10">
                    <div class="form-control-static">
                        <?php
                        if (!empty($role)) {
                            foreach ($role as $v) {
                                echo $v['name'], " ";
                            }
                        }
                        ?>
                        </div>
                </div>
            </div>

        </div>
    </div>
    <!-- END FORM-->
</div>