<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form class="form-horizontal form-bordered form-label-stripped" id="form-admin" enctype="multipart/form-data" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>修改员工</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>
        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>
            <div class="form-group">
                <label class="control-label col-md-2">头像 </label>
                <div class="col-md-10">
                    <div class="input-large image-delete-shutdown">
                        <input type="file" name="avatarnail" id="avatarnail" class="file-loading"/>
                        <input type="hidden" name="avatar" value="<?= $admin->avatar ?>"/>
                    </div>
                    <span class="help-block">请上传图片大小为120px-120px</span>
                </div>
            </div>
            <script>
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    maxFileCount: 1,
                    language: "zh",
                    minImageWidth: 100,
                    minImageHeight: 100,
                    //单位kb
                    maxFileSize: 2048,
                    allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'<?php if($admin->avatar) { ?>,
                    /**
                     * 预加载数据
                     */
                    //预加载删除
                    initialPreviewShowDelete: false,
                    //预加载图片
                    initialPreview: ['<img src="<?= cdn_url('image',$admin->avatar) ?>" class="file-preview-image">'],
                    //预加载图片对应配置
                    initialPreviewConfig: [{caption: "头像"}]
                    <?php } ?>

                };
                $("#avatarnail").fileinput(thumbnailConfig);
            </script>

            <div class="form-group">
                <label class="control-label col-md-2">姓名 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" placeholder="姓名" maxlength="20" value="<?= $admin->name ?>" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">岗位 </label>
                <div class="col-md-10">
                    <input name="job_name" type="text" placeholder="岗位" maxlength="20" value="<?= $admin->job_name ?>" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">手机号 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="mobile" type="text" placeholder="手机号" maxlength="11" value="<?= $admin->mobile ?>" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">密码</label>
                <div class="col-md-10">
                    <input name="password" type="text" onfocus="this.type='password'" placeholder="密码" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group" style="display: none">
                <label class="control-label col-md-2">QQ号</label>
                <div class="col-md-10">
                    <input name="qqnum" type="text" placeholder="QQ号" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group" style="display: none">
                <label class="control-label col-md-2">微信企业号</label>
                <div class="col-md-10">
                    <input name="Vqiyehao" type="text" placeholder="微信企业号" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>
            <?php if($checkAuth('admin/setContacts')) {?>
            <div class="form-group">
                <label class="control-label col-md-2">排序号</label>
                <div class="col-md-10">
                    <input name="sort" type="text"  placeholder="排序号" maxlength="10" value="<?=isset($adminExt->sort) ? $adminExt->sort : 0 ?>" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>
            <?php }?>
           
            <div class="form-group">
                <label class="col-md-2 control-label">部门<span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="scroller" style="height:300px;" data-always-visible="1">
                        <input type="hidden" name="dept_id" id="dept_id" value="<?= !empty($adminExt) ? $adminExt->department : 0 ?>" class="form-control input-large maxlength-handler validate-box" >
                        <div id="department_tree" class="tree-demo">
                            
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">栏目(PC端)</label>
                <div class="col-md-10">
                    <div class="scroller" style="height:300px;" data-always-visible="1">
                        <input type="hidden" name="category_id" id="category_id" value="">
                        <div id="category_tree" class="tree-demo"></div>
                    </div>
                    <br />
                    <label><input type="checkbox" class="icheck" name="greedy_mode_web" value="1" />贪婪模式</label>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-2 control-label">栏目(移动端)</label>
                <div class="col-md-10">
                    <div class="scroller" style="height:300px;" data-always-visible="1">
                        <input type="hidden" name="category_id_app" id="category_id_app" value="">
                        <div id="category_tree_app" class="tree-demo"></div>
                    </div>
                    <br />
                    <label><input type="checkbox" class="icheck" name="greedy_mode_wap" value="1" />贪婪模式</label>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">栏目(手机端)</label>
                <div class="col-md-10">
                    <div class="scroller" style="height:300px;" data-always-visible="1">
                        <input type="hidden" name="category_id_wap" id="category_id_wap" value="">
                        <div id="category_tree_wap" class="tree-demo"></div>
                    </div>
                    <br />
                    <label><input type="checkbox" class="icheck" name="greedy_mode_app" value="1" />贪婪模式</label>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">角色</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <?php
                        if (!empty($role)) {
                            foreach ($role as $v) {
                                $select = in_array($v['id'], $roleids) ? 'checked="checked"' : '';
                                ?>
                                <label><input type="radio" <?= $select ?> class="icheck"  name="roleid" value="<?= $v['id'] ?>"/>
                                    <?= $v['name'] ?>&nbsp;&nbsp;</label>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>            
            <div class="form-group">
                <label class="control-label col-md-2">高级权限配置</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <div class="table-info table-responsive sortable ui-sortable">
                            <?= $this->partial('partials/element', ['authElement' => $assignElement]); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group" style="display: none">
                    <label class="control-label col-md-2">操作日志</label>
                    <div class="col-md-10">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>姓名</th>
                                    <th>修改内容</th>
                                    <th>修改时间</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">

    jQuery.validator.addMethod("ismobile", function(value, element) {
        var length = value.length;
        var mobile = /^1[3|4|5|7|8|][0-9]{9}$/;
        return this.optional(element) || (length == 11 && mobile.test(value));
    }, "请输入正确的手机号码");

    jQuery.validator.addMethod("issecurity", function (value, element) {
        var length = value.length;
		if (length==0){
            return true;
        }
        var lv = 0;
        if (value.match(/[a-z]/ig)) {
            lv++;
        }
        if (value.match(/[0-9]/ig)) {
            lv++;
        }
        if (value.match(/(.[^a-z0-9])/ig)) {
            lv++;
        }
        if (length < 8 && lv > 0) {
            lv--;
        }
        if (lv < 2) {
            return false;
        }
        else {
            return true;
        }
    });
    
    // form stations
    $('#form-admin').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required: true
            },
            mobile: {
                required: true,
                ismobile: true
            },
            dept_id: {
                required: true
            },
            password: {
                minlength: 8,
                issecurity: true,
                maxlength: 20
            }
        },

        messages: {
            name: {
                required: '姓名不能为空'
            },
            mobile: {
                required: '手机号码不能为空',
                ismobile: '请输入正确的手机号码'
            },
            dept_id: {
                required: '请选择部门'
            },
            password: {
                minlength: '密码长度不能少于8位',
                issecurity: '密码太简单，请由数字,字母或者符号组成',
                maxlength: '密码长度不能超过20位'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });

    $("#duty_id").change(function() {
        $(this).valid();
    });

    function createDepartmentTree() {
        $('#department_tree').jstree({
            //'plugins': ["checkbox", "types"],
            'core': {
                "themes": {
                    "responsive": false
                },
                'data' : {
                    'url' : function (node) {
                        return '/department/json?id=<?php echo $admin->id;?>&cs=1';
                    },
                    'data' : function (node) {
                        return { 'id' : node.text };
                    }
                }
            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                }
            }
        })
    }

    function createCategoryTree(terminal) {
        var treestring = "#category_tree";
        if(terminal=="app")treestring = "#category_tree_app";
        if(terminal=="wap")treestring = "#category_tree_wap";
        $(treestring).jstree({
            //'plugins': ["checkbox", "types"],
            'core': {
                "themes": {
                    "responsive": false
                },
                'data': {
                    'url': function (node) {
                        return '/admin/categoryjson?id=<?php echo $admin->id; ?>&terminal='+terminal;
                    },
                    'data': function (node) {
                        return {'id': node.text};
                    }
                }
            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-state-warning icon-lg"
                },
                "file": {
                    "icon": "fa fa-file icon-state-warning icon-lg"
                }
            }
        })
    }

    $(function() {
        createDepartmentTree();
        $('#department_tree')
            // listen for event
            .on('changed.jstree', function (e, data) {
                var i, j, r = [];
                var deptids = "";
                for(i = 0, j = data.selected.length; i < j; i++) {
					if(i >= 9){
						alert("最多只能选择10个部门");
						break;
					}
                	if(deptids != "") deptids += ",";
                	deptids += data.instance.get_node(data.selected[i]).id;
                	
                }
                $("#dept_id").val(deptids);
            })
            // create the instance
            .jstree();

        createCategoryTree("web");
        $('#category_tree')
        // listen for event
            .on('changed.jstree', function (e, data) {
                var i, j, r = [];
                var categoryids = "";
                for (i = 0, j = data.selected.length; i < j; i++) {
                    if(categoryids!="") categoryids += ",";
                    categoryids += data.instance.get_node(data.selected[i]).id;
                }
                $("#category_id").val(categoryids);

            })
            // create the instance
            .jstree();


        createCategoryTree("app");
        $('#category_tree_app')
        // listen for event
            .on('changed.jstree', function (e, data) {
                var i, j, r = [];
                var categoryids = "";
                for (i = 0, j = data.selected.length; i < j; i++) {
                    if(categoryids!="") categoryids += ",";
                    categoryids += data.instance.get_node(data.selected[i]).id;
                }
                $("#category_id_app").val(categoryids);

            })
            // create the instance
            .jstree();
        createCategoryTree("wap");
        $('#category_tree_wap')
        // listen for event
            .on('changed.jstree', function (e, data) {
                var i, j, r = [];
                var categoryids = "";
                for (i = 0, j = data.selected.length; i < j; i++) {
                    if(categoryids!="") categoryids += ",";
                    categoryids += data.instance.get_node(data.selected[i]).id;
                }
                $("#category_id_wap").val(categoryids);

            })
            // create the instance
            .jstree();
    });
</script>