<div class="tab-content">
    <form class="forget-form" action="index" method="post">
        <h3 class="form-title">忘记密码</h3>
        <div class="alert alert-danger display-hide">
            <button class="close" data-close="alert"></button>
            <span>请输入正确的用户名与手机.</span>
        </div>

        <div class="form-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9">手机号</label>
            <div class="input-icon">
                <i class="fa fa-mobile"></i>
                <input class="form-control form-control-solid placeholder-no-fix" type="text" autocomplete="off" placeholder="手机号" name="mobile" data-wordcount="20" maxlength="20"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">验证码</label>
            <div class="input-icon">
                <i class="fa fa-user"></i>
                <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="用户名" name="username"/>
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-success">提交</button>
        </div>

        <div class="login-options">
            <h4>社交帐号登录</h4>
            <div class="social-login">
                <a href="javascript:;" class="btn btn-icon-only btn-circle green">
                    <i class="fa fa-weixin"></i>
                </a>
                <a href="javascript:;" class="btn btn-icon-only btn-circle blue">
                    <i class="fa fa-qq"></i>
                </a>
                <a href="javascript:;" class="btn btn-icon-only btn-circle yellow">
                    <i class="fa fa-weibo"></i>
                </a>
            </div>
        </div>

        <div class="forget-account">
            首次登录/忘记密码？请在这里 <a href="forget" class="forget-password">重置你的密码</a>
        </div>

    </form>
</div>