<?php

/*
 * @filename cms.php 
 * @encoding UTF-8 
 * @author king <347498228@qq.com >
 * @datetime 2015-9-6  16:46:36
 * @version 1.0
  */

return [
    'noauth'=>'对不起，您没有权限，请联系频道管理员',
    'login faild'=>'用户密码错,请联系频道管理员',
    'captcha error'=>'验证码错误',
    'account frozen'=>'账户未激活或禁用,请联系频道管理员',
    'total'=>'总计',
    'success'=>'成功',
    'error'=>'错误',
    'illegal parent'=>'非法层级',
    'exist'=>'已存在',
    'reset success'=>'重置密码成功，请使用新密码登录',

    'user frozen' => '用户已经被冻结',
    
    // 激活重置密码,修改密码，电台，节目单，节目流
    'VericodeFailed'=>'短信验证码错误',
    'PasswordFalse'=>'密码错误',
    'failed'=>'操作失败',

    'wrong format' => "格式错误",

    'invalid request' => '无效的请求',
    'invalid params' => '无效的参数',
    'invalid domain' => '无效的域名',

    // 摇一摇活动
    'Forbid Edit'=>'活动已经开始，禁止修改',
    'Had Data'=>'频道下有活动，禁止修改',


    'not found' => '不存在',
    'wrong username or password' => '用户名或者密码错误',
    'register or reset password' => '注册或者重置密码',
    'invalid mobile' => '手机号码不合法',
    'invalid password' => '密码不合法',
    'empty channel id' => 'channel_id 不能为空',
    'invalid verify code' => '验证码不合法',
    'server internal error' => '服务器内部错误',
    'mobile been resitered' => '手机已经被注册',
    'invalid open_id or access_token' => 'open_id或者access_token不合法',
    'invalid files' => '文件不存在或文件不合法',
    'wrong old password' => '原密码错误',
    'send verify code failed' => '验证码发送失败',
    'user not exists' => '用户不存在',
    'register failed' => '注册出错',
    'password reset failed' => '重置密码出错',
    'repeat password must same' => '密码确认必须与密码保持一致',
    'users.name is too long' => '用户名太长',

    'invalid channel' => '非法入口',
    'please upload valid header image' => '请上传有效的头像图片',
    'please choose upload header image' => '请选择要上传的头像图片',
    'unknown error' => '未知错误',
    'please upload valid ad image' => '请上传有效的广告图片',
    'please choose upload ad image' => '请选择要上传的广告图片',
    'upload file failed' => '上传文件失败',
    'please upload valid poster image' => '请上传有效的封面图片',
    'please upload valid index image' => '请上传有效的索引图片',
    'please choose upload poster image' => '请选择要上传的封面图片',
    'please choose upload index image' => '请选择要上传的索引图片',
    'please upload valid image' => '请上传有效的封面图片',
    'please choose upload image' => '请选择要上传的封面图片',
    'please upload valid excel image' => '请上传有效的excel图片',
    'please choose upload excel image' => '请选择要上传的excel图片',
    'please choose upload csv' => '请选择要上传的csv文件',
    'name' => '姓名',
    'mobile' => '手机号',
    'department' => '部门',
    'post' => '岗位',
    'cztv members info' => '新蓝网员工信息',
    'activity id' => '活动ID',
    'activity name' => '活动名',
    'lottery channel id' => '活动频道ID',
    'channel name' => '频道名',
    'open time' => '开始时间',
    'close time' => '结束时间',
    'people' => '人次',
    'activity statistics' => '活动统计',
    'api request failed' => 'API 请求失败',
    'complete' => '处理完成',
    'real' => '实物',
    'virtual' => '虚拟',
    'please wait for user filling info' => '请等待用户填写联系信息.',
    'shake result' => '摇一摇中奖结果',
    'blind data result' => '交友会资料导出',
    'not enough parameters' => '参数不足',
    'invalid album' => '无效的相册',
    'picture not exists' => '图片不存在',
    'delete data failed' => '数据删除出错',
    'invalid temp file' => '非法的临时文件ID',
    'invalid token' => '非法的 Token',
    'invalid url' => '请求地址出错',
    'allow upload' => '只允许上传 *',
    'file exts' => ' 类型文件.',
    'max file size' => '上传的文件过大.',
    'upload failed' => '上传失败',
    'add success' => '添加成功.',
    'can not find carrier' => '未能找到对应的载体',
    'modify success' => '修改成功.',
    'invalid file, only picture allowed' => '上传的文件不合法，只能传图片文件',
    'invalid file, max file size 5M' => '上传的文件过大，不能大于5M',
	'param is empty' =>'必填参数为空',
    // 媒资发布操作
    'category_id required' => '请先进入具体栏目再进行置顶',
    'can not resort page > 1'=>'只能对第一页数据自定义排序',
    'only top can resort'=>'只有置顶帖才能拖动排序',

    //员工管理前端中文显示
    'search_name'=>'姓名',
    'search_department'=>'部门',
    'search_duty'=>'岗位',

    //部门岗位操作
    'duty_failed' => '岗位被占用无法删除',
    'department_failed' => '部门被占用无法删除',

    'nospecial' => '专辑不能为空',
    //地区
    'country' => '国家',
    'province' => '省、直辖市、自治区',
    'city' => '市',
    'county' => '县、区',
    'town' => '镇、乡、街道',
    'village' => '村',
    'regions name not exit' =>'地区名称不存在',
    'cant low to village' => '级别最低为村',
    'cant delete have son' =>'地区存在下级无法删除',
    'cant push without publish' => '媒资没有发布不能推送',

    //app 
    'error version' => "版本号错误",

    //UGC
    'please choose an anchor' => "请选择一个主播",
    'qua_standard' => "标清",
    'qua_high'=>'高清',
    'qua_supper'=>'超清',
    'work_status_online' => '直播中',
    'work_status_offline'=> '休息下线',
    'stream_status_start'=> '正在推流',
    'stream_status_end' => '推流结束',
    'weixinpay'=>'微信支付',
    'applepay'=>'苹果支付',
    'alipay'=>'支付宝支付',
    'paystatus0'=>'用户未付款',
    'paystatus1'=>'付款成功，等待确认',
    'paystatus2'=>'用户付款中',
    'paystatus3'=>'确认付款成功',

    //弹窗提示
    'dont have picture for popup' => '必须添加图片',
    'have the same popup' => '已存在同一版本弹窗',

    //拍拍浙江美字段后台界面
    'work_picture' => '图片地址',
    'work_intro' => '作品简介',
    'work_number' => '作品编号',
    'r_name' => '姓',
    'r_nickname' => '名',
    'b_year' => '年份',
    'b_month' => '月份',
    'b_date' => '日期',
    'r_title' => '籍贯',
    'r_height' => '身高',
    'r_degree' => '学历',
    'job' => '职业',
    'work_place' => '工作地',
    'merry' => '婚姻状况',
    'weixin' => '微信号',
    'standard' => '择偶标准',
    'introduce' => '自我介绍',
    'pay_number' => '消费额度',
    'birth_year' => '出生年份',
    'birth_month' => '出生月份',
    'birth_day' => '出生日期',
    'height' => '身高',
    'srecord' => '学历',
    'position' => '职务',
    'constellation' => '星座',
    'hhouse' => '住房',
    'isheathy' => '健康状况',
    'body' => '体型',
    'marriage' => '婚姻状况',
    'csex' => '子女性别',
    'cbelong' => '子女归属',
    'home_place' => '户口所在地',
    'home' => '住家地点',
    'intro' => '自我介绍',
    'sage' => '年龄范围',
    'sheight' => '身高范围',
    'ssrecord' => '学历要求',
    'sjob' => '职业要求',
    'spay' => '收入要求',
    'shouse' => '住房要求',
    'schildren' => '子女要求',
    'splace' => '户口要求',
    'smarriage' => '婚姻要求',
    'sother' => '其它要求',
    'sn' => '身份证号',
    'company' => '工作单位',
    'faddress' => '家庭住址',
    'graduate' => '毕业院校',
    'email' => 'E-MALL',
    'qq' => 'QQ',
    'laddress' => '通信地址',
    'hcar' => '备车情况',
    'fmember' => '家庭成员',
    'Unit' => '申报单位',
    'video_scale' => '视频比例',
    'movie_url' => '上传视频地址',
    'movie_id' => '上传视频附件id',
    'daoyan' => '导演',
    'sheying' => '摄影',
    'bianju' => '编剧',
    'nan' => '男主角',
    'nv' => '女主角',
    'secret key repeat' => '口令重复',



];