<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-activity" enctype="multipart/form-data">


        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加封面</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>



        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>

            <div class="form-group">
                <label class="control-label col-md-2">缩率图 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-large image-delete-shutdown">
                        <input type="file" name="thumbnail" id="thumbnail" class="file-loading"/>
                        <input type="hidden" name="file" value=""/>
                    </div>
                    <span class="help-block">请上传图片大小为300px-300px</span>
                </div>
            </div>

        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">
    // form stations
    $('#form-activity').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {

        },
        messages: {

        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>

<script>
    var thumbnailConfig = {
        uploadAsync: false,
        showRemove: false,
        showCaption: false,
        showUpload: false,
        overwriteInitial: true,
        maxFileCount: 1,
        language: "zh",
        minImageWidth: 100,
        minImageHeight: 100,
        //单位kb
        maxFileSize: 2048,
        allowedFileExtensions : ['jpg', 'png', 'gif', 'jpeg'],
        //允许上传 & 允许预览的类型
        allowedFileTypes: ['image'],
        previewFileType: "image",
        browseLabel: '浏览 ...'
    };
    $("#thumbnail").fileinput(thumbnailConfig);
</script>