
<style>
  ::-webkit-scrollbar{
        width: 0px;
    };
</style>
<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-activity" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加活动</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>

            <div class="form-group">
                <label class="control-label col-md-2">索引图 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="thumbnail" id="thumbnail" class="file-loading"/>
                        <input type="hidden" name="file" value=""/>
                    </div>
                    <span class="help-block">请上传图片大小为300px-300px</span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动标题 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="title" placeholder="活动标题" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动副标题 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="sub_title" placeholder="活动副标题" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="name" placeholder="活动名称" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动地点 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="location" placeholder="活动地点" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动时间 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-group input-large date-picker input-daterange" data-date="" data-date-format="yyyy-mm-dd">
                        <input type="text" name="start_time" placeholder="开始时间" value="<?= date('Y-m-d')?>" class="form-control"/>
                        <span class="input-group-addon">到</span>
                        <input type="text" name="end_time" placeholder="结束时间" value="<?= date('Y-m-d')?>" class="form-control"/>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动简介 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <textarea placeholder="活动简介" rows="3" name="intro" maxlength="200" class="form-control maxlength-handler validate-box"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动详情 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <textarea placeholder="活动详情" rows="6" name="content" maxlength="200" class="form-control maxlength-handler validate-box"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">短信模板参数(json格式保存) </label>
                <div class="col-md-10">
                    <textarea placeholder="短信模板参数" name="message_template_params" rows="6" maxlength="255" class="form-control maxlength-handler"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">附加字段1 </label>
                <div class="col-md-10">
                    <textarea placeholder="附加字段1" name="params1" rows="6" maxlength="255" class="form-control maxlength-handler"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">附加字段2 </label>
                <div class="col-md-10">
                    <textarea placeholder="附加字段2" name="params2" rows="6" class="form-control"></textarea>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    // form stations
    $('#form-activity').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            title: {
                required: true
            },
            sub_title: {
                required: true
            },
            name: {
                required: true
            },
            location: {
                required: true
            },
            intro: {
                required: true
            },
            content: {
                required: true
            }
        },

        messages: {
            title: {
                required: '活动标题不能为空'
            },
            sub_title: {
                required: '活动副标题不能为空'
            },
            name: {
                required: '活动名称不能为空'
            },
            location: {
                required: '活动地点不能为空'
            },
            intro: {
                required: '活动简介不能为空'
            },
            content: {
                required: '活动详情不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>

<script>
    var thumbnailConfig = {
        uploadAsync: false,
        showRemove: false,
        showCaption: false,
        showUpload: false,
        overwriteInitial: true,
        minFileCount: 1,
        maxFileCount: 1,
        language: "zh",
        minImageWidth: 100,
        minImageHeight: 100,
        //单位kb
        maxFileSize: 2048,
        allowedFileExtensions : ['jpg', 'png', 'gif', 'jpeg'],
        //允许上传 & 允许预览的类型
        allowedFileTypes: ['image'],
        previewFileType: "image",
        /**
         * 预加载数据
         */
        //预加载删除
        initialPreviewShowDelete: false,
        //预加载图片
        //initialPreview: ['<img src="" class="file-preview-image">'],
        //预加载图片对应配置
        initialPreviewConfig: [{caption: "索引图"}]
    };
    $("#thumbnail").fileinput(thumbnailConfig);
</script>