<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['活动列表' => Url::get('activity/index')],
    'add'=> Url::get('activity/create'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>活动名称</th>
                <th>活动地点</th>
                <th>活动时间</th>
                <th>报名人数</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($data->models as $model) :
            ?>
            <tr>
                <td class="checkbox-middle">
                    <input type="checkbox" class="checkboxes" name="id" value="<?php echo $model->activity->id; ?>"/>
                </td>
                <td>
                    <img class="small-img" src="<?=cdn_url('image',$model->data->thumb)?>"/>
                    <span class="name-center">
                        <?= $model->data->title;?>
                    </span>
                </td>
                <td><?php echo $model->activity->location?></td>
                <td><?php echo date('20y-m-d',$model->activity->start_time);?> 至 <?php echo date('20y-m-d',$model->activity->end_time);?></td>
                <td><?=$model->activity->singup_count?></td>
                <td><?php if(time()>$model->activity->start_time && time()<$model->activity->end_time){echo '进行中';}elseif(time()<$model->activity->start_time){echo '未开始';}elseif(time()>$model->activity->end_time){echo '已结束';}?></td>
                <td>
                    <div class="btn-group btn-group-xs btn-group-solid">
                        <button type="button" class="btn green edit-content tooltips" data-url="/activity/modify/?id=<?php echo $model->activity->id; ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                        <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/activity/delete?id=<?= $model->activity->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                        <button type="button" class="btn blue tooltips href-location" data-url="/activity/listsignup/?id=<?php echo $model->activity->id; ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="查看报名表"><i class="fa fa-users"></i></button>
                        <button type="button" class="btn red edit-content tooltips" data-url="/activity/addVedioDgs/?id=<?php echo $model->activity->id; ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="添加视频"><i class="fa fa-video-camera"></i></button>
                        <button type="button" class="btn blue tooltips href-location" data-url="/activity/listvedios/?id=<?php echo $model->activity->id; ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="视频列表"><i class="fa fa-list"></i></button>
                        <button type="button" class="btn red tooltips href-location" data-url="/activity/listImages/?id=<?php echo $model->activity->id; ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="图片列表"><i class="fa fa-image"></i></button>
                        <button type="button" class="btn blue tooltips href-location" data-url="/activity/listVideo/?id=<?php echo $model->activity->id; ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="视频列表"><i class="fa fa-list"></i></button>
                    </div>
                </td>
            </tr>
        <?php endforeach;?>
        <?php if(count($data->models) == 0) { ?>
            <tr class="sortable-tr"><td colspan="8">未能找到相关数据</td></tr>
        <?php } ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button>
                </div>
            </div>

            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            5:{sorter:false},
            6:{sorter:false}
        }
    });
</script>