<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-site" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>修改站点</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <input type="hidden" name="id" value="<?= $piple->id ?>"/>
            <div class="form-group">
                <label class="control-label col-md-2">短信通道名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" value="<?= $piple->name ?>" name="name" placeholder="短信通道名称" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">通道剩余条数 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" value="<?= $piple->rest ?>" name="rest" placeholder="通道剩余条数" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">通道报警条数 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" value="<?= $piple->alarm ?>" name="alarm" placeholder="通道报警条数" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">状态</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label><input type="radio" class="icheck" name="status" value="0" <?= $piple->status == '0'?'checked':'' ?> />禁用</label>
                        <label><input type="radio" class="icheck" name="status" value="1" <?= $piple->status == '1'?'checked':'' ?> />开启</label>
                    </div>
                </div>
            </div>

        </div>
    </form>
    <!-- END FORM-->
</div>






<script type="text/javascript">
    // form stations
    $('#form-site').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required: true,
                minlength: 2
            },
            reset: {
                required: true
            }
        },

        messages: {
            name: {
                required : '通道名称不能为空',
                minlength: '通道名称至少为2个字符'
            },
            domain: {
                required: '剩余短信数',
            }
            alarm:{
                required: '短信报警数不能为空',
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            if(element.is(':radio') || element.is(':checkbox')) {
                error.appendTo(element.parents(".icheck-inline"));
            }
            else {
                error.insertAfter(element.closest('.validate-box'));
            }
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>