<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['cdn分发日志' => Url::get('cnd/loglist')],
    // 'add'=>Url::get("advert_space/add")
]);
?>

<?php $this->partial('partials/error_messages');?>
<form method="post" action="/advert_space/createjs" name="myform">
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>名称</th>
                <th>分发CDN</th>
                <th>操作状态</th>
                <th>文件类型</th>
                <th>开始时间</th>
                <th>结束时间</th>
                <th>操作员</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value="" name="" id="spacecode" />
                        </td>
                        <td>跑男第四季第4期</td>
                        <td>云帆</td>
                        <td>下发：<span class="font-red">分发中</span></td>
                        <td>视频</td>
                        <td>2016-5-10 17:28:44</td>
                        <td>2016-5-10 17:28:50</td>
                        <td>张三(2016-5-11 10:01:37)</td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                
                                <button type="button" class="btn blue edit-content tooltips" 
                                        data-url="<?= Url::get('cdn/priority', ['id' => 1]) ?>" 
                                        data-container="body" 
                                        data-placement="top" 
                                        data-trigger="hover" 
                                        data-html="true"
                                        data-original-title="优先级" 
                                ><i class="fa fa-bar-chart-o"></i></button>

                                <button type="button" class="btn green edit-content tooltips" data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="详情"><i class="fa fa-eye"></i></button>
                                
                                <button type="button" class="btn yellow edit-content tooltips" data-url="" data-trigger="hover" data-container="body" data-placement="top" data-html="true" data-original-title="重发"><i class="fa fa-link"></i></button>

                                <button type="button" class="btn red tooltips" data-url="" onclick="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            </div>
                        </td>
                    </tr>
               
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
             <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="submit" class="btn btn-default" name="submit">生成js</button>
                </div>
            </div>
            <ul class="pagination"><li><a title="上页" href="javascript:void(0)"><i class="fa fa-angle-left"></i></a></li><li class="active"><a title="第 1 页 " href="javascript:void(0)">1</a></li><li><a title="下页" href="javascript:void(0)"><i class="fa fa-angle-right"></i></a></li></ul>  
            <div class="pagination-info">100</div>
        </div>
    </div>
</div>
</form>
<script type="text/javascript">

    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            4:{sorter:false},
            6:{sorter:false}
        }
    });
</script>