<?php
Input::init(Request::get(),[]);
if(!isset($mess)){
    $mess=array();
}
?>
<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form role="form" method="get" class="form-horizontal form-bordered form-label-stripped" action="/comment/search">
            <div class="form-body">
                <div class="form-group ">
                    <label class="control-label col-md-2">搜索</label>
                    <div class="col-md-10">
                            <div class="screening-order">
                                <input type="text" class="form-control input-small  margin-right-10" placeholder="搜索评论" name="comment" />
                                <input type="text" class="form-control input-small  margin-right-10" placeholder="搜索昵称" name="nickname" />
                                <input type="text" class="form-control input-small  margin-right-10" placeholder="搜索用户ID" name="user_id" />
                                <input type="text" class="form-control input-small  margin-right-10" placeholder="搜索视频ID" name="data_id" />
                                <input type="submit" class="btn blue breadcrumbbtn" value="搜索" />
                            </div>
                    </div>
                </div>
            </div>

            <div class="form-group screening-box">
                <label class="control-label col-md-2">开始时间</label>

                <div class="col-md-10">

                    <div class="input-group date form_datetime input-large validate-box">
                        <input type="text" name="created_at_from" size="18" readonly value="<?=Input::fetch('created_at_from')?>" class="form-control">
						<span class="input-group-btn">
                            <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
						</span>

                    </div>
                </div>

            </div>

            <div class="form-group screening-box">
                <label class="control-label col-md-2">结束时间</label>

                <div class="col-md-10">

                    <div class="input-group date form_datetime input-large validate-box">

                        <input type="text" name="created_at_to" size="18" readonly value="<?=Input::fetch('created_at_to')?>" class="form-control">
						<span class="input-group-btn">
                            <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
						</span>
                    </div>
                </div>

            </div>

        </form>
        <!-- END FORM-->
    </div>
    <?php if($mess){?>
        <div class="search-result">
            <dt><a href="/comment/index">所有结果</a></dt> >
            <dd>
                <?php if($mess['name']):?>
                   <span><?=$mess['name']?></span>
                <?php endif;?>

                <?php if($mess['content']):?>
                    <span><?=$mess['content']?></span>
                <?php endif;?>

                <?php if($mess['created_at_from']):?>
                    <span><?=$mess['created_at_from']?></span>
                <?php endif;?>

                <?php if($mess['created_at_to']):?>
                    <span><?=$mess['created_at_to']?></span>
                <?php endif;?>

                <a href='/comment/index'><i class="fa fa-times"></i></a>
            </dd>
        </div>
        <?php } ?>
</div>

