<?php
$this->partial("partials/breadcrumb", [
    'urls'=>['系统版本'=>Url::get('version/index')],
    'add'=>Url::get("version/add")
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>版本</th>
                <th>更新内容</th>
                <th>更新时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (isset($data->models) && !empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle sortr-handle">
                            <input type="checkbox" class="checkboxes" value=""/>
                        </td>
                        <td><?= $v->name ?></td>
                        <td><?= $v->content ?></td>
                        <td><?= date('Y-m-d',$v->updated_at) ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                    <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('version/edit',['id'=>$v->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                    <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/version/delete?id=<?= $v->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <?= $data->pagination->render();?>
                <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        1:{sorter:false},
        2:{sorter:false},
        4:{sorter:false}
    }
});
</script>