<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['短信模板' => Url::get('sms_sence/index')],
    'add' => Url::get('sms_sence/add'),
]);
?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>ID</th>
            <th>场景名称</th>
            <th>创建时间</th>
            <th>短信模板</th>
            <th>首选通道</th>
            <th>备选通道</th>
            <th>场景宿主</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($models = $data->models)) :
            foreach ($models as $v) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td>
                        <?= $v->id ?>
                    </td>
                    <td><?= $v->name ?></td>
                    <td><?= date('Y-m-d', $v->create_at) ?></td>
                    <td>
                        <?= $templatelist[$v->template_id] ?></td>
                    </td>
                    <td>
                        <?= $piple_list[$v->major_piple] ?>
                    </td>
                    <td>
                        <?= $piple_list[$v->minor_piple] ?>
                    </td>
                    <td>
                        <?= $v->terminal ?>
                    </td>
                    <td>
                        <?php
                        switch ($v->status) {
                            case 1:
                                echo '打开';
                                break;
                            case 0:
                                echo '关闭';
                                break;
                        }
                        ?>
                    </td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn green edit-content tooltips"
                                    data-url="<?= Url::get('sms_sence/edit', ['id' => $v->id]) ?>" data-container="body"
                                    data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑">
                                <i class="fa fa-edit"></i></button>
                            <button type="button" class="btn green edit-content tooltips"
                                    data-url="<?= Url::get('sms_sence/audit', ['id' => $v->id]) ?>"
                                    data-container="body" data-placement="top" data-trigger="hover" data-html="true"
                                    data-original-title="审核"><i class="fa fa-edit"></i></button>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选
                    </button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">
                        取消
                    </button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">
                        反选
                    </button>
                    <button type="button" class="btn btn-default">删除</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers: {
            0: {sorter: false},
            7: {sorter: false}
        }
    });
</script>