<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['关键词列表' => Url::get('wxkeyword/index')],
    'add'=> Url::get('wxkeyword/create'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>微信关键词</th>
            <th>关键词类型</th>
            <th>关键词描述</th>
            <th>关键词代码</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($keyword->models as $model): ?>
            <tr>
                <td class="checkbox-middle">
                    <input type="checkbox" class="checkboxes" value="<?= $model->id?>"/>
                </td>
                <td><?= $model->wx_keyword;?></td>
                <td><?php switch($model->callback_type){
                        case 1:echo '普通回复';break;
                        case 2:echo '兑换码回复';break;
                        case 3:echo '应援回复';break;
                        case 4:echo '用户关注回复';break;
                        default:echo '';
                }?></td>
                <td><?= $model->title;?></td>
                <td><?= $model->keyword_code;?></td>
                <td>
                    <div class="btn-group btn-group-xs btn-group-solid">
                        <button type="button" class="btn green edit-content tooltips" data-url="<?= Url::get('wxkeyword/modify', ['id' => $model->id]);?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                        <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="<?= Url::get('wxkeyword/delete', ['id' => $model->id]);?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        <?php if(count($keyword->models) == 0) { ?>
            <tr><td colspan="6">未能找到相关数据</td></tr>
        <?php } ?>
        <?php ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $keyword->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $keyword->count ?></div>

        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        5:{sorter:false}
    }
});
</script>
