<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['任务列表' => Url::get('task/index')],
    'add'=> Url::get('task/new'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>任务名称</th>
                <th>截止</th>
                <th>指派给</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $models = $data->models;
            if (!empty($models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value="1"/>
                        </td>
                        <td><?= $v->name ?></td>
                        <td><?=Tasks::time2text($v->end)?></td>
                        <td><?=($v->receiver)?$v->getReceiver()->name:$v->getCreator()->name?></td>
                        <td><?=$v->getProgress()?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn purple edit-content tooltips" data-url="/task/detail?id=<?= $v->id ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="查看"><i class="fa fa-eye"></i></button>
                                <button type="button" class="btn green edit-content tooltips" data-url="/task/edit?id=<?= $v->id ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button>
                    <button type="button" class="btn btn-default" href="#check-config" data-toggle="modal">通过审核</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        6:{sorter:false}
    }
});
</script>