<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form id="form-task" class="form-horizontal form-bordered form-label-stripped" method="post" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加任务</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>
        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <input type="hidden" name="father" value="0" />
            <div class="form-group">
                <label class="control-label col-md-2">任务名称</label>
                <div class="col-md-10">
                    <textarea id="" name="name" placeholder="任务名称" rows="3" maxlength="104" class="form-control maxlength-handler"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">开始时间</label>
                <div class="col-md-10">
                    <div class="input-group date form_datetime input-medium">
                        <input name="start" id="start_time" type="text" placeholder="开始时间" size="18" value="<?=date('Y-n-d H:i')?>" class="form-control">
                        <span class="input-group-btn">
                        <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
                        </span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">结束时间</label>
                <div class="col-md-10">
                    <div class="input-group date form_datetime input-medium">
                        <input name="end" id="end_time" type="text" placeholder="结束时间" size="18" value="<?=date("Y-n-d H:i", time() + 86400)?>" class="form-control">
                        <span class="input-group-btn">
                        <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
                        </span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">任务详情</label>
                <div class="col-md-10">
                    <script id="container" name="content" type="text/plain"></script>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">任务指派</label>
                <div class="col-md-10">
                    <select class="form-control select2_category input-medium" name="receiver">
                        <?php
                            if (!empty($admins)) :
                                foreach($admins->models as $v):
                                    ?>
                            <option value="<?=$v->admin->id?>"><?=$v->admin->name?></option>
                        <?php
                                endforeach;
                            endif;
                            ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">附件上传 </label>
                <div class="col-md-10">
                    <input type="file" name="attachfile" id="attachfile" />
                </div>
            </div>
        </div>
    </form>    
    <!-- END FORM-->
</div>

<!-- 编辑器配置文件 -->
<script type="text/javascript" src="/assets/global/plugins/ueditor/ueditor.config.js"></script>
<!-- 编辑器源码文件 -->
<script type="text/javascript" src="/assets/global/plugins/ueditor/ueditor.all.js"></script>

<script type="text/javascript">

    jQuery.validator.addMethod("bigendtime", function (value, element) {
        var flag = true;
        var start_time = $('#start_time').val();  
        var startdate = new Date(start_time.replace(/-/g, "/")).getTime();
        var end_time = $('#end_time').val();
        var enddate = new Date(end_time.replace(/-/g, "/")).getTime();
        if(enddate <= startdate)  flag = false;
        return this.optional(element) || (flag);
    }, "结束时间必须大于开始时间");
   
    $(function() {
        ue = UE.getEditor('container',{});
        ue.ready(function() {
            //设置编辑器的内容
            ue.setContent('');
        });
    });
    // form lotteries group
</script>
