<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>奖号</th>
                <th>获奖奖品</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <?php if (isset($data->models) && !empty($models = $data->models)) :
            foreach($models as $ticket):?>
            <tr>
                <td><?= $ticket->number?></td>
                <td><?= $ticket->name?></td>
                <td class="<?= ($ticket->status)?'font-green':'font-red'?>"><?= ($ticket->status)?'已领奖':'未领奖'?></td>
                <td>
                    <div class="btn-group btn-group-xs btn-group-solid">
                        <button type="button" class="btn purple tooltips" onclick="reward_confirm(this)" data-url="/ticket/getreward?id=<?=$ticket->id?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="领奖"><i class="fa fa-database"></i></button>
                        <button type="button" class="btn yellow tooltips" onclick="reward_confirm(this)" data-url="/ticket/returnreward?id=<?=$ticket->id?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="取消领奖"><i class="fa fa-database"></i></button>
                    </div>
                </td>
            </tr>
        <?php endforeach;endif;?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <?= $data->pagination->render();?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
            <div class="pagination-info">总人数 <?=$data->count?> 人</div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            2:{sorter:false}
        }
    });
</script>