<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['兑换码列表' => Url::get('wxbirthdaysupport/index')],
//    'add'=> Url::get('wxbirthdaysupport/create'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>用户微信id</th>
            <th>关键词id</th>
            <th>应援关键词</th>
            <th>应援序号</th>
            <th>应援时间</th>
            <th>消息id</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($birthday->models as $model): ?>
            <tr>
                <td class="checkbox-middle">
                    <input type="checkbox" class="checkboxes" value="<?= $model->id?>"/>
                </td>
                <td><?= $model->open_id	;?></td>
                <td><?= $model->keyword_id ;?></td>
                <td><?= $model->keyword_name ;?></td>
                <td><?= $model->support_num ;?></td>
                <td><?= date('Y年m月d日H时i分s秒',$model->support_time) ;?></td>
                <td><?= $model->msg_id;?></td>
                <td>
                    <div class="btn-group btn-group-xs btn-group-solid">

                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        <?php if(count($birthday->models) == 0) { ?>
            <tr><td colspan="6">未能找到相关数据</td></tr>
        <?php } ?>
        <?php ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $birthday->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $birthday->count ?></div>

        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        5:{sorter:false}
    }
});
</script>
