<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form action="#" class="form-horizontal form-bordered form-label-stripped">
            <div class="form-actions screening-box">
                <div class="row">
                    <div class="col-md-offset-2 col-md-11">
                        <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
                        <button type="button" class="btn default">重置</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>