<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action=" " method="post" class="form-horizontal form-bordered form-label-stripped form-channel" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加频道</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>

            <div class="form-group">
                <label class="control-label col-md-2">会场名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="location" placeholder="活动地点" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">会场奖品</label>
                <div class="col-md-10" id="sorttable">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>奖品名称</th>
                                <th>奖品等级</th>
                                <th>数量</th>
                                <th>剩余数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <img class="small-img" src="/assets/admin/layout/cztv_img/prizes.png" />
                                    <span class="name-center">Iphone6</span>
                                </td>
                                <td>二等级</td>
                                <td>110</td>
                                <td>80</td>
                                <td>
                                    <div class="btn-group btn-group-xs btn-group-solid">
                                        <button type="button" class="btn green edit-content tooltips" data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                        <button type="button" class="btn red tooltips" data-url= "" onclick="show_confirm(this)"  data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                                    </div>
                                </td>
                            </tr>
                                    
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">会场索引图</label>
                <div class="col-md-10" id="sorttable">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>名称</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <img class="small-img" src="/assets/admin/layout/cztv_img/prizes.png" />
                                    <span class="name-center">钱江频道</span>
                                </td>
                                <td>
                                    <div class="btn-group btn-group-xs btn-group-solid">
                                        <button type="button" class="btn green edit-content tooltips" data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                        <button type="button" class="btn red  tooltips" data-url= "" onclick="show_confirm(this)"  data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                                    </div>
                                </td>
                            </tr>
                                    
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">活动背景图<span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-new thumbnail" style="width: 200px; height: 160px;">
                            <img   alt=""/>
                        </div>
                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 160px;">
                        </div>
                        <div>
                            <span class="btn blue btn-file">
                                <span class="fileinput-new">选择图片</span>
                                <span class="fileinput-exists">更换图片</span>
                                <input type="file" name="file">
                            </span>
                            <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput">删除图片</a>
                        </div>
                    </div>
                    <div class="clearfix margin-top-10">
                        <span class="label label-danger">提示</span> 活动页面的背景图 大小640x800
                    </div>
                </div>
            </div>


            <div class="form-group">
                <label class="control-label col-md-2">摇奖次数 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="location" placeholder="摇奖次数" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">预计人数 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="location" placeholder="预计人数" maxlength="20" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">开始时间 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-group date form_datetime input-large validate-box">
                        <input type="text" name="start_time" size="18" readonly class="form-control">
                        <span class="input-group-btn">
                            <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
                        </span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">结束时间 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-group date form_datetime input-large validate-box">
                        <input type="text" name="end_time" size="18" readonly class="form-control">
                        <span class="input-group-btn">
                            <button class="btn default date-set" type="button"><i class="fa fa-calendar"></i></button>
                        </span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">会场状态</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label><input type="radio" class="icheck" name="no_comment" value="1"/>开启</label>
                        <label><input type="radio" class="icheck" name="no_comment" value="1"/>关闭</label>
                    </div>
                </div>
            </div>

            <!--
            <div class="form-group">
                <label class="control-label col-md-2">操作日志</label>
                <div class="col-md-10">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>姓名</th>
                                <th>修改内容</th>
                                <th>修改时间</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>吴哈哈</td>
                                <td>修改内容0</td>
                                <td>2015-12-3 10.50</td>
                                
                            </tr>
                                    
                        </tbody>
                    </table>
                </div>
            </div>
            -->

        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    // form stations
    $('.form-channel').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {

            name: {
                required : true
            },
            number: {
                required : true,
                number:true
            },
            time:{
                required:true
            },
            status:{
                required:true
            }
        },

        messages: {
            name: {
                required : '名字不能为空'
            },
            number: {
                required : '编号不能为空',
                number:'请填写数字'
            },

            time:{
                required:'时间不能为空'
            },
            status:{
                required:'状态不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>