<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['会场列表' => Url::get('meeting_place/index')],
    'add'=> Url::get('meeting_place/create'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>会场名称</th>
                <th>会场状态</th>
                <th>时间起止</th>
                <th>预计人数</th>
                <th>次数限制</th>
                <th>所属活动</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="checkbox-middle">
                    <input type="checkbox" class="checkboxes" name="id" value=""/>
                </td>
                <td>
                    <img class="small-img" src=""/>
                    <span class="name-center">第一场</span>
                </td>
                <td>进行中</td>
                <td>2015-12-5 9:00 至 2015-12-9 9:00</td>
                <td>2000</td>
                <td>20</td>
                <td>电视观众节</td>
                <td>
                    <div class="btn-group btn-group-xs btn-group-solid">
                        <button type="button" class="btn green edit-content tooltips" data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                        <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                    </div>
                </td>
            </tr>

            <tr>
                <td class="checkbox-middle">
                    <input type="checkbox" class="checkboxes" name="id" value=""/>
                </td>
                <td>
                    <img class="small-img" src=""/>
                    <span class="name-center">第一场</span>
                </td>
                <td><span class="font-red">未开始</span></td>
                <td>2015-12-5 9:00 至 2015-12-9 9:00</td>
                <td>2000</td>
                <td>20</td>
                <td>电视观众节</td>
                <td>
                    <div class="btn-group btn-group-xs btn-group-solid">
                        <button type="button" class="btn green edit-content tooltips" data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                        <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>

        </div>
    </div>
</div>
<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            3:{sorter:false},
            4:{sorter:false},
            5:{sorter:false},
            6:{sorter:false}
        }
    });
</script>