<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['队列通知' => Url::get('queues/sobeylist')],
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>视频ID</th>
            <th>供应源分类</th>
            <th>视频标题</th>
            <th>推送时间</th>
            <th>状态</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($parcel->models as $model): ?>
            <tr>
                <td class="checkbox-middle">
                    <input type="checkbox" class="checkboxes" value="<?= $model->id ?>"/>
                </td>
                <td><?= $model->source_id ?></td>
                <td><?= $model->supply_category_id ?></td>
                <td><?php
                    $content = unserialize($model->origin_content);
                    echo isset($content['video_title'])? $content['video_title']: '';
                    ?></td>
                <td><?= date('Y-m-d H:i:s', $model->updated_at); ?></td>
                <td><?= $model->status == 1? '成功': '等待队列'; ?></td>
            </tr>
        <?php endforeach ?>
        <?php if(count($parcel->models) == 0) { ?>
            <tr class="sortable-tr">
                <td colspan="11">未能找到相关数据</td>
            </tr>
        <?php } ?>
        <?php ?>
        </tbody>
    </table>
    <div class="paginationnav">
        <div class="paginationnav-main">
            <!-- <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sortable-table .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sortable-table .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sortable-table .checkboxes">反选</button>
                </div>
            </div> -->
            <?= $parcel->pagination->render(); ?>
            <div class="pagination-info">总计 <?= $parcel->count ?> 条</div>
        </div>
    </div>
</div>