<?php
$this->partial("partials/breadcrumb", [
    'urls'=>['广告列表'=>Url::get('advert_space/index'),$spacename => Url::get('advert/list?spaceid='.$spaceid)],
    'add'=>Url::get("advert/add?spaceid=".$spaceid)
]);
?>
<form method="post" action="/advert/listorder" name="myform">
<input type="hidden" name="spaceid" value="<?= $spaceid ?>">
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>排序</th>
                <th>广告标题</th>
                <th>广告类型</th>
                <th>所属广告位</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (isset($data->models) && !empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value=""/>
                        </td>
                        <td>
                            <input id="listorder" type="text" class="" value="<?= $v->advert->listorder ?>" name="listorder[<?= $v->advert->id ?>]" size="5"/>
                        </td>
                        <td><?= $v->advert->name ?></td>
                        <td><?= Advert::getTypeName($v->advert->type) ?> </td>
                        <td><?= $v->name ?></td>
                        <td><?php if($v->advert->status == 0){ ?><span class="font-red">未审核</span> <?php } else echo "审核"; ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('advert/edit',['id'=>$v->advert->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <button type="button" class="btn tooltips <?= $v->advert->status == 1 ? 'red': 'blue' ?>"
                                    data-url="<?= ($v->advert->status)?Url::get('advert/lock', ['id' => $v->advert->id]):Url::get('advert/unlock', ['id' => $v->advert->id]) ?>"
                                    data-container="body" data-placement="top" data-trigger="hover" data-html="true"
                                    data-original-title="<?= $v->advert->status == 0 ? '审核': '取消审核' ?>" onclick="show_confirm(this)"><i
                                    class="fa <?= $v->advert->status == 1 ? 'fa-ban': 'fa-check' ?>"></i>
                                </button>
                                <button type="button" class="btn red tooltips" data-url="<?=Url::get('advert/delete',['id'=>$v->advert->id])?>" onclick="show_confirm(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="submit" class="btn btn-default" name="submit">排序</button>
                   <!-- <button type="button" class="btn btn-default">删除</button>-->
                </div>
            </div>
            <?= $data->pagination->render();?>
                <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
</form>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        1:{sorter:false},
        6:{sorter:false}
    }
});
</script>