
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <!-- <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" /> -->
  <meta name="renderer" content="webkit">
  <title>中国蓝TV - 找回密码</title>
  <meta name="Keywords" content="明星,娱乐,视频,新闻,网络电视,时尚门户,电视直播,浙江卫视,影视,浙江广电,电视台,中国蓝"/>
  <meta name="Description" content="浙江广播电视集团新媒体，整合浙江卫视在内的18个广播电视频道的优势资源， 打造“浙江第一视频门户”，为网民提供互联网、通信网、电视网三网融合、无缝衔接的新媒体优质服务。"/>
  <link rel="shortcut icon" href="http://tv.cztv.com/cztv/user/favicon.ico" />
  <!-- <link type="text/css" rel="stylesheet" href="http://tv.cztv.com/cztv/user/core.css"/> -->
  <link type="text/css" rel="stylesheet" href="http://tv.cztv.com/cztv/user/style.css" />
  <link href="http://tv.cztv.com/cztv/user/style_reset.css" rel="stylesheet" type="text/css" />
<!--   
   <script>
	document.domain = 'cztv.com'; </script> -->
  <script src='http://tv.cztv.com/bluetv/user/core.js'></script>
  <script src='http://tv.cztv.com/bluetv/user/d2017425.js'></script>
	<script src="http://tv.cztv.com/bluetv/user/md5.js" type="text/javascript"></script>
  <!-- <script src='http://tv.cztv.com/bluetv/user/w2016.js'></script> -->
  <script src='http://tv.cztv.com/bluetv/user/w2017420.js'></script>
  <script type="text/javascript" src="http://tv.cztv.com/bluetv/user/action_reset.js?v=1.1"></script>

</head>
<!-- <body id="autoBody"> -->
<body>
<!-- forget/S-->
<div class="ui-warp">
	<div class="ui-comwidth ui-cf">		
		<div class="ui-forget ui-cf" id="ui-forget">
			<!-- <div class="ui-fl">
				<ul class="ui-tabs ui-cf">
					<li class="active"><i class="ui-icon-phone"></i><span>通过手机找回</span><em></em></li>
                    <li class="email"><i class="ui-icon-email"></i><span>通过邮箱找回</span><em></em></li>
				</ul>
			</div> -->
			<!-- nav start -->
			<div class="reset_nav re">
				<img class="reset_nav1 active" src="http://tv.cztv.com/cztv/user/topic/reset_phone1.png" alt=""/>
				<img class="reset_nav2" src="http://tv.cztv.com/cztv/user/topic/reset_mail1.png" alt=""/>
			</div>
			<!-- nav end -->
	
			<div class="ui-fr">
            				<div class="ui-forget-con ui-cf active">
            			<!--	<form action="" method="post">-->
            						<div class="ui-form ui-form-forget ui-cf">
            						<!--<p class="ui-alert" id='denglualert3'><i class="ui-icon-alert-info"></i><span></span></p>-->
            							<div class="ui-form-group ui-cf mt10 ui-cf pos-re">
            								<div class="ui-col-12">
            									<input type="text" name="" class="ui-form-input" value=""id='mobile' placeholder="手机号码" />
            									<p class="ui-alert left-for-confirm" id='denglualert3'>
            										<span class="arrow"></span>
            										<i class="ui-icon-alert-info"></i>
            										<span id='mobileMeg'></span>
            									</p>
            								</div>
            							</div>
            							<!--<p class="ui-alert" id='denglualert4'><i class="ui-icon-alert-info"></i><span></span></p>-->
            							<div class="ui-form-group ui-cf mt10 ui-cf pos-re">
            								<div class="ui-col-9">
            									<input type="text" name="" class="ui-form-input ui-form-input-sm" value="" id='code' placeholder="验证码" />
            									<p class="ui-alert left-for-confirm" id='denglualert4'>
            										<span class="arrow"></span>
            										<i class="ui-icon-alert-info"></i>
            										<span id='codeMeg'></span>
            									</p>
            								</div>
            								<div class="ui-col-3" id="mobilecode" ><a href="javascript:;" class="ui-btn ui-btn-default ui-btn-block ui-btn-vcode ui-disabled height-for-yz" style="">获取验证码</a></div>
            							</div>

            							<div class="ui-form-group ui-cf mt10 ui-cf pos-re ui-form-group2">
            								<div class="ui-col-9 ui-col-99">
            									<input type="text" name="" class="ui-form-input ui-form-input-sm" value="" placeholder="新密码" id='pwd'/>
            									<input type="text" name="" class="ui-form-input ui-form-input-sm" value="" placeholder="确认密码" id='pwd2'/>
            									<p class="ui-alert left-for-confirm" id='denglualert5'>
            										<span class="arrow"></span>
            										<i class="ui-icon-alert-info"></i>
            										<span id='pwdMeg'></span>
            									</p>
            								</div>
            								<!-- <div class="ui-col-3"></div> -->
            							</div>

            							<div class="ui-form-group ui-margin-top-lg ui-cf">
            								<div class="ui-col-12" id='submit'>
            									<input type="submit" class="ui-btn ui-btn-primary left-for-submit" value="提交" />
            								</div>
            							</div>
            						</div>
            				<!--	</form>-->
            				</div>
            				<div class="ui-forget-con ui-cf">
                            					<!--<form action="" method="post">-->
                            						<div class="ui-form ui-form-forget ui-cf">
                            							<!--<p class="ui-alert" id='denglualert1'><i class="ui-icon-alert-info"></i><span></span></p>-->
                            							<div class="ui-form-group ui-cf mt10 ui-cf pos-re">
                            								<div class="ui-col-12">
                            									<input type="text" name="" class="ui-form-input" value="" id='mail' placeholder="邮箱" />
                            									<p class="ui-alert left-for-confirm" id='denglualert1'>
                            										<span class="arrow"></span>
                            										<i class="ui-icon-alert-info"></i>
                            										<span id='forgetMail'></span>
                            									</p>
                            								</div>
                            							</div>
                            							<!--<p class="ui-alert" id='denglualert2'><i class="ui-icon-alert-info"></i><span></span></p>-->
                            							<div class="ui-form-group ui-cf mt10 ui-cf pos-re">
                            								<div class="ui-col-9">
                            									<input type="text" name="" class="ui-form-input ui-form-input-sm" value="" id='mailcode' placeholder="验证码" />
                            									<p class="ui-alert left-for-confirm" id='mail-jihuo'>
                            										<span class="arrow"></span>
                            										<i class="ui-icon-alert-info"></i>
                            										<span id='mailMegCode'></span>
                            									</p>
                            								</div>
                            								<div class="ui-col-3" id="emailcode" >
                            									<a href="javascript:;" class="ui-btn ui-btn-default ui-btn-block ui-btn-vcode ui-disabled height-for-yz">获取验证码</a>
                            								</div>
                            							</div>

                            							<div class="ui-form-group ui-cf mt10 ui-cf pos-re ui-form-group2">
                            								<div class="ui-col-9 ui-col-99">
                            									<input type="password" name="" class="ui-form-input ui-form-input-sm" value="" placeholder="新密码" id='mailpwd'/>
                            									<input type="password" name="" class="ui-form-input ui-form-input-sm" value="" placeholder="确认密码" id='mailpwd2'/>
                            									<p class="ui-alert left-for-confirm" id='mailPwdMeg'>
                            										<span class="arrow"></span>
                            										<i class="ui-icon-alert-info"></i>
                            										<span id='newpwdMeg'></span>
                            									</p>
                            								</div>
                            								<!-- <div class="ui-col-3"></div> -->
                            							</div>

                            							</div>
                            							<div class="ui-form-group ui-margin-top-lg ui-cf">
                            								<div class="ui-col-12 ui-form-forget">
                            									<input type="submit" id='mail-submit' class="ui-btn ui-btn-primary left-for-submit" value="提交" />
                            								</div>
                            							</div>
                            						</div>
            				<!--	</form>-->
            				</div>
            			</div>
		</div>
	</div>
</div>
<!-- forget/E-->

<script type="text/javascript" src="http://tv.cztv.com/bluetv/user/core.js"></script>
<script src='http://tv.cztv.com/bluetv/base/jqueryCookie.js'></script>
<!-- <script type="text/javascript" src="http://tv.cztv.com/bluetv/user/main.js"></script> -->
<script type="text/javascript" src="http://tv.cztv.com/bluetv/user/main0223.js"></script>

<script src="http://tv.cztv.com/bluetv/header/user.js"></script>
<script src="http://tv.cztv.com/bluetv/header/autoComplete.js" type="text/javascript"></script>
<script src="http://tv.cztv.com/bluetv/storage/swfobject.js"></script>
<script src="http://tv.cztv.com/bluetv/storage/xlPlayer.js"></script>
<script src="http://tv.cztv.com/bluetv/header/history.js"></script>
<script type="text/javascript">
$(function(){
	//tab切换
	//$("#ui-forget").on("click",".ui-tabs li",function(){
	//	if(!$(this).hasClass("active")){
	//		var index=$(this).index();
	//		$(this).addClass("active").siblings("li").removeClass("active");
	//		$("#ui-forget .ui-forget-con").removeClass("active");
	//		$("#ui-forget .ui-forget-con").eq(index).addClass("active");
	//	}
	//});
});
</script>
</body>
</html>
