<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="/module/elementsave" class="form-horizontal form-bordered form-label-stripped" id="form-element" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>修改原子</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <input type="hidden" name="moduleid" value="<?=$moduleid?>">
            <input type="hidden" name="id" value="<?=$element->id?>">
            <div class="form-group">
                <label class="control-label col-md-2">控制器 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="controller" placeholder="控制器" type="text" value="<?=$element->controller?>" class="form-control input-large validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">操作 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="action" placeholder="操作" type="text" value="<?=$element->action?>" class="form-control input-large validate-box"/>
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-md-2">原子名 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="action_name" placeholder="原子名" type="text" value="<?=$element->action_name?>" class="form-control input-large validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">显示</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label>
                        <input type="radio" class="icheck" <?php if($element->is_hide==0){ ?> checked="checked"<?php } ?> name="is_hide" value="0"/>
                        是</label>
                        <label>
                        <input type="radio" class="icheck" <?php if($element->is_hide==1){ ?> checked="checked"<?php } ?> name="is_hide" value="1"/>
                        否</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">系统功能组</label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label>
                        <input type="radio" class="icheck" <?php if($element->is_system==1){ ?> checked="checked"<?php } ?> name="is_system" value="1"/>
                        是</label>
                        <label>
                        <input type="radio" class="icheck" <?php if($element->is_system==0){ ?> checked="checked"<?php } ?> name="is_system" value="0"/>
                        否</label>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">
    // form stations
    $('#form-element').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            controller: {
                required : true
            },
            action: {
                required : true
            },
            action_name: {
                required : true
            }
        },

        messages: {
            controller: {
                required : '控制器必填'
            },
            action: {
                required : '操作必填'
            },
            action_name: {
                required : '原子名称必填'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>