<div class="form-group">
    <label class="control-label col-md-2">简介 <span class="font-red">*必填</span></label>
    <div class="col-md-10">
        <textarea placeholder="简介" rows="4" maxlength="200" class="form-control maxlength-handler validate-box" name="intro" id="intro"><?= Input::fetch('intro');?></textarea>
        <span class="help-block">简介来自文章中，但并不一定是第一段，要根据文章内容选取，如果可能请自己总结一段</span>
    </div>
</div>