<div class="form-group">
    <label class="control-label col-md-2">关键词</label>
    <div class="col-md-10">
        <input type="text" name="keywords" id="keywords" placeholder="关键词" class="form-control tags validate-box" value="<?= Input::fetch('keywords');?>"/>
        <span class="help-block">关键词来自简介和正文, 而不仅仅是标题, 请认真仔细选择关键词</span>
    </div>
</div>

<script type="text/javascript">
    $('#keywords').tagsInput({
        width: 'auto',
        defaultText: "输入标签"
    });
</script>