<?php
$categories = PrivateCategory::channelQuery(Auth::user()->channel_id)->execute();
?>
<div class="form-group">
    <label class="control-label col-md-2">分类 </label>
    <div class="col-md-10">
        <?php
        $this->partial('partials/private_category', [
            'id' => 'private_category_id',
            'name' => 'private_category_id',
            'data' => $privateCategoryData,
            'multiple'=>false,
        ]);
        ?>
    </div>
</div>