<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form class="form-horizontal form-bordered form-label-stripped" id="form-block" enctype="multipart/form-data" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加块  </span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>
            
            <div class="form-group">
                <label class="control-label col-md-2">块标识 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="code" type="text" placeholder="块标识" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">描述 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="description" type="text" placeholder="描述" maxlength="11" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">
    // form stations
    $('#form-block').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            code: {
                required : true
            },
            description: {
                required : true
            }
        },

        messages: {
            code: {
                required : '块标识不能为空'
            },
            description: {
                required : '描述不能为空'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>