<div class="form-group">
    <label class="control-label col-md-2">标题 <span class="font-red">*必填</span></label>
    <div class="col-md-10">
        <input type="text" name="title" id="title" placeholder="标题" maxlength="20" class="form-control maxlength-handler validate-box" value="<?= Input::fetch('title');?>" />
    </div>
</div>

<div class="form-group">
    <label class="control-label col-md-2">关键词</label>
    <div class="col-md-10">
        <input type="text" name="keywords" id="keywords" placeholder="关键词" class="form-control tags validate-box" value="<?= Input::fetch('keywords');?>"/>
        <span class="help-block">关键词来自简介和正文, 而不仅仅是标题, 请认真仔细选择关键词</span>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-md-2">简介 <span class="font-red">*必填</span></label>
    <div class="col-md-10">
        <textarea placeholder="简介" rows="4" maxlength="200" class="form-control maxlength-handler validate-box" name="intro" id="intro"><?= Input::fetch('intro');?></textarea>
        <span class="help-block">简介来自文章中，但并不一定是第一段，要根据文章内容选取，如果可能请自己总结一段</span>
    </div>
</div>

<script type="text/javascript">
    $('#keywords').tagsInput({
        width: 'auto',
        defaultText: "输入标签"
    });

    // form mediapost
    $('.form-mediapost').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            title: {
                required: true,
                minlength: 5
            },
            intro: {
                required: true
            }
        },

        messages: {
            title: {
                required: '标题不能为空',
                minlength: '标题不能少于6位'
            },
            intro: {
                required: '简介不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error');
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit();
        }

    });
</script>