<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form action="#" class="form-horizontal form-bordered form-label-stripped">
            <div class="form-body">

                <div class="form-group">
                    <label class="control-label col-md-2">按状态</label>
                    <div class="col-md-10">
                        <div class="order-filter">
                            <a href="#" class="active">任务通知</a>
                            <a href="#">待处理</a>
                            <a href="#">进行中</a>
                            <a href="#">我接受</a>
                            <a href="#">我发起</a>
                        </div>
                    </div>
                </div>

                <div class="form-group screening-box">
                    <label class="control-label col-md-2">按部门</label>
                    <div class="col-md-10">
                        <div class="order-filter">
                            <a href="#" class="active">新闻部</a>
                            <a href="#">编辑部</a>
                            <a href="#">视频部</a>
                        </div>
                    </div>
                </div>

                <div class="form-group screening-box">
                    <label class="control-label col-md-2">按栏目</label>
                    <div class="col-md-10">
                        <div class="order-filter">
                            <a href="#" class="active">任务通知</a>
                            <a href="#">待处理</a>
                            <a href="#">进行中</a>
                            <a href="#">我接受</a>
                            <a href="#">我发起</a>
                        </div>
                    </div>
                </div>

                <div class="form-group screening-box">
                    <label class="control-label col-md-2">按日期</label>
                    <div class="col-md-10">
                        <div class="input-group input-large date-picker input-daterange" data-date="10/11/2012" data-date-format="mm/dd/yyyy">
                            <input type="text" class="form-control" name="from">
                            <span class="input-group-addon">到</span>
                            <input type="text" class="form-control" name="to">
                        </div>
                    </div>
                </div>

            </div>
            <div class="form-actions screening-box">
                <div class="row">
                    <div class="col-md-offset-2 col-md-11">
                        <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
                        <button type="button" class="btn default">重置</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>