<?php
Input::init(Request::getPost(), $data);
?>
<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action=" " method="post" class="form-horizontal form-bordered form-label-stripped form-channel" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>修改来源</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>

            <div class="form-group">
                <label class="control-label col-md-2">网址LOGO <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="thumbnail" id="thumbnail" class="file-loading"/>
                        <input type="hidden" name="thumb" value="<?= Input::fetch('thumb');?>" />
                    </div>
                    <span class="help-block">请上传图片大小为30px-30px</span>
                </div>
            </div>
            <script>
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    maxFileCount: 1,
                    language: "zh",
                    minImageWidth: 30,
                    minImageHeight: 30,
                    //单位kb
                    maxFileSize: 2048,
                    allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'<?php if(Input::fetch('thumb')) { ?>,
                    /**
                     * 预加载数据
                     */
                    //预加载删除
                    initialPreviewShowDelete: false,
                    //预加载图片
                    initialPreview: ['<img src="<?= stripos(Input::fetch('thumb'),'image.xianghunet.com')?Input::fetch('thumb'):cdn_url('image',Input::fetch('thumb')); ?>" class="file-preview-image">'],
                    //预加载图片对应配置
                    initialPreviewConfig: [{caption: "索引图"}]
                    <?php } ?>
                };
                $("#thumbnail").fileinput(thumbnailConfig);
            </script>

            <div class="form-group">
                <label class="control-label col-md-2">来源 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="name" value="<?=$data->name?>" placeholder="来源" maxlength="50" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">URL地址 <span class="font-red">*必填</span></label>
                <div class="col-md-2">
                    <input type="text" name="url" value="<?=$data->url?>" placeholder="URL地址" maxlength="200" class="form-control input-large maxlength-handler validate-box" />
                </div>
            </div>

        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    // form stations
    $('.form-channel').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required: true
            },
            url: {
                required: true
            }
        },

        messages: {
            name: {
                required: '来源不能为空'
            },
            url: {
                required: 'Url地址不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>