<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['订阅专辑列表' => Url::get('subscription/index')],
//    'add'=> Url::get('stations/create'),
    'subscription_get_set' => 'subscription/getset',
    'editkeyword' => '/subscription/editkeyword',
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th class="">专辑编号</th>
                <th class="">专辑名</th>
                <th class="">订阅数</th>
<!--                <th class="">是否设为热词</th>-->
                <th class="">排序权重</th>
                <th class="">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value="<?= $v->subscriptionSet->id ?>"/>
                        </td>
                        <td><?= $v->subscriptionSet->set_id ?></td>
                        <td>
                            <img class="small-img" src="<?php if(isset($v->subscriptionSetInfo->set_cover)&&$v->subscriptionSetInfo->set_cover) {echo $v->subscriptionSetInfo->set_cover;} else{?> /assets/admin/layout/img/sidebar_inline_toggler_icon_blue.jpg <?php } ?>" >
                            <span class="name-center">
                                <?= $v->subscriptionSet->name ?>
                            </span>
                        </td>
                        <td><?= $v->subscriptionSetInfo->subscription_number ?></td>
                        <td><?= $v->subscriptionSetInfo->sort ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn blue-steel href-location tooltips" data-url="<?= Url::get('subscription/details', ['set_id' => $v->subscriptionSet->set_id]) ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="订阅名单列表"><i class="fa fa-bar-chart-o"></i></button>
                                <button type="button" class="btn green edit-content tooltips" data-url="/subscription/modify?set_id=<?=$v->subscriptionSet->set_id?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif;
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
<!--                     <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button> -->
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        6:{sorter:false}
    }
});
</script>
