<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <div class="form-horizontal form-bordered form-label-stripped" id="form-pushMsg" >
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>查看员工</span>
        </div>
	<?php if($data):?>
    <div class="form form-topcontrol">
        <div class="form-horizontal form-bordered form-label-stripped">
            <div class="form-body">
                 <div class="form-group" id="telephone">
                    <label class="control-label col-md-2">推送状态</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                            <?php $status = $data->status; if($status >= 0) {
                            	switch ($status) {
									case 0: echo "没有推送"; break;
									case 1: echo "完成"; break;
									case 2: echo "执行中"; break;
									case 9: echo "失败"; break;
									default:;
								}
                            }?>
                        </div>
                    </div>
                </div>

				<?php if(!empty($data->task_type)){ ?>
                <div class="form-group">
                    <label class="control-label col-md-2">媒资标题</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                             <?=$data->push_content;?>
                        </div>
                    </div>
                </div>
				<?php }?>
 				
 				<?php $titleArr = json_decode($data->task_data);
 					$title = empty($titleArr->data_title) ? "": $titleArr->data_title;
 					$data_id = empty($titleArr->data_id) ? "": $titleArr->data_id;
 				?>
 				 <div class="form-group" >
                    <label class="control-label col-md-2">媒资ID</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                            <?= $data_id;?>
                        </div>
                    </div>
                </div>
                <div class="form-group" >
                    <label class="control-label col-md-2">消息内容</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                           <?=$title;?>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">创建时间</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                            <?=date('Y-m-d H:i:s',$data->created_at);?>
                        </div>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="control-label col-md-2">更新时间</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                            <?=date('Y-m-d H:i:s',$data->updated_at);?>
                        </div>
                    </div>
                </div>
                
                <div class="form-group" >
	                <label class="control-label col-md-2">推送结果</label>
	                <div class="col-md-10">
	                    <textarea rows="8" class="form-control maxlength-handler"><?= $data->remark;?></textarea>
	                </div>
           		</div>
           		
           		<div class="form-group">
                    <label class="control-label col-md-2">推送个人</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                            <?=$data->single == 1 ? "是" : "否";?>
                        </div>
                    </div>
                </div>
                <?php if($data->single == 1){?>
                <div class="form-group">
                    <label class="control-label col-md-2">客户端ID</label>
                    <div class="col-md-10">
                        <div class="form-control-static">
                            <?=$data->push_single_client;?>
                        </div>
                    </div>
                </div>
                <?php }?>
                
            </div>
        </div>
    </div>
	<?php endif ?>
	</div>
</div>