<?php
Input::init(Request::getPost(), $model);
if(!isset($token)) {
    $album_id = $model->id;
    $token = '';
} else {
    $album_id = 0;
}
?>
<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form method="post" class="form-horizontal form-bordered form-label-stripped form-mediaalbum" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i><?= $action; ?>相册</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <?= $this->partial('partials/form/thumb');?>
            <?= $this->partial('partials/form/private_categories');?>
            <?= $this->partial('partials/form/title'); ?>
            <?= $this->partial('partials/form/sub_title'); ?>
            <?= $this->partial('partials/form/comment_type'); ?>
            <?= $this->partial('partials/form/water_mark'); ?>
            <?= $this->partial('partials/form/referer'); ?>
            <?= $this->partial('partials/form/keywords'); ?>
            <div class="form-group">
                <label class="control-label col-md-2">相册简介 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <textarea placeholder="相册简介" rows="4" class="form-control validate-box" name="intro" id="intro"><?= Input::fetch('intro');?></textarea>
                    <span class="help-block"></span>
                </div>
            </div>
            <input type="hidden" name="token" value="<?= $token; ?>" />
            <div class="form-group">
                <label class="control-label col-md-2">相册上传</label>
                <div class="col-md-10 albumsmain">
                    <input id="file_albums" type="file" multiple  class="file-loading" data-overwrite-initial="false" data-min-file-count="1">
                </div>
            </div>
                      
        </div>
    </form>
</div>

<script>
var token = '<?= $token;?>';
var album_id = <?= $album_id;?>;
if(album_id) {
    var upload_url = "<?= Url::get('media_albums/upload');?>?album_id="+album_id;
} else {
    var upload_url = "<?= Url::get('media_albums/tmpupload');?>?token="+token;
}
function delete_url(id) {
    var url;
    if(album_id) {
        url = '<?= Url::get('media_albums/removeimage');?>?id='+id+'&album_id='+album_id;
    } else {
        url = '<?= Url::get('media_albums/removetmpimage');?>?id='+id+'&token='+token;
    }
    return url;
}
var footerTemplate = '<div class="file-thumbnail-footer">\n' +
    '   <div class="file-thumbnail-imginfo">\n' +
    '       <textarea class="img-intro form-control" name="img_intro" placeholder="请输入描述...">{caption}</textarea>\n' +
    '   </div>\n' +
    '   {actions}\n' +
    '</div>';
var albumsConfig = {
    uploadUrl: upload_url,
    /**
     * FIXME 重复选择同一张图片无法修改描述
     */
    uploadExtraData: function(previewId, index) {
        console.log(previewId + ":" + index);
        var $intro = $('.img-intro').eq(index);
        var intro = '';
        if($intro) {
            intro = $intro.val()? $intro.val(): '';
        }
        return {"intro": intro};
    },
    //异步上传
    uploadAsync: true,
    showRemove: true,
    showCaption: true,
    //单位kb
    maxFileSize: 2048,
    allowedFileExtensions : ['jpg', 'png', 'gif', 'jpeg'],
    //底部模板
    layoutTemplates: {footer: footerTemplate},
    //允许上传 & 允许预览的类型
    allowedFileTypes: ['image'],
    previewFileType: "image",
    language: "zh",
    minImageWidth: 100,
    minImageHeight: 100,
    resizeImage: true,
    /**
     * 预加载数据
     */
    //预加载删除
    initialPreviewShowDelete: true,
    //预加载图片
    initialPreview: [],
    //预加载图片对应配置
    initialPreviewConfig: [],
    //额外数据对应配置
    initialPreviewThumbTags: []
};
<?php
    if(!isset($images)) {
        $images = [];
    }
    foreach($images as $img) {
        $intro = js_output(h($img->intro));
        $url = cdn_url('image',$img->path);
        echo <<<JS
albumsConfig.initialPreview.push('<img src="$url" class="file-preview-image" id="{$img->id}">');
albumsConfig.initialPreviewConfig.push({
    caption: "{$intro}",
    width: '120px',
    url: delete_url({$img->id}),
    key: {$img->id}
});
JS;
    }
?>
$("#file_albums").fileinput(albumsConfig);
$("#file_albums").on("filepredelete", function(jqXHR) {
    var abort = true;
    if (confirm("确定删除这些照片 ?")) {
        abort = false;
    }
    return abort;
});

    // form mediapost
    $('.form-mediaalbum').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            title: {
                required: true,
            },
            intro: {
                required: true
            }
        },

        messages: {
            title: {
                required: '标题不能为空',
            },
            intro: {
                required: '简介不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error');
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit();
        }

    });

    //sort photo
    $(function () {
        $(".albumsmain .file-preview-frame").bind('mouseover', function () {
            $(this).css("cursor", "move")
        });

        var $show = $("#loader");
        var $orderlist = $("#orderlist");
        var $list = $(".albumsmain .file-preview-thumbnails");
        $list.sortable({
            opacity: 0.6,
            revert: true,
            cursor: 'move',
            //handle: '.checkbox-middle',
            placeholder: "file-preview-danger",
            items: ".file-preview-frame",
            update: function () {
                var new_order = [];
                $list.children(".file-preview-frame").each(function () {
                    var id = $("#"+this.id).children(".file-preview-image").attr("id");
                    new_order.push(id);
                });
                $.ajax({
                    type: "post",
                    dataType: 'json',
                    url: "<?=Url::get('media_albums/sort') ?>",
                    data: {'ids': new_order,'album_id':album_id},
                    beforeSend: function () {
                        $show.html("正在更新...");
                    },
                    success: function (data) {
                        if (data.code != 200) {
                            alert(data.msg);
                        }
                    },
                    error: function () {
                        alert("error");
                    }

                });
            }
        });
    });

    //edit img info
    $(function () {
        
        var $show = $("#loader");
        $(".file-thumbnail-imginfo textarea").blur(function(){
            var img_intro = $(this).val();
            var id = $(this).parent().parent(".file-thumbnail-footer").siblings(".file-preview-image").attr('id');
            $.ajax({
                type: "post",
                dataType: 'json',
                url: "<?=Url::get('media_albums/eintro')?>",
                data: {'intro':img_intro,'id':id,'album_id':album_id},
                beforeSend: function () {
                    $show.html("正在更新...");
                },
                success: function (data) {
                    if (data.code != 200) {
                        alert(data.msg);
                    }
                },
                error: function () {
                    alert("error");
                }

            });
        })
    });
</script>

<input type="hidden" id="orderlist"/>
