<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['视频文件' => Url::get('ugc_live_vf/index')],
]);
?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>直播流ID</th>
            <th>直播开始时间</th>
            <th>直播结束时间</th>
            <th>主播</th>
            <th>主播设备</th>
            <th>码率</th>
            <th>文件地址</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($data)): $models = $data->models;
            foreach ($models as $video):
                $stream = $data_ext[$video->id]['stream'];
                $anchor = $data_ext[$video->id]['anchor'];
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" name="id" value="<?= $video->id ?>"/>
                    </td>
                    <td>
                        <?= 'S' . date('ymd', $stream['start_time']) . str_pad($stream['id'], 3, '0', STR_PAD_LEFT) ?>
                    </td>
                    <td>
                        <?= date('Y-m-d H:i:s', $video->start_time); ?>
                    </td>
                    <td>
                        <?= date('Y-m-d H:i:s', $video->end_time); ?>
                    </td>
                    <td>
                        <?= $anchor ?>
                    </td>
                    <td>
                        <?= $stream['terminal'] == '1' ? 'IOS' : $stream['terminal'] == '2' ? '安卓' : '其他' ?>
                    </td>
                    <td>
                        <?= $video->rate ?>
                    </td>
                    <td>
                        <?= $video->file_url.$video->file_flv_url ?>
                    </td>
                    <td>
					    <?php if($video->file_flv_url) { ?>
                        <a href="<?= $video->file_flv_url ?>" class="active">下载</a>
						<?php } ?>
                    </td>
                </tr>
                <?php
            endforeach;
        endif;
        ?>

        </tbody>
    </table>
    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选
                    </button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">
                        取消
                    </button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">
                        反选
                    </button>
                    <button type="button" class="btn btn-default">删除</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
