<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped form-stationsepg">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加直播流</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>
        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <input type="hidden" name="stations_id" value="<?=$station->id?>">

            <div class="form-group">
                <label class="control-label col-md-2">电台 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <?=$station->name?>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">直播流名 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="name" placeholder="直播流名" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">宽度 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="width" placeholder="宽度" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">高度 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="height" placeholder="高度" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">cdn <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="cdn" placeholder="cdn" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">percent <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="percent" placeholder="percent" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">视频码率 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="kpbs" placeholder="视频码率" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">音频码率 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="audiokpbs" placeholder="音频码率" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">防盗链 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input type="text" name="drm" placeholder="防盗链" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">权重</label>
                <div class="col-md-10">
                    <input type="text" name="sort" placeholder="权重" maxlength="50" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>
        </div>
    </form>
    <!-- END FORM-->
</div>
<script type="text/javascript">
    // form stationsepg
    $('.form-stationsepg').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            stations_id: {
                required : true,
                number: true
            },
            name: {
                required : true
            },
            width: {
                required : true,
                number: true
            },
            height: {
                required : true,
                number: true
            },
            cdn: {
                required : true,
                url: true
            },
            percent: {
                required : true,
                number: true
            },
            kpbs: {
                required : true,
                number: true
            },
            audiokpbs: {
                required : true,
                number: true
            },
            drm: {
                required : true
            }
        },

        messages: {
            stations_id: {
                required : '请输入正确的电视台ID',
                number : '电视台ID必须为数字'
            },
            name: {
                required : '请输入直播流名'
            },
            width: {
                required : '宽度不能为空',
                number : '宽度必须为数字'
            },
            height: {
                required : '高度不能为空',
                number : '高度必须为数字'
            },
            cdn: {
                required : 'CDN不能为空',
                url : '请输入合法的网址'
            },
            percent: {
                required : 'Percent不能为空',
                number : 'Percent必须为数字'
            },
            kpbs: {
                required : '视频码率不能为空',
                number : '视频码率必须为数字'
            },
            audiokpbs: {
                required : '音频码率不能为空',
                number : '音频码率必须为数字'
            },
            drm: {
                required : '防盗链不能为空'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element)
                .closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>