<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['活动评论列表' => Url::get('comment_hudong/index')],
    'add'=> Url::get('comment_hudong/add'),
    'html' => '',
]);
?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>活动名称</th>
                <th>创建人</th>
                <th>创建时间</th>
                <th>发布方式</th>
                <th>开启状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
        <?php
        if(isset($data->models)) $comments = $data->models;
        if (!empty($comments)) :
            foreach ($comments as $comment) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" name="selectchecked" value="<?php echo $comment->commentActivity->id; ?>"/>
                    </td>
                    <td>
                        <?= $comment->commentActivity->title ?>
                    </td>
                    <td>
                        <?= $comment->admin->name ?>
                    </td>
                    <td>
                        <?= date('Y-m-d h:i:s',$comment->commentActivity->created_at); ?>
                    </td>
                    <td>
                        <?= $comment->commentActivity->mustaudit=='1'?'先审后发':'先发后审'   ?>
                    </td>
                    <td>
                        <?= $comment->commentActivity->status=='1'?'开启':'关闭'  ?>
                    </td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn blue edit-content tooltips" data-url="<?=Url::get('comment_hudong/edit',['id'=>$v->admin->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            <button type="button" class="btn bg-green-jungle edit-content tooltips" data-url="<?=Url::get('comment_hudong/audit',['id'=>$v->admin->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="审核"><i class="fa fa-anchor"></i></button>
                            <button type="button" class="btn yellow edit-content tooltips" data-url="<?=Url::get('comment_hudong/detail',['id'=>$v->admin->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="查看"><i class="fa fa-eye"></i></button>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="button" class="btn btn-default  tooltips" data-url="<?= Url::get('verify/comment'); ?>" onclick="passnews(this, 1)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="通过审核选中的评论">通过审核</button>
                    <button type="button" class="btn btn-default tooltips" data-url="<?= Url::get('verify/comment'); ?>" onclick="passnews(this, 2)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="取消审核选中的评论">取消审核</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>