<!-- 团拜会专用后台模版 -->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="zh-cn" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="zh-cn" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zh-cn">
    <!--<![endif]-->
    <!-- Begin Head -->
    <head>
        <meta charset="utf-8"/>
        <title>CMS | 用户登录 - 中国蓝新媒体平台</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta content="" name="description"/>
        <meta content="" name="author"/>
        <!-- <link rel="shortcut icon" href="favicon.ico"/> -->

        <!-- Font Icon Css -->
        <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
        <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>

        <!-- Component Plug-in Css -->
        <link href="/assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
        <link href="/assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="/assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
        <link href="/assets/admin/layout/css/themes/blue.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="/assets/admin/pages/css/login.css" rel="stylesheet" type="text/css"/>
        <link href="/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>

        <!-- Coder Plugins -->
        <!--[if lt IE 9]>
        <script src="/assets/global/plugins/respond.min.js"></script>
        <script src="/assets/global/plugins/excanvas.min.js"></script> 
        <![endif]-->
        <script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>

        <!-- Page Plugins -->
        <script src="/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
        <script src="/assets/global/scripts/metronic.js" type="text/javascript"></script>
        <script src="/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
        <!-- <script src="/assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
        <script src="/assets/admin/pages/scripts/login.js" type="text/javascript"></script> -->
        <script>
			jQuery(document).ready(function () {
				Metronic.init();
				Layout.init();
				//Login.init();
				//Demo.init();
			});
        </script>
    </head>
    <body class="login">
        <!-- logo -->
        <div class="logo">
            <a href="index" class="logo-content">
                <img src="<?= $channel ? $channel->channel_logo : D::defaultImage('logo'); ?>" class="logo-img" alt=""/>
                <img src="<?= D::defaultImage('hdcztvqrcode') ?>" alt="" class="qr-code">
            </a>
            <span><?= $channel ? $channel->name : "中国蓝新媒体平台" ?></span>
        </div>
        <!-- login form -->
        <div class="content">
            <?= $this->getContent(); ?>
        </div>

        <!-- copy -->
        <div class="copyright">
            2015 &copy; <?= $channel ? $channel->name : "中国蓝新媒体平台" ?>
        </div>
    </body>
</html>
<script type="text/javascript">
    if(window.parent && window.parent.location.href != window.location.href){
        window.parent.location.href = window.location.href
    }
</script>