<?php
$this->partial("partials/breadcrumb", [
    'urls'=>['角色列表'=>Url::get('role/index')],
    'add'=>Url::get("role/add")
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>角色</th>
                <th>权限</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (isset($data->models) && !empty($models = $data->models)){
                foreach ($models as $v) {
                    ?>
                    <tr>
                        <td class="checkbox-middle" width="2%">
                            <input type="checkbox" class="checkboxes" value="1"/>
                        </td>
                        <td width="10%"><?= $v->name ?></td>
                        <td width="70%"><?php
                        if(!empty($v->element)){
                            foreach (explode(",",$v->element) as $e){
                                if($element[$e]['belong']==0&&$element[$e]['auth_hide']==0)  {
                                    echo $element[$e]['action_name']," ";
                                }
                            }
                        } ?></td>
                        <td width="18%">
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('role/edit',['id'=>$v->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                }
            }
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <?= $data->pagination->render();?>
                <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>