<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form action="/subscription/search" method="post" class="form-horizontal form-bordered form-label-stripped">
            <div class="form-body">

                <div class="form-group screening-box">
                    <label class="control-label col-md-2">搜索</label>
                    <div class="col-md-10">
                        <div class="screening-order">
                            <input type="text" class="form-control input-large  margin-right-10" placeholder="输入关键词" name="keyword" />
                            <input type="submit" class="btn blue breadcrumbbtn" value="搜索" />
                        </div>
                    </div>
                </div>

            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>