<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['自定义字段管理' => Url::get('custom_params/index')],
    'add'=> Url::get('custom_params/add'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th class="">参数名</th>
                <th class="">参数存储名</th>
                <th class="">参数形式</th>
                <th class="">默认值</th>
                <th class="">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value="<?= $v->id ?>"/>
                        </td>
                        <td>
                            <span class="name-center">
                                <?= $v->param_label ?>
                            </span>
                        </td>
                        <td><?= $v->param_name ?></td>
                        <td><?= CustomParams::$funtypes[$v->param_fun_type] ?></td>
                        <td><?= $v->param_default ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn green edit-content tooltips" data-url="/custom_params/edit?id=<?=$v->id?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <button type="button" class="btn blue tooltips" onclick="show_confirm(this)"  data-url="" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="审查"><i class="fa fa-check-square-o"></i></button>
                                <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="/stations/delete?id=<?= $v->id ?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif;
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
<!--                     <button type="button" class="btn btn-default" href="#delet-config" data-toggle="modal">删除</button> -->
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        4:{sorter:false}
    }
});
</script>
