<!DOCTYPE html>
<!--[if IE 8]> <html lang="zh-cn" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="zh-cn" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zh-cn">
<!--<![endif]-->
<!-- Begin Head -->
<head>
    <meta charset="utf-8"/>
    <title>CMS | CZTV - 中国蓝互动平台</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!-- <link rel="shortcut icon" href="favicon.ico"/> -->

    <!-- Font Icon Css -->
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>

    <!-- Component Plug-in Css -->
    <link href="/assets/global/plugins/select2/select2.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/icheck/skins/all.css" rel="stylesheet"/>
    <link href="/assets/global/plugins/file-upload/css/fileinput.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/jstree/dist/themes/default/style.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/admin/pages/css/todo.css" rel="stylesheet" type="text/css"/>

    <!-- Themes Css -->
    <link href="/assets/global/css/global-allplugin.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/admin/layout/css/themes/blue.css" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
    
    <!-- Coder Plugins -->
    <!--[if lt IE 9]>
    <script src="/assets/global/plugins/respond.min.js"></script>
    <script src="/assets/global/plugins/excanvas.min.js"></script> 
    <![endif]-->
    <script src="/assets/global/plugins/jquery.min.js"></script>
    <script src="/assets/global/plugins/jquery-migrate.min.js"></script>
    <script src="/assets/global/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"></script>
    <script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/assets/global/plugins/jquery.blockui.min.js"></script>
    <script src="/assets/global/plugins/jquery.cokie.min.js"></script>
    <script src="/assets/global/plugins/uniform/jquery.uniform.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <script src="/assets/global/plugins/jquery.cxselect.min.js"></script>

    <!-- Page Plugins -->
    <script src="/assets/global/plugins/select2/select2.min.js"></script>
    <script src="/assets/global/plugins/fuelux/js/spinner.min.js"></script>

    <script src="/assets/global/plugins/file-upload/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>

    <script src="/assets/global/plugins/file-upload/js/fileinput.js" type="text/javascript"></script>
    <script src="/assets/global/plugins/file-upload/js/fileinput_locale_zh.js" type="text/javascript"></script>
    
    <script src="/assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>
    <script src="/assets/global/plugins/jquery.input-ip-address-control-1.0.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-pwstrength/pwstrength-bootstrap.min.js"></script>
    <script src="/assets/global/plugins/jquery-tags-input/jquery.tagsinput.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-touchspin/bootstrap.touchspin.js"></script>
    <script src="/assets/global/plugins/typeahead/handlebars.min.js"></script>
    <script src="/assets/global/plugins/typeahead/typeahead.bundle.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-markdown/lib/markdown.js"></script>
    <script src="/assets/global/plugins/bootstrap-markdown/js/bootstrap-markdown.js"></script>
    <script src="/assets/global/plugins/icheck/icheck.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-selectsplitter/bootstrap-selectsplitter.min.js"></script>
    <script src="/assets/global/plugins/autosize/autosize.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
    <script src="/assets/global/plugins/clockface/js/clockface.js"></script>
    <script src="/assets/global/plugins/bootstrap-daterangepicker/moment.min.js"></script>
    <script src="/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js" ></script>
    <script src="/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    <script src="/assets/global/plugins/bootbox/bootbox.min.js"></script>
    <script src="/assets/global/plugins/fancybox/source/jquery.fancybox.pack.js"></script>
    <script src="/assets/global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
    <script src="/assets/global/plugins/jstree/dist/jstree.min-3.js"></script>
    <script src="/assets/global/plugins/jquery.tablesorter.js"></script>
    <script src="/assets/global/plugins/sortable.min.js"></script>

    <!-- Page Script -->
    <script src="/assets/global/scripts/metronic.js"></script>
    <script src="/assets/admin/layout/scripts/layout.js"></script>
    <script src="/assets/admin/pages/scripts/pageall.js"></script>
    <script src="/assets/admin/layout/scripts/base.js?20170110"></script>
    <script>
        jQuery(document).ready(function() {       
            Metronic.init();
            Layout.init();
            QuickSidebar.init();
            FormSamples.init();
            ComponentsFormTools.init();
            ComponentsFormTools2.init();
            FormiCheck.init();
            ComponentsPickers.init();
            BaseJs.init();
        });

        window.onload=function () {
            var loadingMask = window.parent.parent.document.getElementById("loading_icon");
            $(loadingMask).fadeOut(60);
        }
    </script>
</head>
<!-- End Head -->