<style>
    .loading_mask {
        width:100%;
        height:100%;
        opacity:1;
        position:fixed;
        z-index:99999999999;
        /*background-color:rgb(18,124,199);
        */
    }
    .mask_img {
        width:50px;
        height:50px;
        position:absolute;
        top:50%;
        margin-top:-25px;
        left:50%;
        margin-left:-25px;
    }
</style>
<div class="loading_mask" id="loading_icon" style="display: block">
    <div class="mask_img"><i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
<span class="sr-only">Loading...</span></div>
</div>

<script>
    function closeMask() {
        setTimeout(function () {
            var loadingMask = document.getElementById("loading_icon");
            if( $(loadingMask).is(':visible') ){
//                alert("加载异常")
                runLoadingMask(false);
            }
        },10*1000);
    }
</script>