    <!-- 后台共用文件 -->
    <meta charset="utf-8"/>
    <title>新蓝云平台-浙江广播电视集团新媒体</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!--  禁止所有的搜索引擎,另在后台站点防止文件/cms/public/robots.txt -->
	<meta content="noarchive" name="robots">
    <link rel="shortcut icon" href="/assets/global/img/favicon.ico"/>
	
    <!-- Css文件 -->
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

    <!-- Js文件 -->
    <script src="/assets/global/plugins/jquery.min.js"></script>    
    <script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js"></script>