<li>
    <a href="javascript:;" data-url="javascript:;">
        <span class="selected"></span>
        <span class="title"><?= $e['action_name']; ?></span>
        <span class="arrow"></span>
    </a>
    <ul class="sub-menu">
        <li>
            <a target="mainiframe"
               href="javascript:;" data-url="<?= Url::get('ugcyun_live_stream/index') ?>" ><span class="title">直播流管理</span></a>
        </li>
        <li>
            <a target="mainiframe"
               href="javascript:;" data-url="<?= Url::get('ugcyun_live_vf/index') ?>" ><span class="title">点播文件管理</span></a>
        </li>
    </ul>
</li>