<li>
    <a href="javascript:;">
        <span class="selected"></span>
        <span class="title"><?= $e['action_name']; ?></span>
        <span class="arrow"></span>
    </a>
    <ul class="sub-menu">
        <li><a target="mainiframe" href="javascript:;" data-url="<?= Url::get('sms_piple/index') ?> ">
                <span class="selected"></span>
                <span class="title">短信通道</span>
                <span class="arrow"></span>
            </a>
        </li>
        <li>
            <a target="mainiframe" href="javascript:;" data-url="<?= Url::get('sms_template/index') ?>" >
                <span class="selected"></span>
                <span class="title">短信模板</span>
                <span class="arrow"></span>
            </a>
        </li>
        <li>
            <a target="mainiframe" href="javascript:;" data-url="<?= Url::get('sms_sence/index') ?>" >
                <span class="selected"></span>
                <span class="title">短信场景</span>
                <span class="arrow"></span>
            </a>
        </li>
        <li>
            <a target="mainiframe" href="javascript:;" data-url="<?= Url::get('sms/log') ?>" >
                <span class="selected"></span>
                <span class="title">短信日志</span>
                <span class="arrow"></span>
            </a>
        </li>
    </ul>
</li>