<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form action="" method="post" class="form-horizontal form-bordered form-label-stripped" id="form-binding" enctype="multipart/form-data">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>绑定推荐位</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages');?>
            <input type="hidden" name="data_id" value="<?= $data_id ?>"/>

            <div class="form-group">
                <label class="control-label col-md-2">标题</label>
                <div class="col-md-10">
                    <input type="text" readonly value="<?= $data_name?$data_name:'' ?>" class="form-control input-large"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">推荐缩略图</label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="feature_thumbnail" id="feature_thumbnail" class="file-loading"/>
                        <input type="hidden" name="feature_thumb" value="<?= $data?$data['feature_thumb']:'' ?>"/>
                    </div>
                    <span class="help-block">请上传图片大小为300px-300px</span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">推荐位选择 </label>
                <div class="col-md-10">
                    <?php
                    $this->partial('features/partials/special_category', [
                        'id' => 'feature_id',
                        'name' => 'feature_id',
                        'data' => $featured_data,
						'features_type' => $feature_type,
                        'multiple'=>true,
                    ]);
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">推荐标题</label>
                <div class="col-md-10">
                    <input type="text" name="feature_title" placeholder="推荐标题" value="<?= $data?$data['feature_title']:'' ?>" maxlength="80" class="form-control input-large maxlength-handler"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">权重</label>
                <div class="col-md-10">
                    <input type="text" name="sort" placeholder="权重" value="<?= $data?$data['sort']:'' ?>" maxlength="20" class="form-control input-large maxlength-handler"/>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    // form stations
    $('#form-binding').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            feature_id: {
                required: true
            }
        },

        messages: {
            feature_id: {
                required: '推荐位选择不能为空'
            }
        },

        invalidHandler: function(event, validator) {  
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }
    });
    var thumbnailConfig = {
        uploadAsync: false,
        showRemove: false,
        showCaption: false,
        showUpload: false,
        overwriteInitial: true,
        maxFileCount: 1,
        language: "zh",
        minImageWidth: 100,
        minImageHeight: 100,
        maxImageWidth: 500,
        maxImageHeight: 500,
        //单位kb
        maxFileSize: 2048,
        allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
        //允许上传 & 允许预览的类型
        allowedFileTypes: ['image'],
        previewFileType: "image",
        browseLabel: '浏览 ...'<?php if($data?$data['feature_thumb']:'') { ?>,
        /**
         * 预加载数据
         */
        //预加载删除
        initialPreviewShowDelete: false,
        //预加载图片
        initialPreview: ['<img src="<?= cdn_url('image',$data['feature_thumb']); ?>" class="file-preview-image">'],
        //预加载图片对应配置
        initialPreviewConfig: [{caption: "推荐缩略图"}]
        <?php } ?>
    };
    $("#feature_thumbnail").fileinput(thumbnailConfig);
</script>
