<?php
$this->partial("ugcyun_live_stream/partials/detailtop", [
    'urls' => ['直播流列表' => Url::get('ugcyun_live_stream/index')],
]);
?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>类型</th>
            <th>地址</th>
            <th>清晰度</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($urls as $line): ?>
            <tr>
                <td><?= $line['type'] ?></td>
                <td><?= $line['url'] ?></td>
                <td><?= $line['pic_quality'] ?></td>
                <td>
                    <?php if ($line['pic_quality'] && $stream->stream_event == 'start'): ?>
                        <button type="button" class="btn red  edit-content tooltips"
                                data-url="<?= Url::get('ugc_live_room/playStream', array('u', $line['url'])) ?>"
                                data-container="body"
                                data-placement="top" data-trigger="hover" data-html="true"
                                data-original-title="在线直播"><i class="fa fa-edit"></i></button>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
