<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['中奖列表' => Url::get('lottery_winnings/index',['lottery_group_id' => isset($lottery_group)?$lottery_group->id:0])],
]);
?>
<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th>姓名</th>
                <th>奖品名称</th>
                <th>手机</th>
                <th>中奖时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($data->models)) {
                foreach ($data->models as $v) {
                    $w = $v->lotteryWinnings;
                    $v = $v->lotteryContacts;
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" name="selectchecked" value="<?= $v->id ?>"/>
                        </td>
                        <td>
                            <img class="small-img" src="/assets/admin/layout/img/avatar.png" />
                            <span class="name-center">
                                <?= $v->name ?>
                            </span>
                        </td>
                        <td><?= $w->prize_name ?></td>
                        <td><?= $v->mobile ?></td>
                        <td><?= date('m-d H:i:s', $v->created_at) ?></td>
                        <td><span class="font-red"><?= LotteryContacts::getStatusName($v->status);?></span></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn green edit-content tooltips" data-url="<?= Url::get('lottery_winnings/edit', ['id' => $v->id]) ?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                }
            }
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                    <button type="submit" class="btn blue popovers" data-url="<?= Url::get('lottery_winnings/index',['lottery_group_id' => isset($lottery_group)?$lottery_group->id:0 ,
                        'prize_is_real' => Request::get('prize_is_real') , 'keyword' => Request::get('keyword') ,
                        'export' => 1]);?>"
                            onclick="passnews(this)" data-container="body" data-trigger="hover" data-placement="top" data-content="禁止在活动开启时导出数据">导出所选</button>
                </div>
            </div>
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            6:{sorter:false}
        }
    });
    function passnews(datatips){
        var checkVal = [];
        $('input[name="selectchecked"]:checked').each(function(){
            checkVal.push($(this).val());
        });
//        if (checkVal.length==0){
//            alert('你还没有选择任何内容！将导出所有名单');
//        }
        var datatips = $(datatips);
        var datatitle = datatips.attr('data-original-title');
        var datamessage = '确定导出所有名单吗';
        bootbox.dialog({
            message: datamessage,
            title: datatitle,
            buttons: {
                success: {
                    label: "确定",
                    className: "green",
                    callback: function() {
                        var url =datatips.attr('data-url');
                        location.href = url;
//                        $.post(url,{id:checkVal}, function(result){
//                            if(result.msg =="success"){
//                                location.reload();
//                            }
//                        });
                    }
                },
                danger: {
                    label: "取消",
                    className: "red",
                    callback: function() {

                    }
                }
            }
        });
    }
</script>