<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['应用提示弹窗' => Url::get('apppopup/index')]
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>APP名称</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($models = $data->models)) :
            foreach ($models as $v) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td>
                        <img class="small-img" src="<?php if($v->logo) {  echo cdn_url('image',$v->logo); } else{?> /assets/admin/layout/img/defaultlogo.png<?php } ?>" />
                        <span class="name-center">
                            <?= $v->name ?>
                        </span>
                    </td>
                    <td>

                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" data-url="<?=Url::get('apppopup/popuplist', ['id'=>$v->id,'type'=>'android'])?>" class="btn blue-steel href-location tooltips" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="安卓提示弹窗"><i class="fa fa-android"></i></button>
                            <button type="button" data-url="<?=Url::get('apppopup/popuplist', ['id'=>$v->id,'type'=>'ios'])?>" class="btn blue href-location tooltips" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="IOS提示弹窗"><i class="fa fa-apple"></i></button>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $data->pagination->render() ;?>
            <div class="pagination-info"><?=Lang::_('total')."： ".$data->count?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        1:{sorter:false},
        3:{sorter:false},
        4:{sorter:false},
        5:{sorter:false},
        6:{sorter:false},
        7:{sorter:false}
    }
});
</script>
