<?php

$addaction = ($app_type=="android")?"androidadd":"iosadd";
$editaction = ($app_type=="android")?"androidedit":"iosedit";
$title = ($app_type=="android")?"安卓":"苹果";
$this->partial("partials/breadcrumb", [
    'urls' => ['应用提示弹窗' => Url::get('apppopup/index'), $app->name.'('.$title.')'=>"" ],
    'add'=> Url::get('apppopup/add', ['app_id'=>$app->id , 'app_type'=>$app_type]),
]);

?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="table-checkbox">选择</th>
            <th>应用名</th>
            <th>版本</th>
            <th>状态</th>
            <th>标题</th>
            <th>类型</th>
            <th>图片</th>
            <th>弹窗内容类型</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($models = $data->models)) :
            foreach ($models as $v) :
                ?>
                <tr>
                    <td class="checkbox-middle">
                        <input type="checkbox" class="checkboxes" value="1"/>
                    </td>
                    <td>
                        <span class="name-center">
                            <?= $app_name ?>
                        </span>
                    </td>
                    <td><?= $v->version ?></td>
                    <td><?= ($v->status==1?"审核":"未审核") ?></td>
                    <td><?= ($v->title?:"中国蓝TV") ?></td>
                    <td><?= ($v->poptype==1?"第一次启动弹出":"每次启动弹出")?></td>
                    <td><img width="200" height="160" src="<?= (stripos($v->thumb, "http")===false)?cdn_url('image',$v->thumb):$v->thumb ?>"></td>
                    <td><?php switch($v->datatype){
                            case AppPopup::$VideoUnitDetailTypeWeb:
                            case AppPopup::$VideoUnitDetailTypeCredit: echo '页面链接';break;
                            case AppPopup::$VideoUnitDetailTypeLive:
                            case AppPopup::$VideoUnitDetailTypeVOD:
                            case AppPopup::$VideoUnitDetailTypeSubject:
                            case AppPopup::$VideoUnitDetailTypePanoLive:
                            case AppPopup::$VideoUnitDetailTypePanoVOD: echo '视频链接';break;
                        }?>
                    </td>
                    <td>
                        <div class="btn-group btn-group-xs btn-group-solid">
                            <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('apppopup/edit', ['id'=>$v->id ,'app_id'=>$app->id , 'app_type'=>$app_type])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                            <?php
                               if($v->status==1) {
                            ?><button type="button" class="btn red tooltips" data-url="<?=Url::get('apppopup/unlock',['id'=>$v->id])?>" onclick="show_confirm(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="取消审核"><i class="fa fa-check-square"></i></button>
                            <?php
                               }
                               else {
                            ?><button type="button" class="btn blue tooltips" data-url="<?=Url::get('apppopup/lock',['id'=>$v->id])?>" onclick="show_confirm(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="审核"><i class="fa fa-check-square"></i></button>
                            <?php
                               }
                            ?>
                            <button type="button" class="btn red tooltips" data-url="<?=Url::get('apppopup/delete',['id'=>$v->id])?>" onclick="show_confirm(this)" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                        </div>
                    </td>
                </tr>
                <?php
            endforeach;
        endif
        ?>
        </tbody>
    </table>

    




    <div class="paginationnav">
        <div class="paginationnav-main">
            <div class="table-btn">
                <div class="btn-group">
                    <button type="button" class="btn btn-default group-checkable" data-set="#sorttable .checkboxes">全选</button>
                    <button type="button" class="btn btn-default group-offcheckable" data-set="#sorttable .checkboxes">取消</button>
                    <button type="button" class="btn btn-default group-anticheckable" data-set="#sorttable .checkboxes">反选</button>
                </div>
            </div>
            <?= $data->pagination->render() ;?>
            <div class="pagination-info"><?=Lang::_('total')."： ".$data->count?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
$("#sorttable .table").tablesorter({
    headers:{
        0:{sorter:false},
        1:{sorter:false},
        3:{sorter:false},
        4:{sorter:false},
        5:{sorter:false},
        6:{sorter:false},
        7:{sorter:false}
    }
});
</script>
