<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form action="" method="get" class="form-horizontal form-bordered form-label-stripped">
            <div class="form-body">
                <div class="form-group">
                    <label class="control-label col-md-2">会场</label>
                    <div class="col-md-10">
                        <?= $this->partial("lotteries/partials/channel", ['name' => 'lottery_channel_id', 'channel' => $lotteryChannel, 'current' => Request::get('lottery_channel_id')]) ?>
                    </div>
                </div>
                <div class="form-group screening-box">
                    <label class="control-label col-md-2">日期起止</label>
                    <div class="col-md-4">
                        <div class="input-group input-large date-picker input-daterange" data-date="2012-10-11" data-date-format="yyyy-mm-dd">
                            <input type="text" class="form-control" name="open_time" value="<?= Request::get('open_time') ? : '' ?>">
                            <span class="input-group-addon">到</span>
                            <input type="text" class="form-control" name="close_time" value="<?= Request::get('close_time') ? : '' ?>">
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-10">
                        <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
                        <button type="button" class="btn default" onclick="window.location.href = '<?= Url::get('lotteries/index') ?>'">重置</button>
                        <span><button type="submit" name="export" value="1" class="btn blue"><i class="fa fa-check"></i> 导出数据</button>( <font color="red">禁止</font>在活动开启的时候导出数据 ) 服务器时间： <?= date('Y-m-d H:i:s',time());?></span>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>