<?php
$this->partial("partials/breadcrumb", [
    'urls' => ['APP菜单' => Url::get('menu/index')],
    'add'=> Url::get('menu/create'),
    'html' => '',
]);
?>

<div class="table-info table-responsive sortable ui-sortable" id="sorttable">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="table-checkbox">选择</th>
                <th class="">菜单名</th>
                <th class="">菜单类型</th>
                <th class="">状态</th>
                <th class="">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (!empty($models = $data->models)) :
                foreach ($models as $v) :
                    ?>
                    <tr>
                        <td class="checkbox-middle">
                            <input type="checkbox" class="checkboxes" value="<?= $v->id ?>"/>
                        </td>
                        <td>
                            <img class="small-img" src="<?php if($v->icon) { echo cdn_url('image',$v->icon); } else{?> /assets/admin/layout/img/defaultlogo.png<?php } ?>" />
                            <span class="name-center">
                                <?= $v->name ?>
                            </span>
                        </td>
                        <td><?= $v->type ?></td>
                        <td class="<?= ($v->status==1)?"font-green":"font-red" ?>"><?= ($v->status==1)?"显示":"隐藏" ?></td>
                        <td>
                            <div class="btn-group btn-group-xs btn-group-solid">
                                <button type="button" class="btn green edit-content tooltips" data-url="<?=Url::get('menu/modify',['id'=>$v->id])?>" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="编辑"><i class="fa fa-edit"></i></button>
                                <button type="button" class="btn red tooltips" onclick="show_confirm(this)" data-url="<?=Url::get('menu/delete',['id'=>$v->id])?>" data-toggle="modal" data-container="body" data-placement="top" data-trigger="hover" data-html="true" data-original-title="删除"><i class="fa fa-trash-o"></i></button>
                            </div>
                        </td>
                    </tr>
                    <?php
                endforeach;
            endif;
            ?>
        </tbody>
    </table>

    <div class="paginationnav">
        <div class="paginationnav-main">
            <?= $data->pagination->render(); ?>
            <div class="pagination-info"><?= Lang::_('total') . "： " . $data->count ?></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#sorttable .table").tablesorter({
        headers:{
            0:{sorter:false},
            4:{sorter:false}
        }
    });
</script>
