<?php Input::init(Request::getPost(), $model); ?>
<div class="form page-quick-sidebar-form">
    <!-- BEGIN FORM-->
    <form class="form-horizontal form-bordered form-label-stripped" id="form-lotteries-channels" enctype="multipart/form-data" method="post">
        <div class="page-quick-sidebar-title">
            <span class="page-quick-sidebar-titleinfo font-blue"><i class="fa fa-info"></i>添加抽奖会场</span>
            <div class="btn-group">
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> 提交</button>
            </div>
        </div>

        <div class="form-body">
            <?php $this->partial('partials/error_messages'); ?>
            <div class="form-group">
                <label class="control-label col-md-2">活动名称 </label>
                <div class="col-md-10" style="padding-top: 23px;padding-bottom: 23px;">
                    <?= isset($lottery_group)?$lottery_group->name:'' ?>
                    <input name="group_id" value="<?= isset($lottery_group)?$lottery_group->id:'' ?>" style="display: none"/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">会场背景图 </label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="backgroundnail" id="backgroundnail" class="file-loading"/>
                        <input type="hidden" name="background" value=""/>
                    </div>
                    <span class="help-block">请上传图片大小为300px-300px</span>
                </div>
            </div>
            <script>
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    maxFileCount: 1,
                    language: "zh",
                    minImageWidth: 100,
                    minImageHeight: 100,
                    //单位kb
                    maxFileSize: 2048,
                    allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'
                };
                $("#backgroundnail").fileinput(thumbnailConfig);
            </script>

            <div class="form-group">
                <label class="control-label col-md-2">会场名称 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <input name="name" type="text" value="" placeholder="会场名称" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Logo </label>
                <div class="col-md-10">
                    <div class="input-large">
                        <input type="file" name="logonail" id="logonail" class="file-loading"/>
                        <input type="hidden" name="style" value=""/>
                    </div>
                    <span class="help-block">请上传图片大小为300px-300px</span>
                </div>
            </div>
            <script>
                var thumbnailConfig = {
                    uploadAsync: false,
                    showRemove: false,
                    showCaption: false,
                    showUpload: false,
                    overwriteInitial: true,
                    maxFileCount: 1,
                    language: "zh",
                    minImageWidth: 100,
                    minImageHeight: 100,
                    //单位kb
                    maxFileSize: 2048,
                    allowedFileExtensions: ['jpg', 'png', 'gif', 'jpeg'],
                    //允许上传 & 允许预览的类型
                    allowedFileTypes: ['image'],
                    previewFileType: "image",
                    browseLabel: '浏览 ...'
                };
                $("#logonail").fileinput(thumbnailConfig);
            </script>


            <div class="form-group">
                <label class="control-label col-md-2">类型 <span class="font-red">*必填</span></label>
                <div class="col-md-10">
                    <div class="icheck-inline">
                        <label><input type="radio" class="icheck" name="type" value="tv" checked/>电视台</label>
                        <label><input type="radio" class="icheck" name="type" value="radio"/>广播台</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">排序</label>
                <div class="col-md-10">
                    <input name="sort" type="text" value="" placeholder="排序" maxlength="20" class="form-control input-large maxlength-handler validate-box"/>
                </div>
            </div>

        </div>
    </form>
    <!-- END FORM-->
</div>

<script type="text/javascript">
    // form lotteries channels
    $('#form-lotteries-channels').validate({
        errorElement: 'span', //default input error message container
        errorClass: 'help-block', // default input error message class
        focusInvalid: true, // do not focus the last invalid input
        rules: {
            name: {
                required: true
            },
            style: {
                required: true
            }
        },

        messages: {
            name: {
                required: '频道名不能为空'
            },
            style: {
                required: '样式不能为空'
            }
        },

        invalidHandler: function(event, validator) {
            //$('.alert-danger', $('.login-form')).show();
        },

        highlight: function(element) { // hightlight error inputs
            $(element).closest('.form-group').addClass('has-error'); // set error class to the control group
        },

        success: function(label) {
            label.closest('.form-group').removeClass('has-error');
            label.remove();
        },

        errorPlacement: function(error, element) {
            error.insertAfter(element.closest('.validate-box'));
        },

        submitHandler: function(form) {
            form.submit(); // form validation success, call ajax form submit
        }

    });
</script>