<?php
Input::init(Request::get(),[]);
if(!isset($mess)){
    $mess=array();}
?>
<div class="screening-content">
    <div class="form">
        <!-- BEGIN FORM-->
        <form role="form" method="post" class="form-horizontal form-bordered form-label-stripped" action="/ltvugc_live/listPayment">
            <div class="form-body">
                <div class="form-group ">
                    <label class="control-label col-md-2">搜索</label>
                    <div class="col-md-10">
                        <div class="screening-order">
                            <input type="text" class="form-control input-small   margin-right-10" placeholder="输入关键词" name="keyword" />
                            <select class="form-control input-small editer_category  margin-right-10" name="type">
                                <option value="-1">所有支付状态</option>
                                <option value="0"><?= Lang::_('paystatus0'); ?></option>
                                <option value="2"><?= Lang::_('paystatus2'); ?></option>
                                <option value="1"><?= Lang::_('paystatus1'); ?></option>
                                <option value="3"><?= Lang::_('paystatus3'); ?></option>
                            </select>
                            <input type="submit" class="btn blue breadcrumbbtn" value="搜索" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <?php if($mess){?>
            <div class="search-result">
                <dt><a href="/ltvugc_live/listPayment">所有结果</a></dt> >
                <dd>
                    <?php if($mess['keyword']):?>
                        <span><?=$mess['keyword']?></span>
                    <?php endif;?>
                </dd>
            </div>
        <?php } ?>
</div>

    <script type="text/javascript">
        $('.editer_category').select2({
            placeholder: "选择广告位类型",
            formatNoMatches: "没有匹配的选项",
            allowClear: true
        });
    </script>



